pom.xml, src/main/java/uk/gov/pay/ledger/app/LedgerApp.java, src/main/java/uk/gov/pay/ledger/event/EventResource.java, src/main/resources/config/config.yaml, src/main/resources/logback.xml, src/test/java/uk/gov/pay/ledger/event/EventIntegrationTest.java, src/test/java/uk/gov/pay/ledger/event/EventResourceTest.java, src/test/resources/config/test-config.yaml
- add logging framework
- add /v1/ to resource path
=> PP-5219 add logging framework to project

pom.xml, src/main/resources/config/config.yaml, src/test/resources/config/test-config.yaml, src/test/resources/logback.xml
- change the logging format to json type
=> PP-5219 implement json formatting for logging

Dockerfile, build-local.sh, docker-startup.sh
Adds a simple openjdk11 alpine container, startup script and local build script similar to other Pay application services.
This will allow a local application container to be built and run (requires local installation of maven). Once merged, further build pipeline development may continue.
=> PP-5115: Add Dockerfile and startup scripts

pom.xml, src/main/java/uk/gov/pay/ledger/app/LedgerApp.java, src/main/java/uk/gov/pay/ledger/app/LedgerModule.java, src/main/java/uk/gov/pay/ledger/event/dao/EventDao.java, src/main/java/uk/gov/pay/ledger/event/dao/mapper/EventMapper.java, src/main/java/uk/gov/pay/ledger/event/model/Event.java, src/main/java/uk/gov/pay/ledger/event/resources/EventResource.java, src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/dao/mapper/TransactionMapper.java, src/main/java/uk/gov/pay/ledger/transaction/model/Address.java, src/main/java/uk/gov/pay/ledger/transaction/model/CardDetails.java, src/main/java/uk/gov/pay/ledger/transaction/model/Transaction.java, src/main/java/uk/gov/pay/ledger/transaction/resources/TransactionResource.java, src/main/resources/migrations.xml, src/main/resources/migrations/00001_create_table_event.sql, src/main/resources/migrations/00002_create_table_transaction.sql, src/test/java/uk/gov/pay/ledger/event/EventResourceTest.java, src/test/java/uk/gov/pay/ledger/rules/AppWithPostgresRule.java, src/test/java/uk/gov/pay/ledger/transaction/TransactionIntegrationTest.java, src/test/java/uk/gov/pay/ledger/transaction/TransactionResourceTest.java, src/test/java/uk/gov/pay/ledger/utils/fixtures/DbFixture.java, src/test/java/uk/gov/pay/ledger/utils/fixtures/TransactionFixture.java, src/test/resources/config/test-config.yaml
- refactor project structure
- refactor migrations to use individual scripts
- add create transactions table script
- configure AppWithPostgresRule to use Jdbi
with @mrlumbu
=> PP-5251 Create transactions table

src/test/java/uk/gov/pay/ledger/transaction/TransactionIntegrationTest.java
Test containers still don't work on CI, so ignoring for now to unblock things
=> BAU Ignore IT test

src/main/java/uk/gov/pay/ledger/app/LedgerModule.java, src/main/java/uk/gov/pay/ledger/event/dao/EventDao.java, src/main/java/uk/gov/pay/ledger/event/dao/ResourceTypeDao.java, src/main/java/uk/gov/pay/ledger/event/dao/mapper/EventMapper.java, src/main/java/uk/gov/pay/ledger/event/model/Event.java, src/main/java/uk/gov/pay/ledger/event/model/ResourceType.java, src/main/java/uk/gov/pay/ledger/event/model/serializer/MicrosecondPrecisionDateTimeSerializer.java, src/main/java/uk/gov/pay/ledger/event/resources/EventResource.java, src/main/java/uk/gov/pay/ledger/transaction/model/Transaction.java, src/main/resources/migrations/00001_create_table_event.sql, src/main/resources/migrations/00001_create_table_transaction.sql, src/main/resources/migrations/00002_create_table_resource_type.sql, src/main/resources/migrations/00003_create_table_event.sql, src/test/java/uk/gov/pay/ledger/event/EventDaoITest.java, src/test/java/uk/gov/pay/ledger/event/EventIntegrationTest.java, src/test/java/uk/gov/pay/ledger/event/EventResourceTest.java, src/test/java/uk/gov/pay/ledger/rules/AppWithPostgresRule.java, src/test/java/uk/gov/pay/ledger/utils/DatabaseTestHelper.java, src/test/java/uk/gov/pay/ledger/utils/ZonedDateTimeTimestampMatcher.java, src/test/java/uk/gov/pay/ledger/utils/fixtures/EventFixture.java, src/test/java/uk/gov/pay/ledger/utils/fixtures/TransactionFixture.java
- add liquibase create event table
- add insert method to EventDao with ResourceType.id lookup
- add EventFixture
- ignore integration tests until further notice
=> PP-5250 create event table

src/main/java/uk/gov/pay/ledger/transaction/model/TransactionSearchResponse.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/main/java/uk/gov/pay/ledger/transaction/search/dao/TransactionSearchDao.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionSearchService.java, src/test/java/uk/gov/pay/ledger/it/transaction/search/dao/TransactionSearchDaoITest.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionSearchServiceTest.java, src/test/java/uk/gov/pay/ledger/utils/fixtures/TransactionViewFixture.java
- add transaction service to wrap results into `TransactionSearchResponse` after executing a search query
with @kbottla
=> PP-5256 add transaction service

src/main/java/uk/gov/pay/ledger/transaction/model/TransactionSearchResponse.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/CommaDelimitedSetParameter.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/HalLinkBuilder.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/Link.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/PaginationBuilder.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/PaginationLink.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/TransactionView.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/test/java/uk/gov/pay/ledger/transaction/search/model/PaginationBuilderTest.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java
- Added pagination links for transaction search results
- Added self, refund links for transactions
- Unit tests - PaginationBuilderTest, TransactionServiceTest (for search results)
=> PP-5256 Transaction Search - Adds links

src/main/java/uk/gov/pay/ledger/transaction/model/Address.java, src/main/java/uk/gov/pay/ledger/transaction/model/CardDetails.java
- match the JSON format of CardDetails to connector
=> PP-5256 match CardDetails to that of connector

src/test/java/uk/gov/pay/ledger/event/dao/EventDaoIT.java, src/test/java/uk/gov/pay/ledger/event/resource/EventResourceIT.java, src/test/java/uk/gov/pay/ledger/event/resource/EventResourceTest.java, src/test/java/uk/gov/pay/ledger/queue/QueueMessageReceiverIT.java, src/test/java/uk/gov/pay/ledger/queue/sqs/EventQueueIT.java, src/test/java/uk/gov/pay/ledger/queue/sqs/SqsQueueServiceTest.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceTest.java
- Reorganise test classes (including integration tests) to mirror packages
- Updated few integration tests suffix to IT so fail safe plugin can run them as integration tests
=> BAU - reorganise test classes

LICENSE, README.MD
* added license and responsible disclosure (taken from pay-connector)
* added description of all environment variables used in `config.yml` file grouped by categories
* added description of the background task
Question - is this the correct license?
=> PP-5254: update README.md

src/main/java/uk/gov/pay/ledger/queue/EventQueue.java
it may contain sensitive personal information
=> BAU avoid emitting message body to logs

src/main/java/uk/gov/pay/ledger/event/model/ResourceType.java, src/main/resources/migrations/00006_add_new_types_to_resource_type_table.sql, src/test/java/uk/gov/pay/ledger/pact/TransactionsApiContractTest.java, src/test/java/uk/gov/pay/ledger/queue/EventQueueTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/EventFixture.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueueEventFixture.java
- add new resource types (`payment`, `card_payment`) to match the one emitted from connector
- update code/tests
=> PP-5255 add new resource types to match connector

src/main/resources/migrations/00010_add_searchable_fields_to_transaction_table.sql
- pull the searchable fields to top level on transaction table
- add indexes to searchable fields
=> PP-5359 add searchable fields to top level

src/main/java/uk/gov/pay/ledger/event/model/TransactionEntityFactory.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/test/java/uk/gov/pay/ledger/event/model/TransactionEntityFactoryTest.java, src/test/java/uk/gov/pay/ledger/queue/QueueMessageReceiverIT.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueueEventFixture.java
* moved creating TransactionEntity to its own factory (from Transaction Service) <- only moved it, haven't changed the way it's been done
* test for ^^
* renamed fixture method
=> PP-5359: clean up

Jenkinsfile
Run consumer pact tests as part of build
=> PP-5355 Fix pact command

src/test/java/uk/gov/pay/ledger/util/fixture/QueueEventFixture.java
Make sure contracts assert the correct type, don't just assume things are strings \o/
=> PP-5355 Write contracts with correct type

Jenkinsfile
The connector side is now done, so this should work now. I have added provider tests and pact compatibility similarly to publicapi tests https://github.com/alphagov/pay-publicapi/blob/master/Jenkinsfile
=> PP-5355 Re-enable pact compatibility check

src/main/resources/migrations/00012_add_fields_to_transaction_table.sql
* added fields related to refund and settlement summary
* added fields related to fees (net_amount and total_amount)
=> PP-5360: additional fields in transaction table

src/main/java/uk/gov/pay/ledger/transaction/model/Address.java, src/main/java/uk/gov/pay/ledger/transaction/model/CardDetails.java, src/main/java/uk/gov/pay/ledger/transaction/model/Payment.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/TransactionView.java
* added static factory methods to Address and CardDetails to handle lack of data
* added JsonInclude annotation to TransactionView to show only non-null properties
=> PP-5359: handle null fields for search

src/main/java/uk/gov/pay/ledger/transaction/dao/mapper/TransactionMapper.java
* returns Optional
* behaviour of the non-existing date is defined in "consumer"
=> BAU: updated signature of getZonedDateTime

src/main/java/uk/gov/pay/ledger/event/model/TransactionEntityFactory.java, src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/entity/TransactionEntity.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/test/java/uk/gov/pay/ledger/event/model/TransactionEntityFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java
populate `net_amount` and `total_amount`
rename factory method (to follow convention)
=> PP-5460: populate fields

src/main/resources/migrations/00013_add_fee_column_to_transaction_table.sql, src/main/resources/migrations/00013_add_fee_columns_to_transaction_table.sql
* added `fee` ~and `corporate_surcharge`~ column~s~ to Transaction table - migration
=> PP-5460: new columns in transaction table

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/dao/mapper/TransactionMapper.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
* cast transaction_type string to `transaction_type_t` enum
* update fixture to allow `withTransactionType`
with @kbottla
=> PP-5457 Update transaction DAO - transaction type

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/dao/mapper/TransactionMapper.java, src/main/java/uk/gov/pay/ledger/transaction/entity/TransactionEntity.java, src/main/java/uk/gov/pay/ledger/transaction/model/PaymentFactory.java, src/test/java/uk/gov/pay/ledger/event/model/TransactionEntityFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java, src/test/java/uk/gov/pay/ledger/transaction/model/PaymentFactoryTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
* update db upsert query to include fee
* fix contract test to insert fee directly to the transaction table instead of transaction_detais column
* updated tests to make sure the fee is being populated
=> PP-5460 populate fee in transaction table

src/main/java/uk/gov/pay/ledger/transaction/search/model/ConvertedTransactionDetails.java, src/test/java/uk/gov/pay/ledger/event/model/TransactionEntityFactoryTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueueEventFixture.java
* add corporate_surcharge to ConvertedTransactionDetails to make sure it's part of the transaction_details column of Transaction table
=> PP-5460 populate corporate_surcharge in transactionDetails

src/main/resources/migrations/00016_add_parent_resource_external_id_to_event_table.sql
* migration script to add column
=> PP-5403 Add `parent_resource_external_id` to event

src/main/java/uk/gov/pay/ledger/event/dao/EventDao.java, src/main/java/uk/gov/pay/ledger/event/dao/mapper/EventMapper.java, src/main/java/uk/gov/pay/ledger/event/model/Event.java, src/main/java/uk/gov/pay/ledger/queue/EventMessage.java, src/main/java/uk/gov/pay/ledger/queue/EventMessageDto.java, src/main/resources/migrations/00016_add_parent_resource_external_id_to_event_table.sql, src/test/java/uk/gov/pay/ledger/event/dao/EventDaoIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/EventFixture.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueueEventFixture.java
* depends on https://github.com/alphagov/pay-ledger/pull/141
* add mapper logic for attribute
=> PP-5403 Event DAO + entity for `parent_resource_external_id`

src/test/java/uk/gov/pay/ledger/event/model/TransactionEntityFactoryTest.java, src/test/java/uk/gov/pay/ledger/pact/CaptureConfirmedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/pact/PaymentCreatedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueueEventFixture.java
validation of relevant transaction properties (filled based on the paymentCreated event)
=> BAU: update paymentCreated event contract test

src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java
add account_id query parame to get one transaction endpoint
=> PP-5419: add account_id query param

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/test/java/uk/gov/pay/ledger/pact/CaptureConfirmedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/pact/GetTransactionContractTest.java, src/test/java/uk/gov/pay/ledger/pact/PaymentDetailsEnteredEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/queue/QueueMessageReceiverIT.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java
* added account_id query parameter to get transaction endpoint
* added method to dao to retrieve transaction based on account_id and external_id
* updated pact provider
Update to public API: https://github.com/alphagov/pay-publicapi/pull/611
=> PP-5419 gateway account query parameter

src/main/java/uk/gov/pay/ledger/transaction/search/model/TransactionView.java
added builder for TransactionView
=> BAU: replaced many constructor arguments with builder (TransactionView)

src/main/java/uk/gov/pay/ledger/transaction/model/TransactionEvent.java, src/main/java/uk/gov/pay/ledger/transaction/model/TransactionEventResponse.java, src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java
- Adds endpoint (GET `/v1/transaction/{transactionId}/event`) to get transaction events
=> PP-5454 Transaction event resource endpoint

src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java, src/main/java/uk/gov/pay/ledger/transaction/service/AccountIdSupplierManager.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceTest.java, src/test/java/uk/gov/pay/ledger/transaction/service/AccountIdSupplierManagerTest.java
Naming improvements suggestions are more than welcome.
`TransactionView` is hard-coded at the moment - can be made generic in the future.
=> PP-5419 first draft of privileged flag (override_account_id_restriction)

src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java
- required by Krishna's endpoint
- removed by my PR (rebased before Krishna's PR has been merged)
Interesting one.
=> BAU: added removed required import

src/main/java/uk/gov/pay/ledger/transaction/entity/TransactionEntity.java
All fields in TransactionEntity should be mapped to snake case
when serialising to/deserialising from JSON
=> PP-5463 Snake case for transaction entity

src/main/java/uk/gov/pay/ledger/transaction/state/TransactionState.java
* map salient event to correct external state (according to current
Connector configuration)
=> BAU Fix AUTHORISATION_SUCCESS external state

src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceTest.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java
waiting on public api to be released first.
Can be reviewed - tests won't pass until I release public api first though.
=> PP-5419: remove links section from transaction

src/main/java/uk/gov/pay/ledger/transaction/model/TransactionEvent.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java
- `data` field from transaction event  (`/v1/transaction/{trasactionExternalId}/event`) endpoint is being returned as String which is now converted to JSON object
=> PP-5454 Structurize transaction event `data` object

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
- Adds DAO method to find `transactions` by parent_external_id and gateway_account_id
- Integration test
=> PP-5505 DAO method - Find transaction by ParentExternalId

src/main/java/uk/gov/pay/ledger/transaction/model/TransactionsForTransactionResponse.java, src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceTest.java
- Added `/transaction/{id}/transaction` endpoint that returns list of transactions for a parent transaction external id
- Relevant tests
=> PP-5505 Added /transaction/{parentId}/transaction endpoint

src/main/resources/migrations/00018_add_transaction_refunded_amount.sql
1. add additional column
2. move over functionality - https://github.com/alphagov/pay-ledger/pull/208
3. remove older column
=> PP-5541: add additional column for refunded amount

Jenkinsfile, src/main/java/uk/gov/pay/ledger/transaction/dao/mapper/TransactionMapper.java, src/main/java/uk/gov/pay/ledger/transaction/entity/TransactionEntity.java, src/main/java/uk/gov/pay/ledger/transaction/model/TransactionFactory.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/SettlementSummary.java, src/test/java/uk/gov/pay/ledger/pact/CaptureConfirmedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/pact/GetTransactionContractTest.java, src/test/java/uk/gov/pay/ledger/transaction/model/TransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
Rename settled_time to captured_date everywhere.
Move captured date from column to transaction details
=> PP-5462 Add captured date to tx details

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java
* add `transaction_type` and `parent_external_id` optional query parameters
* extended transaction Dao method
* updated (and added new) integration test
=> PP-5498: add query parameters to get transaction endpoint

src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java
Bit fiddly because we have one set of states but the search is on
two different transaction types.
=> PP-5555 Implement search for {payment,refund}_states

src/test/java/uk/gov/pay/ledger/pact/GetTransactionContractTest.java, src/test/java/uk/gov/pay/ledger/pact/TransactionEventsApiContractTest.java
- add selfservice to relevant pact tests as consumer
=> PP-5537 add selfservice to consumers in relevant pact tests

src/test/java/uk/gov/pay/ledger/pact/TransactionEventsApiContractTest.java
- reconfigure to use empty map for event_data
=> PP-5537 reconfigure transaction event test data

src/main/resources/migrations/00022_index_transaction_type_for_filtering.sql
* column used for searching in Toolbox and self service
* index to avoid full table scan
=> PP-5389 btree index for transaction type column

src/test/java/uk/gov/pay/ledger/pact/TransactionsApiContractTest.java
- add selfservice tag to consumers
=> PP-5537 add add selfservice consumer to transaction api contract test

src/test/java/uk/gov/pay/ledger/pact/TransactionsApiContractTest.java
- add a new state to cover selfservice search
=> PP-5537 add selfservice search state to transaction pact test

src/test/java/uk/gov/pay/ledger/pact/TransactionsApiContractTest.java
Reverts alphagov/pay-ledger#265
=> Revert "PP-5537 add add selfservice consumer to transaction api contract test"

src/main/resources/migrations/00025_index_transaction_lower_email.sql
- Creates Gin index to be able to search transactions by `email` using partial strings.`
=> PP-5389 Gin index for `email

src/main/resources/migrations/00027_gin_index_transaction_reference.sql
- Creates Gin index to be able to search transactions by partial `reference`
=> PP-5389 Gin index for `reference`

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java
* updating the on confict condition will allow to recalculate the transaciton state
on emitting duplicate event (it won't insert a new event, but refresh the transaction state), which
should be helpful when event data doesn't change but the way we map them to the transaction
=> PP-5605: force update transaction

src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceTest.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java
404 is the appropriate response in this case.
=> PP-5604 Return 404 getting events for non-existent transaction

src/main/resources/migrations/00030_add_live_column_to_transaction_table.sql
* add boolean `live` column to transaction table
* index column for analytics/ searching
=> PP-5659 Add transaction live column

src/main/java/uk/gov/pay/ledger/report/dao/ReportDao.java, src/main/java/uk/gov/pay/ledger/report/entity/PaymentCountByStateResult.java, src/main/java/uk/gov/pay/ledger/report/params/PaymentsReportParams.java, src/test/java/uk/gov/pay/ledger/report/dao/ReportDaoIT.java, src/test/java/uk/gov/pay/ledger/report/params/PaymentsReportParamsTest.java
Add a reports DAO with a method to perform a query to filter payments and return the counts of the filtered payments in each state.
=> PP-5671 Add report DAO

src/test/java/uk/gov/pay/ledger/pact/ContractTestSuite.java, src/test/java/uk/gov/pay/ledger/pact/PaymentNotificationCreatedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java
- add an event queue contract test for PaymentNotificationCreated event
=> PP-5445 add payment notification created pact test

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/dao/mapper/TransactionMapper.java, src/main/java/uk/gov/pay/ledger/transaction/dao/mapper/TransactionWithParentMapper.java, src/main/java/uk/gov/pay/ledger/transaction/entity/TransactionEntity.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
* add attribute live to transaction entity
* update DAO to write live attribute to database
* ignore attribute in JSON mapping
=> PP-5659 Add live attribute to transaction entity

src/main/java/uk/gov/pay/ledger/transaction/model/CardDetails.java, src/main/java/uk/gov/pay/ledger/transaction/model/CardType.java, src/main/java/uk/gov/pay/ledger/transaction/model/TransactionFactory.java, src/main/java/uk/gov/pay/ledger/util/serialiser/ToLowerCaseStringSerializer.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
- Return the card type in lower case from ledger
=> PP-5667 Return Card Type From Ledger

src/test/java/uk/gov/pay/ledger/pact/PaymentNotificationCreatedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java
- update telephone payment pact test with expiry_date, payment_provider and card_brand_label
=> PP-5681 update telephone payment pact test

src/main/java/uk/gov/pay/ledger/exception/BadRequestExceptionMapper.java
- this log output can be changed to warn as it is not an error
=> PP-5510 change log error to warn

src/main/java/uk/gov/pay/ledger/report/dao/ReportDao.java, src/main/java/uk/gov/pay/ledger/report/entity/TransactionSummaryResult.java, src/main/java/uk/gov/pay/ledger/report/params/ReportParams.java, src/main/java/uk/gov/pay/ledger/report/params/TransactionSummaryParams.java, src/main/java/uk/gov/pay/ledger/report/service/ReportService.java, src/test/java/uk/gov/pay/ledger/report/dao/ReportDaoIT.java, src/test/java/uk/gov/pay/ledger/report/resource/ReportResourceIT.java, src/test/java/uk/gov/pay/ledger/report/service/ReportServiceTest.java
- add a method to get transactions summary for selfservice
- refactor ReportDao
- add relevant/refactor tests
=> PP-5427 add transactions summary

src/test/java/uk/gov/pay/ledger/pact/ContractTest.java
- add a new contract test for the transaction summary
=> PP-5427 add contract test for transaction summary

src/main/java/uk/gov/pay/ledger/report/dao/ReportDao.java, src/test/java/uk/gov/pay/ledger/report/dao/ReportDaoIT.java
- sum amount when total_amount is null to get a precise statistical figure
=> PP-5427 sum amount when total_amount is null

src/test/java/uk/gov/pay/ledger/pact/ContractTest.java
- a payment in success state with all the trimmings
=> PP-5770 add pact state for a payment in success state

pom.xml
Reverts alphagov/pay-ledger#413
=> Revert "Bump maven-surefire-plugin from 3.0.0-M3 to 3.0.0-M4"

pom.xml
Reverts test containers, AWS Java SDK SQS dependabot PRs due to Ledger build failures.
=> Reverts dependabot PRs

pom.xml
Reverts alphagov/pay-ledger#455
=> Revert "PP-4573 Update maven plugin"

src/test/java/uk/gov/pay/ledger/pact/RefundCreatedByUserEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueueRefundEventFixture.java
- Add `user_email` to RefundCreatedByUser contract test
=> PP-5966 Add user_email to pact test

src/main/java/uk/gov/pay/ledger/transaction/model/TransactionFactory.java, src/main/java/uk/gov/pay/ledger/util/JsonParser.java, src/test/java/uk/gov/pay/ledger/util/JsonParserTest.java
- Adds new utility class to parse JSON node so the same can be used while generating CSV data from ledger
- Adds few tests for new class
=> PP-5970 Add utility class `JsonParser`

src/main/java/uk/gov/pay/ledger/app/LedgerApp.java, src/main/java/uk/gov/pay/ledger/app/LedgerModule.java, src/main/java/uk/gov/pay/ledger/report/entity/PerformanceReportEntity.java, src/main/java/uk/gov/pay/ledger/report/resource/PerformanceReportResource.java, src/test/java/uk/gov/pay/ledger/report/dao/PerformanceReportDaoIT.java, src/test/java/uk/gov/pay/ledger/report/resource/PerformanceReportResourceIT.java
I saw no need to implement a Service class here, so the PerformanceReportResource calls the PerformanceReportDao directly.
=> PP-5978: Implement /v1/report/performance-report endpoint

src/main/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactory.java, src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/main/java/uk/gov/pay/ledger/util/csv/CSVMessageBodyWriter.java, src/test/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java
- Replaces POJO with Map<String,Object> for CSV data endpoint response
- Few fixes in CsvTransactionFactory  data mapping
=> PP-5970 Use Map for CSV resource endpoint

src/main/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactory.java, src/test/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactoryTest.java
- Sanitise fields (input by user) against spreadsheet formula injection
- prepends values beginning with special characters (=@+-) with single quote https://www.owasp.org/index.php/CSV_Injection
=> PP-5970 Sanitise CSV fields

src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java
- Added temporary logging around each activity to understand the performance (time taken) for large CSV downloads
=> PP-5970 Add logging temporarily for CSV

src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java
- Fix logging class in TransactionService
=> PP-5970 Fix logging class

src/main/java/uk/gov/pay/ledger/event/dao/EventDao.java, src/main/java/uk/gov/pay/ledger/event/dao/mapper/EventTickerMapper.java, src/main/java/uk/gov/pay/ledger/event/model/EventTicker.java, src/test/java/uk/gov/pay/ledger/event/dao/EventDaoIT.java
Missing the `amount` attribute, add it.
=> PP-5991 Expose amount on EventTicker

src/main/java/uk/gov/pay/ledger/util/csv/CSVMessageBodyWriter.java
- Use BufferedWriter to write each line individually to output stream for CSV rather than streaming entire content.
=> PP-5970 Use BufferedWriter for CSV data

Jenkinsfile, pom.xml, src/test/java/uk/gov/pay/ledger/event/dao/EventDaoIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java
- Downgrade Maven failsafe plugin as latest version doesn't run integration tests on `mvn clean verify`
- Fixed few failing integration tests
- Run integration tests on master
=> BAU - Downgrade Maven failsafe to 3.0.0-M1

src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java
- Set accept header to `JSON` for tests to avoid hitting CSV endpoint
=> BAU - Set accept header for tests

src/main/java/uk/gov/pay/ledger/util/csv/CSVMessageBodyWriter.java
- Flush CSV data (after every 1000 rows) to start streaming immediately instead of buffering and streaming all at once
=> PP-5999 Flush CSV data stream

src/main/java/uk/gov/pay/ledger/app/LedgerModule.java, src/main/java/uk/gov/pay/ledger/metadatakey/dao/MetadataKeyDao.java, src/test/java/uk/gov/pay/ledger/metadatakey/dao/MetadataKeyDaoIT.java, src/test/java/uk/gov/pay/ledger/util/DatabaseTestHelper.java
- Added MetadataKeyDao with a method to insert new metadata key
- Relevant tests
=> PP-6059 Add MetadataKeyDao

src/main/java/uk/gov/pay/ledger/metadatakey/dao/MetadataKeyDao.java, src/main/java/uk/gov/pay/ledger/transaction/model/MetadataKey.java, src/test/java/uk/gov/pay/ledger/metadatakey/dao/MetadataKeyDaoIT.java, src/test/java/uk/gov/pay/ledger/transaction/model/MetadataKeyFromEventDigestTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java
- Adds a getByKey(String key) method to MetadataKeyDao to retrieve the
id by the key value
- add MetadataKey class
- add from EventDigest method to MetadataKey
with @sandorarpa
=> PP-6060 Add getByKey to MetadataKeyDao

.travis.yml
Adds .travis.yml necessary to run builds on Travis CI.
=> Run builds on travis

src/main/java/uk/gov/pay/ledger/app/LedgerApp.java, src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactory.java, src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java, src/main/java/uk/gov/pay/ledger/transaction/service/CsvService.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceTest.java
Performance depends on https://github.com/alphagov/pay-ledger/pull/551
=> PP-6058 StreamingOutput CSV writer

src/main/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactory.java, src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java, src/main/java/uk/gov/pay/ledger/transaction/service/CsvService.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionMetadataService.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java
- Derives and metadata keys to the headers for CSV streaming
Co-authored-by: Steven Fountain <steven.fountain@digital.cabinet-office.gov.uk>
=> PP-6061 Derive metadata headers for CSV stream

src/main/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactory.java, src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java, src/main/java/uk/gov/pay/ledger/transaction/service/CsvService.java, src/test/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactoryTest.java
CSV report end point allows consumer to include or remove fee columns.
Co-authored-by: Krishna Bottla <krishna.bottla@digital.cabinet-office.gov.uk>
=> PP-6100 Query param for consumer specifying fee columns

src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
Description:
- Added moto field and build method to TransactionFixture
- Added line in TransactionResourceIT to test for moto field
=> PP-5952 Update TransactionSearchAPI Moto

src/main/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactory.java, src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/test/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java
- remove searchCsv endpoint and any subsequent methods that are only used by this method.
- add a StopWatch and log how long it took for how many records to be streamed
- remove relevant tests
=> PP-6070 clean up csv development route

src/main/java/uk/gov/pay/ledger/transaction/search/model/TransactionView.java
Move it to a position of less significance.
=> PP-6078: Move moto json field

src/test/java/uk/gov/pay/ledger/pact/ContractTest.java
This fixes https://github.com/alphagov/pay-publicapi/pull/855
=> bau: Consolidate publicapi->ledger search pact

manifest.yml, src/main/resources/env-map.yml
This will use the VCAP_SERVICES environment variable to set all the
other variables.
=> PP-6085: Use env-map buildpack to set env vars

src/test/java/uk/gov/pay/ledger/pact/ContractTest.java
Relates to https://github.com/alphagov/pay-publicapi/pull/860
=> bau: Remove unused state

src/main/java/uk/gov/pay/ledger/transaction/model/Payment.java, src/main/java/uk/gov/pay/ledger/transaction/model/TransactionFactory.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/TransactionView.java, src/test/java/uk/gov/pay/ledger/transaction/model/TransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceCsvIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
- Added `wallet_type` to get one transaction response
=> PP-6141 Return wallet_type in transaction response

src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceCsvIT.java
- When a search is made with `accept: text/csv` as a header, it returns,
as a csv, the results for multiple gateway accounts when they are sent
as a comma separated parameter.
=> PP-6163 Stream CSV works with multiple GA's

src/main/java/uk/gov/pay/ledger/payout/entity/PayoutEntity.java, src/test/java/uk/gov/pay/ledger/payout/dao/PayoutDaoIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/PayoutFixture.java
- Remove the version long from the entity before it's removed from the
database table
=> PP-6262 Remove Version From Entity

src/main/resources/migrations/00042_drop_version_column_from_payouts.sql
- Remove the version column from the database to match the changes to
the entity.
=> PP-6262 Remove Version From Database

pom.xml, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsTest.java
Reverts
https://github.com/alphagov/pay-ledger/compare/a7a5a41a10ca47e02905b118b82f3438f1aa9395...8adab8c2d917b83e3a80a10eb3956eec03cc1a10
as integration tests are not being run in CI and pact compatibility breaks
Also includes https://github.com/alphagov/pay-ledger/pull/677 changes
=> BAU - Revert library upgrades and `live` flag change

src/main/java/uk/gov/pay/ledger/event/resource/EventResource.java, src/test/java/uk/gov/pay/ledger/event/resource/EventResourceTest.java
Use built in validation to validate ticker query params. Add resource test.
=> BAU Improve ticker validation

src/main/java/uk/gov/pay/ledger/event/model/SalientEventType.java, src/main/java/uk/gov/pay/ledger/transaction/state/TransactionState.java
Add base support role administrative events for payments and refund
success/ error states.
=> PP-6382 Support role salient base events (STROOP-30)

src/main/resources/migrations/00045_add_payout_type_to_resource_types.sql
Database migration adding `payout` entry for resource type table.
=> PP-6421 Payout entry in resource type table

src/main/java/uk/gov/pay/ledger/payout/dao/PayoutDao.java, src/main/java/uk/gov/pay/ledger/payout/dao/mapper/PayoutMapper.java, src/main/java/uk/gov/pay/ledger/payout/entity/PayoutEntity.java, src/test/java/uk/gov/pay/ledger/payout/dao/PayoutDaoIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/PayoutFixture.java
- Updated PayoutDao, mapper and relevant tests for new fields (event_count, payout_details) added to payout
=> PP-6421 Update DAO for event_count and payout_details

src/main/java/uk/gov/pay/ledger/app/LedgerModule.java, src/main/java/uk/gov/pay/ledger/event/model/ResourceType.java, src/main/java/uk/gov/pay/ledger/payout/dao/PayoutDao.java, src/main/java/uk/gov/pay/ledger/queue/EventDigestHandler.java, src/main/java/uk/gov/pay/ledger/queue/EventMessageHandler.java, src/test/java/uk/gov/pay/ledger/queue/EventDigestHandlerTest.java, src/test/java/uk/gov/pay/ledger/queue/EventMessageHandlerTest.java
- Added EventDigestHandler which looks up resource type and processes digest accordingly (i.e, by payout/refund or payout or unsupported)
=> PP-6421 Add EventDigestHandler

src/main/resources/migrations/00048_add_state_to_payout_table.sql
- add state column to payout table (to replace status in next iteration)
=> PP-6465 add state column to payout table

src/main/resources/migrations/00051_add_gateway_account_id_to_payout.sql
- add gateway_account_id varchar(255) to payout table
- add index on gateway_account_id to payout table
=> PP-6502 add gateway_account_id to payout table

src/main/java/uk/gov/pay/ledger/payout/dao/PayoutDao.java, src/main/java/uk/gov/pay/ledger/payout/dao/mapper/PayoutMapper.java, src/main/java/uk/gov/pay/ledger/payout/entity/PayoutEntity.java, src/test/java/uk/gov/pay/ledger/payout/dao/PayoutDaoIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/PayoutFixture.java
- add gateway account id to PayoutEntity
- update tests
=> PP-6025 add gateway account id to PayoutEntity

src/test/java/uk/gov/pay/ledger/pact/PayoutCreatedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePayoutEventFixture.java
- Added gateway_account_id (which connector provides for payout create event) to Payout created pact payload
=> PP-6469 Add gateway_account_id to PayoutCreated pact

src/main/java/uk/gov/pay/ledger/payout/dao/PayoutDao.java, src/main/java/uk/gov/pay/ledger/payout/search/PayoutSearchParams.java, src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsValidator.java, src/main/java/uk/gov/pay/ledger/util/CommaDelimitedSetParameter.java, src/test/java/uk/gov/pay/ledger/payout/dao/PayoutDaoSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsTest.java, src/test/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsValidatorTest.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java, src/test/java/uk/gov/pay/ledger/util/DatabaseTestHelper.java, src/test/java/uk/gov/pay/ledger/util/fixture/PayoutFixture.java
- add new method to PayoutDao
- add PayoutSearchParams class
- move CommaDelimitedSetParameter to common util class
- add relevant tests to specific new class PayoutDaoSearchIT
=> PP-6502 add search function to PayoutDao

src/main/java/uk/gov/pay/ledger/event/model/SalientEventType.java, src/main/java/uk/gov/pay/ledger/payout/state/PayoutState.java, src/test/java/uk/gov/pay/ledger/payout/model/PayoutEntityFactoryTest.java
- Changes payout salient events to match the events received from connector
=> PP-6486 Change payout salient events

src/main/java/uk/gov/pay/ledger/app/LedgerApp.java, src/main/java/uk/gov/pay/ledger/payout/resource/PayoutResource.java, src/main/java/uk/gov/pay/ledger/payout/search/PayoutSearchParams.java, src/main/java/uk/gov/pay/ledger/payout/service/PayoutService.java, src/main/java/uk/gov/pay/ledger/payout/state/PayoutState.java, src/test/java/uk/gov/pay/ledger/payout/dao/PayoutDaoSearchIT.java, src/test/java/uk/gov/pay/ledger/payout/resource/PayoutResourceSearchIT.java, src/test/java/uk/gov/pay/ledger/payout/service/PayoutServiceTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/PayoutFixture.java
- add payout endpoint
- add search payout to endpoint
- refactor PayoutSearchParams to use singular state
- add relevant test
=> PP-6502 add payout endpoint

src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsTest.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java
- Added new query parameter `gateway_payout_id` on transaction resource to list payments/refunds for a given payout ID
=> PP-6503 Add gateway_payout_id query param

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/dao/mapper/TransactionMapper.java, src/main/java/uk/gov/pay/ledger/transaction/dao/mapper/TransactionWithParentMapper.java, src/main/java/uk/gov/pay/ledger/transaction/entity/TransactionEntity.java, src/main/java/uk/gov/pay/ledger/transaction/model/Payment.java, src/main/java/uk/gov/pay/ledger/transaction/model/Refund.java, src/main/java/uk/gov/pay/ledger/transaction/model/Transaction.java, src/main/java/uk/gov/pay/ledger/transaction/model/TransactionFactory.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/TransactionView.java, src/test/java/uk/gov/pay/ledger/event/model/TransactionEntityFactoryTest.java, src/test/java/uk/gov/pay/ledger/pact/ConsumerContractTestSuite.java, src/test/java/uk/gov/pay/ledger/pact/PaymentIncludedInPayoutEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/pact/RefundIncludedInPayoutEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsTest.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueueRefundEventFixture.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
- Re-adding payout related changes as the issue has been identified that is causing NPE https://github.com/alphagov/pay-ledger/pull/767
This reverts commits
9c9f9a3...ffb019b
=> PP-6586 Revert "Revert payout id changes"

src/test/java/uk/gov/pay/ledger/pact/ContractTest.java
- add a new state for a selfservice search of payouts
=> PP-6491 add a payout search pact test

src/test/java/uk/gov/pay/ledger/pact/ContractTest.java
- truncate data before running payout pact test
=> PP-6491 fix pact test

pom.xml
Reverts alphagov/pay-ledger#789
=> Revert "Bump maven-shade-plugin from 3.2.3 to 3.2.4"

pom.xml, src/test/java/uk/gov/pay/ledger/event/model/EventDigestTest.java, src/test/java/uk/gov/pay/ledger/event/model/TransactionEntityFactoryTest.java, src/test/java/uk/gov/pay/ledger/event/resource/EventResourceTest.java, src/test/java/uk/gov/pay/ledger/event/service/EventServiceTest.java, src/test/java/uk/gov/pay/ledger/payout/model/PayoutEntityFactoryTest.java, src/test/java/uk/gov/pay/ledger/payout/service/PayoutServiceTest.java, src/test/java/uk/gov/pay/ledger/queue/EventDigestHandlerTest.java, src/test/java/uk/gov/pay/ledger/queue/EventMessageHandlerTest.java, src/test/java/uk/gov/pay/ledger/queue/EventQueueTest.java, src/test/java/uk/gov/pay/ledger/queue/sqs/SqsQueueServiceTest.java, src/test/java/uk/gov/pay/ledger/report/dao/builder/TransactionStatisticQueryTest.java, src/test/java/uk/gov/pay/ledger/report/resource/ReportResourceTest.java, src/test/java/uk/gov/pay/ledger/report/service/ReportServiceTest.java, src/test/java/uk/gov/pay/ledger/report/validator/TransactionSummaryValidatorTest.java, src/test/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/model/TransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceTest.java, src/test/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsTest.java, src/test/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsValidatorTest.java, src/test/java/uk/gov/pay/ledger/transaction/service/AccountIdSupplierManagerTest.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionMetadataServiceTest.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java, src/test/java/uk/gov/pay/ledger/transactionmetadata/dao/TransactionMetadataDaoIT.java, src/test/java/uk/gov/pay/ledger/util/JsonParserTest.java, src/test/java/uk/gov/pay/ledger/util/pagination/PaginationBuilderTest.java
- Upgrades unit tests to Junit5.
- Units tests should pass on CI
=> PP-6708 Upgrade to JUnit5

pom.xml, src/test/java/uk/gov/pay/ledger/extension/AppWithPostgresAndSqsExtension.java, src/test/java/uk/gov/pay/ledger/rule/PostgresTestDocker.java, src/test/java/uk/gov/pay/ledger/rule/SqsTestDocker.java
- An extension (for Junit5 support) to start and stop dropwizard application and required containers (sqs, postgres).
- same concepts of rule  https://github.com/alphagov/pay-ledger/blob/6caca4bda2bc4e99277f75f322f2316cb9876bf7/src/test/java/uk/gov/pay/ledger/rule/AppWithPostgresAndSqsRule.java#L25  are applied except it uses dropwizard extension and lifecycle callbacks
=> PP-6708 Add PostgresAndSqsExtension

pom.xml, src/test/java/uk/gov/pay/ledger/event/dao/EventDaoIT.java, src/test/java/uk/gov/pay/ledger/event/resource/EventResourceIT.java, src/test/java/uk/gov/pay/ledger/healthcheck/HealthCheckResourceIT.java, src/test/java/uk/gov/pay/ledger/metadatakey/dao/TransactionMetadataKeyDaoIT.java, src/test/java/uk/gov/pay/ledger/payout/dao/PayoutDaoIT.java, src/test/java/uk/gov/pay/ledger/payout/dao/PayoutDaoSearchIT.java, src/test/java/uk/gov/pay/ledger/payout/resource/PayoutResourceSearchIT.java, src/test/java/uk/gov/pay/ledger/queue/QueueMessageReceiverForTransactionIT.java, src/test/java/uk/gov/pay/ledger/queue/QueueMessageReceiverIT.java, src/test/java/uk/gov/pay/ledger/queue/sqs/EventQueueIT.java, src/test/java/uk/gov/pay/ledger/report/dao/PerformanceReportDaoIT.java, src/test/java/uk/gov/pay/ledger/report/dao/ReportDaoIT.java, src/test/java/uk/gov/pay/ledger/report/resource/PerformanceReportResourceIT.java, src/test/java/uk/gov/pay/ledger/report/resource/ReportResourceIT.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceCsvIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceTest.java, src/test/java/uk/gov/pay/ledger/transactionmetadata/dao/TransactionMetadataDaoIT.java
- Upgrades integration tests(*IT.java) to JUnit5.
=> PP-6708 Upgrade integration tests to Junit5

src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java
Previous PR missed adding a test for a new method added to TransactionDao, add this.
=> PP-6850 Add TransactionDao test

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/dao/mapper/TransactionMapper.java, src/main/java/uk/gov/pay/ledger/transaction/entity/TransactionEntity.java, src/main/java/uk/gov/pay/ledger/transaction/model/TransactionFactory.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/SettlementSummary.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/model/TransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceSearchIT.java
- join payout column on gateway_payout_id to transactions
- surface to resource level paid_out_date as settled_date
=> PP-6669 add payout date to settlement summary for transaction search

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java
- join payout table on gateway payout id to transactions when finding transactions
- update relevant tests
=> PP-6669 add payoutentity to find transaction queries

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoSearchIT.java
- join payout table on gateway payout id to transactions when cursor searching transactions
- add a relevant tests
=> PP-6669 add payout date to search transaction with cursor

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/dao/mapper/TransactionMapper.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsValidator.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsValidatorTest.java
- add from_settled_date and to_settled_date to the searchparams
- add validation
=> PP-6669 add settled dates to search params

src/test/java/uk/gov/pay/ledger/pact/ContractTest.java
- add a new state with payout details
=> PP-6670 add a new state for pact tests that uses settled date

src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsValidator.java, src/test/java/uk/gov/pay/ledger/pact/ContractTest.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsTest.java, src/test/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsValidatorTest.java
- refactor search by settled dates to new date format (yyyy-MM-dd)
- refactor tests to confirm new date format
- add pact state test
=> PP-7211 refactor search by settled dates

src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsValidator.java
- refactor settled date search validation and parsing to use pay-java-commons DateTimeUtils
=> PP-7211 refactor settled date search

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoSearchIT.java
- fix query bug when joining payout table to transactions with no gateway account id is present
=> PP-7223 fix query bug for priviliged accounts

src/test/java/uk/gov/pay/ledger/pact/ConsumerContractTestSuite.java, src/test/java/uk/gov/pay/ledger/pact/UserEmailCollectedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java
- Added pact test for new event sent by connector when email is patched
=> PP-7276 Add user email collected pact test

src/main/java/uk/gov/pay/ledger/event/model/EventDigest.java
Description:
- Removes lambdas with method references
- With @alexbishop1
=> PP-7609 - Refactor lambda into method references

src/test/java/uk/gov/pay/ledger/pact/ConsumerContractTestSuite.java, src/test/java/uk/gov/pay/ledger/pact/Gateway3dsExemptionResultObtainedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java
Description:
- This PR creates the JSON file which is needed on the consumer side to verify the pact
- With @alexbishop1
=> PP-7609 - Pact test for GATEWAY_3DS_EXEMPTION_RESULT_OBTAINED

src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java
`TransactionDaoIT` uses JUnit 5.
Also remove the access modifiers on the class and method to make the test more obviously JUnit 5.
=> PP-7696 Replace JUnit 4 @Ignore annotation with JUnit 5 @Disabled

.gitignore, src/main/resources/migrations/00055_add_value_column_to_transaction_metadata.sql, src/main/resources/migrations/00056_index_transaction_metadata_value_column.sql
- add a new column `value` to transaction_metadata table
- add btree index to transaction_metadata on lower(value)
=> PP-PP-7831 add value column to transaction_metadata table

src/main/java/uk/gov/pay/ledger/transactionmetadata/dao/TransactionMetadataDao.java, src/test/java/uk/gov/pay/ledger/transactionmetadata/dao/TransactionMetadataDaoIT.java
- add a new method to upsert values on transaction_metada table
- add relevant test
=> PP-7832 add upsert method to TransactionMetadataDao

src/main/java/uk/gov/pay/ledger/transaction/service/TransactionMetadataService.java, src/main/java/uk/gov/pay/ledger/transactionmetadata/dao/TransactionMetadataDao.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceCsvIT.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionMetadataServiceTest.java, src/test/java/uk/gov/pay/ledger/transactionmetadata/dao/TransactionMetadataDaoIT.java
- use upsert in place of insertIfNotExist in TransactionMetadataService
- remove insertIfNotExist method from TransactionMetadataService
- remove insertIfNotExist tests
- update all other tests
=> PP-7832 replace use of insertIfNotExists with upsert

src/main/resources/migrations/00058_make_key_on_metadata_key_unique.sql
- add a unique constraint on key column on metadata_key table
=> PP-7832 add unique constraint on key on metadata_key

src/main/java/uk/gov/pay/ledger/transaction/service/TransactionMetadataService.java
We've discovered that inserting new keys to `metadata_key` table might trigger a race condition whereupon two payments with same metadata key can try to insert the keys. Thus one of them is going to throw an error.
This solution is not the most elegant but it works. It lets the insertion of transaction_metadata be triggered and prevents skipping it.
- log exception if race condition happens
with @stephencdaly
=> PP-7832 add try-catch for race condition

src/main/resources/migrations/00059_add_transaction_summary_table.sql
- add new table transaction_summary
=> PP-8024 add transaction_summary table

src/main/resources/migrations/00060_rename_fee_in_transaction_summary.sql
- rename fee column to a more meaningful total_fee_in_pence
=> PP-8024 rename fee column in transaction_summary table

src/main/resources/migrations/00061_alter_column_type_on_transaction_summary_table_for_transaction_date.sql
- change transaction_date's type to date on transaction_summary table.
=> PP-8024 change column type

src/main/java/uk/gov/pay/ledger/app/LedgerModule.java, src/main/java/uk/gov/pay/ledger/transactionsummary/dao/TransactionSummaryDao.java, src/test/java/uk/gov/pay/ledger/transactionsummary/dao/TransactionSummaryDaoIT.java, src/test/java/uk/gov/pay/ledger/util/DatabaseTestHelper.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionSummaryFixture.java
Added DAO methods to insert/update transaction_summary or deduct transaction summary when transaction state changes
=> PP-8025 Add DAO methods for transaction_summary

src/test/java/uk/gov/pay/ledger/queue/QueueMessageReceiverIT.java
- Increase wait time so messages from queue are processed by queue message handler before asserting on the results.
=> PP-8025 Fix flakey test

.github/workflows/git-run-unit-test.yml
- add github action to run unit tests on PR creation and/or push (including merging to main)
with @stephencdaly
=> PP-8047 add github action

.github/workflows/run-tests.yml
=> PP-8047 Rename things in Github Actions workflow

src/main/java/uk/gov/pay/ledger/transaction/model/Payment.java, src/main/java/uk/gov/pay/ledger/transaction/model/TransactionFactory.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/TransactionView.java, src/test/java/uk/gov/pay/ledger/transaction/model/TransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
- Added `credential_external_id` to transaction response
=> PP-8270 Add credential_external_id to transaction response

src/test/java/uk/gov/pay/ledger/pact/Gateway3dsInfoObtainedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java
- add a new queue pact test for 3ds info obtained message
=> PP-8461 add pact test for 3ds info obtained event

src/test/java/uk/gov/pay/ledger/pact/GatewayRequires3dsAuthorisationEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java
- add new pact test for GatewayRequires3dsAuthorisation event
=> PP-8461 add pact test for gateway requires 3ds authorisation

src/main/java/uk/gov/pay/ledger/transaction/model/AuthorisationSummary.java, src/main/java/uk/gov/pay/ledger/transaction/model/Payment.java, src/main/java/uk/gov/pay/ledger/transaction/model/ThreeDSecure.java, src/main/java/uk/gov/pay/ledger/transaction/model/TransactionFactory.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/TransactionView.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java
Description:
- For the shape of the JSON see the JIRA ticket for PP-8534
- If either requires_3ds or version_3ds is in transaction_details then Ledger will return authorisation_summary JSON blob
=> PP-8534 - Include 3ds info for get payment

src/test/java/uk/gov/pay/ledger/pact/ContractTest.java
- small fix to include 3ds version in pact tests
=> PP-8535 fix contract tests

src/main/java/uk/gov/pay/ledger/eventpublisher/EventPublisher.java, src/main/java/uk/gov/pay/ledger/queue/EventMessageHandler.java
Pass exception message into EventPublisherException, and log
message when caught in EventMessageHandler. Log at warn rather than
error
=> PP-9017 Fix event publisher logging

src/test/java/uk/gov/pay/ledger/pact/FeeIncurredEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueueEventFixtureUtil.java
Add a pact test to check the FEE_INCURRED event generated by ledger has
the expected structure and is processed correctly by ledger.
with @SandorArpa
=> PP-8950 Add pact test for FEE_INCURRED event

src/test/java/uk/gov/pay/ledger/pact/ConsumerContractTestSuite.java
Tests need to be individually included in the suite. Add all tests that
were not included in the test suite.
=> PP-8950 Include contract tests in suite

src/main/java/uk/gov/pay/ledger/gatewayaccountmetadata/dao/GatewayAccountMetadataDao.java, src/test/java/uk/gov/pay/ledger/gatewayaccountmetadata/dao/GatewayAccountMetadataDaoIT.java, src/test/java/uk/gov/pay/ledger/util/DatabaseTestHelper.java, src/test/java/uk/gov/pay/ledger/util/fixture/GatewayAccountMetadataFixture.java
- Added DAO to handle gateway_account_metadata operations
=> PP-9311 Add GatewayAccountMetadataDao

src/main/java/uk/gov/pay/ledger/event/model/ResourceType.java, src/main/java/uk/gov/pay/ledger/queue/EventDigestHandler.java, src/main/java/uk/gov/pay/ledger/queue/eventprocessor/DisputeEventProcessor.java, src/test/java/uk/gov/pay/ledger/queue/EventDigestHandlerTest.java
- Making sure ledger is able to process the new resource type without throwing an error, but just ignore the event for now.
=> PP-9258 add new resource type

src/main/java/uk/gov/pay/ledger/transaction/service/TransactionMetadataService.java, src/main/java/uk/gov/pay/ledger/transactionmetadata/dao/TransactionMetadataDao.java, src/test/java/uk/gov/pay/ledger/transactionmetadata/dao/TransactionMetadataDaoIT.java
We no longer look up metadata keys on individual transactions as part of Ledger performance improvement work
=> PP-9311 Clean up unused DAO queries

src/main/resources/migrations/00069_add_dispute_type_to_resource_types.sql, src/test/java/uk/gov/pay/ledger/queue/QueueMessageReceiverIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueueDisputeEventFixture.java
- add new resource type to resource_type table
- add integration test
=> PP-9258 add dispute to resource type

.github/workflows/post-merge.yml
Follows the pattern of https://github.com/alphagov/pay-adminusers/pull/1287
=> PP-9236: Run provider contract tests

.github/workflows/post-merge.yml, .github/workflows/run-tests.yml
Follows the pattern of https://github.com/alphagov/pay-publicapi/pull/1388.
=> PP-9236: Publish and tag ledger consumer pact

.github/workflows/post-merge.yml, Jenkinsfile
We can see the "Run Connector as Provider" check on this PR run successfully.
=> Pp 9236 run pact provider tests

.github/workflows/_run-pact-provider-tests.yml
See equivalent connector PR: https://github.com/alphagov/pay-connector/pull/3533
=> BAU: Fix provider contract tests to use the consumer and tag correctly

.github/workflows/_run-pact-provider-tests.yml
Same as [Adminusers](https://github.com/alphagov/pay-adminusers/pull/1291) and [Connector](https://github.com/alphagov/pay-connector/pull/3535) - fix the Pact provider version tagging.
=> [BAU] Fix Pact Provider version SHA

openapi/ledger_spec.yaml, src/main/java/uk/gov/pay/ledger/exception/ErrorResponse.java, src/main/java/uk/gov/pay/ledger/healthcheck/HealthCheckResource.java, src/main/java/uk/gov/pay/ledger/report/dao/PerformanceReportDao.java, src/main/java/uk/gov/pay/ledger/report/entity/GatewayAccountMonthlyPerformanceReportEntity.java, src/main/java/uk/gov/pay/ledger/report/entity/PerformanceReportEntity.java, src/main/java/uk/gov/pay/ledger/report/entity/TimeseriesReportSlice.java, src/main/java/uk/gov/pay/ledger/report/entity/TransactionSummaryResult.java, src/main/java/uk/gov/pay/ledger/report/entity/TransactionsStatisticsResult.java, src/main/java/uk/gov/pay/ledger/report/params/TransactionSummaryParams.java, src/main/java/uk/gov/pay/ledger/report/resource/PerformanceReportResource.java, src/main/java/uk/gov/pay/ledger/report/resource/ReportResource.java, src/main/resources/openapi-config.yaml, src/test/java/uk/gov/pay/ledger/report/resource/ReportResourceIT.java
- Updates to generate openAPI specs for reporting and healthcheck endpoints
=> PP-9456 OpenAPI specs for reporting & healthcheck endpoints

pom.xml
Reverts alphagov/pay-ledger#1844
=> Revert "Bump dropwizard-bom from 2.0.29 to 2.1.0"

src/test/java/uk/gov/pay/ledger/pact/AdminusersContractTest.java, src/test/java/uk/gov/pay/ledger/pact/ProviderContractTestSuite.java
- add adminusers-as-consumer pact test set up.
=> PP-9307 add new pact test set up

src/test/java/uk/gov/pay/ledger/pact/ConsumerContractTestSuite.java, src/test/java/uk/gov/pay/ledger/pact/DisputeCreatedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueueDisputeEventFixture.java
- implement `a dispute created event` pact test
=> PP-9577 add dispute created event pact test

src/test/java/uk/gov/pay/ledger/pact/ConsumerContractTestSuite.java, src/test/java/uk/gov/pay/ledger/pact/DisputeWonEventQueueContractTest.java
- implement `a dispute won event` pact test
=> PP-9577 add dispute won event pact test

src/test/java/uk/gov/pay/ledger/pact/ConsumerContractTestSuite.java, src/test/java/uk/gov/pay/ledger/pact/DisputeEvidenceSubmittedEventQueueContractTest.java
- implement `a dispute evidence submitted event` pact test
=> PP-9577 add dispute evidence submitted event pact test

src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/main/java/uk/gov/pay/ledger/transaction/state/TransactionState.java, src/test/java/uk/gov/pay/ledger/report/service/ReportServiceTest.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceSearchIT.java
- implement search by `transaction_type` (DISPUTE)
- implement search by `dispute_states`
- update `TransactionSearchParams` to handle `dispute_states`
- add/update relevant tests
=> PP-9627 implement search disputes

src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java
- add a `search by state` test for disputes
=> PP-9627 additional test

src/main/java/uk/gov/pay/ledger/util/DisputeReasonMapper.java, src/test/java/uk/gov/pay/ledger/util/DisputeReasonMapperTest.java
- refactor `DisputeReasonMapper` to handle null value
- add test
=> PP-9627 -fix reason mapper

src/test/java/uk/gov/pay/ledger/pact/DisputeCreatedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueueDisputeEventFixture.java
- Added `evidence_due_date` back to DISPUTE_CREATED event pact test
=> PP-9788 Add evidence_due_date to DISPUTE_CREATED pact

src/main/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactory.java, src/main/java/uk/gov/pay/ledger/transaction/state/DisputeState.java, src/test/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceCsvIT.java, src/test/java/uk/gov/pay/ledger/transaction/state/DisputeStateTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
- Changes to map dispute transactions for CSV download.
=> PP-9673 CSV downloads for `Dispute` transactions

src/test/java/uk/gov/pay/ledger/pact/ContractTest.java, src/test/java/uk/gov/pay/ledger/pact/PublicApiContractTest.java
- add a new pact state for a dispute lost transaction
=> PP-9576 add a dispute lost transaction pact test

src/test/java/uk/gov/pay/ledger/pact/ContractTest.java
- Added pact state for dispute transaction search (selfservice)
=> PP-9673 Add pact state

src/test/java/uk/gov/pay/ledger/pact/ContractTest.java
- Updated `dispute lost transaction exists` pact state to set defaults for state params so that the same state can be used by the selfservice pact test
=> PP-9662 Update pact state

src/main/java/uk/gov/pay/ledger/app/config/QueueMessageReceiverConfig.java, src/main/java/uk/gov/pay/ledger/queue/eventprocessor/ChildTransactionEventProcessor.java, src/main/resources/config/config.yaml, src/test/java/uk/gov/pay/ledger/queue/QueueMessageReceiverIT.java, src/test/java/uk/gov/pay/ledger/queue/eventprocessor/ChildTransactionEventProcessorTest.java, src/test/resources/config/test-config.yaml
- Removed feature flags for disputes as we are now projecting disputes in all environments.
=> PP-9956 Remove dispute feature flags

.github/workflows/_run-pact-provider-tests.yml, .github/workflows/post-merge.yml, .github/workflows/run-tests.yml
checked for Ubuntu 18.04 images and updated to ubuntu-latest.
=> PP-10035 Updated ubuntu 18.04 to ubuntu-latest

src/main/java/uk/gov/pay/ledger/agreement/resource/AgreementSearchParams.java, src/test/java/uk/gov/pay/ledger/agreement/resource/AgreementResourceIT.java
Accept display_size query parameter for searching agreements and use in the search.
=> PP-10485 Allow custom display_size for searching agreements

src/test/java/uk/gov/pay/ledger/agreement/resource/AgreementResourceIT.java
Add assertions to an integration tests for the search agreements endpoint to check that the response includes pagination links.
=> PP-10485 Add test assertions that links are included

.secrets.baseline, openapi/ledger_spec.yaml, src/main/java/uk/gov/pay/ledger/agreement/resource/AgreementResource.java, src/main/java/uk/gov/pay/ledger/agreement/resource/AgreementSearchParams.java, src/main/resources/openapi-config.yaml
- Add descriptions and examples to parameters for AgreementResource
- Move annotations from fields to setters for consistency
- Update Api response descriptions for AgreementResource
=> PP-10511 Update openAPI spec for RCP

.editorconfig
- missing .editorconfig file, add it!
with @alan-gds
=> BAU add .editorconfig file

.secrets.baseline, openapi/ledger_spec.yaml, pom.xml, src/main/java/uk/gov/pay/ledger/agreement/entity/AgreementsFactory.java, src/main/java/uk/gov/pay/ledger/event/model/SalientEventType.java, src/test/java/uk/gov/pay/ledger/agreement/entity/AgreementsFactoryTest.java
- add a new `SalientEventType`, `AGREEMENT_INACTIVATED`
- refactor `AgreementsFactory` to handle new SalientType
- add a test to check if event is handled correctly
=> PP-10949 add new salient type

README.MD
Update README information on environment variables for SNS, SQS, and general AWS config.
=> PP-10762: Document SNS environment variables

.secrets.baseline, openapi/ledger_spec.yaml, pom.xml
- update pay-java-commons to latest, and re-generate openapi spec.
=> PP-10977 re-generate openapi spec

.secrets.baseline, src/test/java/uk/gov/pay/ledger/pact/ContractTest.java
-add external id param to pact test
=> PP-10982 add transaction id to pact test

src/main/resources/migrations/00077_add_cancelled_information_to_agreements_table.sql
- add cancelled_date
- add cancelled_by_user_email
=> PP-10520 add cancelled information columns to agreement table

.secrets.baseline, src/test/java/uk/gov/pay/ledger/pact/ContractTest.java
- add events to the pact state with an agreement and payment instrument
=> PP-11121 add pact state for agreement with events

.secrets.baseline, src/test/java/uk/gov/pay/ledger/pact/ContractTest.java
- add event count to agreement
- set agreement as not live
=> PP-11121 fix pact test

.secrets.baseline, src/test/java/uk/gov/pay/ledger/pact/ContractTest.java
- refactor 3 agreements so selfservice can use it
- refactor agreement with payment instrument so we can param reference
with @james-peacock-gds
=> PP-9884 refactor agreement pact tests

pom.xml, src/main/java/uk/gov/pay/ledger/app/LedgerApp.java, src/main/java/uk/gov/pay/ledger/app/LedgerConfig.java, src/main/resources/config/config.yaml, src/test/resources/config/test-config.yaml
Set up a prometheus metric endpoint /metrics.
Append ECS metadata info (via the PrometheusDefaultLabelSampleBuilder class in pay-java-commons) as default labels.
=> PP-11223: Set up prometheus metrics

.secrets.baseline, openapi/ledger_spec.yaml, src/main/java/uk/gov/pay/ledger/event/resource/EventResource.java, src/main/java/uk/gov/pay/ledger/queue/EventMessageDto.java, src/test/java/uk/gov/pay/ledger/event/resource/EventResourceAgreementIT.java, src/test/java/uk/gov/pay/ledger/event/resource/EventResourceIT.java, src/test/java/uk/gov/pay/ledger/event/resource/EventResourceTest.java
- Make timestamp, externalId, resourceType and eventType mandatory for post events endpoint
- Update openapi spec
- Add unit tests
- Add response status code check to integration test
=> PP-11246 Set mandatory fields for events

.github/workflows/_run-pact-provider-tests.yml, .github/workflows/post-merge.yml, src/test/java/uk/gov/pay/ledger/pact/AdminusersContractTest.java, src/test/java/uk/gov/pay/ledger/pact/ConnectorContractTest.java, src/test/java/uk/gov/pay/ledger/pact/PublicApiContractTest.java, src/test/java/uk/gov/pay/ledger/pact/SelfServiceContractTest.java, src/test/java/uk/gov/pay/ledger/pact/WebhooksContractTest.java
=> PP-11292 update pact broker host

src/test/java/uk/gov/pay/ledger/rule/SqsTestDocker.java
=> BAU: Pin to elasticmq v1.4.2

src/main/java/uk/gov/pay/ledger/event/dao/EventDao.java, src/test/java/uk/gov/pay/ledger/event/dao/EventDaoIT.java
- Added DAO method to remove events for the list of transactions provided
=> PP-11232 Add DAO method to remove events

src/main/java/uk/gov/pay/ledger/app/LedgerConfig.java, src/main/java/uk/gov/pay/ledger/app/config/ExpungeOrRedactHistoricalDataConfig.java, src/main/java/uk/gov/pay/ledger/expunge/service/ExpungeOrRedactService.java, src/main/resources/config/config.yaml, src/test/java/uk/gov/pay/ledger/expunge/service/ExpungeOrRedactServiceTest.java, src/test/resources/config/test-config.yaml
- Added a service method to expunge/redact historical data
- Adds the core structure and logs when the flag is disabled. It also sends metrics for the total duration of the task.
=> PP-11232 Add service method to expunge/redact historical data

src/main/java/uk/gov/pay/ledger/expungeorredact/dao/TransactionRedactionInfoDao.java, src/main/java/uk/gov/pay/ledger/expungeorredact/service/ExpungeOrRedactService.java, src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/test/java/uk/gov/pay/ledger/expungeorredact/dao/TransactionRedactionInfoDaoIT.java, src/test/java/uk/gov/pay/ledger/expungeorredact/service/ExpungeOrRedactServiceTest.java, src/test/java/uk/gov/pay/ledger/util/DatabaseTestHelper.java
- Added TransactionRedactionInfo DAO method to create and update `last_processed_transaction_created_date`
=> PP-11232 Add TransactionRedactionInfo DAO method

.secrets.baseline, src/test/java/uk/gov/pay/ledger/pact/ContractTest.java
=> PP-11511 add wallet_type Pact state

src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java
- for unknown reasons, Github actions are not starting Postgres correctly for nested test classes and failing integration tests. Moving them out of nested test classes.
=> PP-11232 Move Itests out of nested test classes

.secrets.baseline, README.MD, openapi/ledger_spec.yaml, src/main/java/uk/gov/pay/ledger/app/LedgerApp.java, src/main/java/uk/gov/pay/ledger/app/LedgerConfig.java, src/main/java/uk/gov/pay/ledger/app/LedgerModule.java, src/main/java/uk/gov/pay/ledger/expungeorredact/resource/ExpungeOrRedactResource.java, src/main/resources/openapi-config.yaml, src/test/java/uk/gov/pay/ledger/expungeorredact/resource/ExpungeOrRedactResourceIT.java, src/test/resources/config/test-config.yaml
- Added a resource endpoint to redact historical data
=> PP-11232 Add resource to redact historical data

.github/workflows/_run-pact-provider-tests.yml, .github/workflows/run-tests.yml, src/test/java/uk/gov/pay/ledger/queue/QueueMessageReceiverIT.java, src/test/java/uk/gov/pay/ledger/rule/PostgresTestDocker.java
Bump Postgres to 15.2, like we have in our real envs.
=> PP-11895-upgrade-postgres-container

src/main/java/uk/gov/pay/ledger/transaction/model/TransactionFactory.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/RefundSummary.java, src/test/java/uk/gov/pay/ledger/transaction/model/TransactionFactoryTest.java
This is because we don't support EPDQ or Smartpay anymore.
=> PP-11613: Make refund status for EPDQ/Smartpay always be unavailable

README.MD, src/main/resources/config/config.yaml, src/test/resources/config/test-config.yaml
Bind to 127.0.0.1 by default instead of 0.0.0.0
I followed the exact same testing strategy as https://github.com/alphagov/pay-connector/pull/5539 and achieved the same results
=> PP-13145: Accept BIND_HOST env var and default to localhost

pom.xml, src/main/java/uk/gov/pay/ledger/transaction/search/model/PaymentSettlementSummary.java, src/test/java/uk/gov/pay/ledger/payout/resource/PayoutResourceSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceSearchIT.java
Reverts alphagov/pay-ledger#3577
=> Revert "PP-13220 Update to latest Pay Java commons"

pom.xml, src/main/java/uk/gov/pay/ledger/transaction/search/model/PaymentSettlementSummary.java, src/test/java/uk/gov/pay/ledger/payout/resource/PayoutResourceSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceSearchIT.java
Reverts alphagov/pay-ledger#3578
=> Revert "Revert "PP-13220 Update to latest Pay Java commons""

src/test/java/uk/gov/pay/ledger/pact/event/Requested3dsExemptionQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java
Changes on connector are through, we can unignore the relevant pact test.
=> PP-13430 unignore pact test

src/main/java/uk/gov/pay/ledger/transaction/model/TransactionFactory.java, src/test/java/uk/gov/pay/ledger/transaction/model/TransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
Use correct property value when adding exemption object to payments returned by ledger endpoints.
=> PP-13439 use correct property value

src/main/java/uk/gov/pay/ledger/transaction/model/TransactionFactory.java, src/test/java/uk/gov/pay/ledger/transaction/model/TransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
Reverts alphagov/pay-ledger#3688
=> Revert "PP-13439 use correct property value"

src/test/java/uk/gov/pay/ledger/pact/event/GatewayDoesNotRequire3dsAuthorisationEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java
Add a queue message pact test for GatewayDoesNotRequire3dsAuthorisation event.
=> PP-13436 add pact test

pom.xml
Fine tune Dropwizard 4 bom dependencies.
=> PP-13654  refine Dropwizard 4 migration
