alphagov/pay-ledger

pom.xml, src/test/java/uk/gov/pay/ledger/event/EventIT.java
Split the unit & integration tests and name integration tests to match the
default inclusion rules for the failsafe plugin.
=> Add surefire and failsafe plugins for unit & integration tests

src/test/java/uk/gov/pay/ledger/event/EventIntegrationTest.java
Test containers don't seem to work in CI. In order
to unblock infra work around ledger, ignore test that
uses them for now.
=> BAU Ignore integration test

Jenkinsfile
Adds a Jenkinsfile to build, test and (later) deploy the ledger service.
The Jenkins CI configuration must be updated in alphagov/pay-chef to scan and build this repository. Once this has been deployed to CI, this application may be built.
=> PP-5115: Add ledger Jenkinsfile build configuration

src/test/java/uk/gov/pay/ledger/rules/AppWithPostgresRule.java
**WHAT**
This is the version of PostgreSQL provisioned for the ledger hosting environment. Tests (once written & enabled) should be run using the same version.
**HOW**
This can be tested locally by running:`mvn build verify`. This will run tests using the official postgres 11.1 image.
=> RED-54: Use PostgreSQL 11.1 container for tests

Jenkinsfile
**What it does**
Enables the deploy and complete stages for the Jenkins build process run on CI. Currently this will only run in CI since the deploy instance has not yet been configured with the ledger service.
**How to test**
When changes are pushed to master they should be deployed to the configured environment.
=> RED-55: Enable CI deploy stage

Jenkinsfile
We don't have pact setup for ledger. So `checkPactCompatibility` can be disabled for now
=> BAU: Disabled Pact compatibility check

docker-startup.sh, src/main/java/uk/gov/pay/ledger/app/LedgerApp.java, src/main/java/uk/gov/pay/ledger/healthcheck/HealthCheckResource.java, src/main/resources/config/config.yaml, src/test/resources/config/test-config.yaml
Adds healthcheck on 'normal' port rather than the
dropwizard default of admin port.
Adds necessary server + db config to get things moving
and working inpay local.
=> PP-5249 Add healthcheeck and db config

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/model/Transaction.java, src/main/java/uk/gov/pay/ledger/transaction/resources/TransactionResource.java, src/test/java/uk/gov/pay/ledger/transaction/TransactionIntegrationTest.java, src/test/java/uk/gov/pay/ledger/transaction/TransactionResourceTest.java
- Rename charge_id to external id in Transaction model
- For transactions, change example endpoint and test
to be getById - it was confusing for
GET /v1/transaction/{id}
to return a list filtered by gateway account id
- Use snake case naming strategy in transaction model
=> PP-5251 Tidy ups

src/main/java/uk/gov/pay/ledger/app/LedgerApp.java, src/main/java/uk/gov/pay/ledger/exception/BadRequestException.java, src/main/java/uk/gov/pay/ledger/exception/BadRequestExceptionMapper.java, src/main/java/uk/gov/pay/ledger/exception/ErrorResponse.java, src/main/java/uk/gov/pay/ledger/exception/UnparsableDateException.java, src/main/java/uk/gov/pay/ledger/transaction/resources/TransactionResource.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsValidator.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/TransactionView.java, src/main/java/uk/gov/pay/ledger/transaction/state/TransactionState.java, src/test/java/uk/gov/pay/ledger/it/resource/transaction/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/it/transaction/search/TransactionDaoSearchITest.java, src/test/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsValidatorTest.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java
- Added validation for search query parameters `from_date` and `to_date`
- Adds validation with in resource endpoint method as Dropwizards query parameter validation doesn't support custom json error response
- Changes `from_date` & `to_date` to String as Dropwizard custom deserialiser (to ZonedDateTime) is not supported for query parameters
- Units tests for TransactionSearchParamsValidator
- Updated integration test `TransactionDaoSearchITest` to ensure all query params are processed
with @SandorArpa
=> PP-5256 Transaction search - resource parameter validation

src/main/resources/config/config.yaml
Added `sslfactory` to mitigate the `error=org.postgresql.util.PSQLException: Could not open SSL root certificate file /root/.postgresql/root.crt.` issue
(Tested in local docker environment)
=> BAU: update to db connection string

src/main/java/uk/gov/pay/ledger/exception/ValidationException.java, src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/resources/TransactionResource.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsValidator.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/test/java/uk/gov/pay/ledger/it/resource/transaction/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsValidatorTest.java, src/test/java/uk/gov/pay/ledger/transaction/search/model/PaginationBuilderTest.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java
- Transaction API endpoints changed from `/v1/api/accounts/{accountId}....` to
`/v1/transaction/{transactionExternalId}` - to find a single transaction
`/v1/transaction?query_params` - to search transactions
- Validation for `accound_id` which is now a query parameter for transaction search endpoint
- Updates relevents DAO queries, methods, and tests to reflect above changes
=> PP-5257 Change API structure for transactions

Jenkinsfile, pom.xml, src/test/java/uk/gov/pay/ledger/pact/ContractTestSuite.java, src/test/java/uk/gov/pay/ledger/pact/TransactionsApiContractTest.java
- Adds provider state for transaction search pact between public api and ledger (for PaymentCreated event)
- Excludes `common-lang3`(version 3.4) transitive dependency from pact-provider dependency which is causing compile error on usage of `RandomUtils.nextLong()` which is only available in latest version (commons-lang3-3.8.1)
=> PP-5527 Provider state for Transaction search pact

src/main/java/uk/gov/pay/ledger/app/LedgerApp.java, src/main/java/uk/gov/pay/ledger/app/config/QueueMessageReceiverConfig.java, src/main/resources/config/config.yaml, src/test/java/uk/gov/pay/ledger/it/queue/sqs/EventQueueIT.java, src/test/java/uk/gov/pay/ledger/it/queue/sqs/QueueEventProcessingIT.java, src/test/java/uk/gov/pay/ledger/rule/AppWithPostgresAndSqsRule.java, src/test/resources/config/test-config.yaml
* There was some sort of interference between the tests that caused sqs integration tests to fail when run with all of them
* Introduced `backgroundProcessingEnabled` configuration variable which is turned off for all the tests but selected one
* small cleanup in `EventQueueIT` test
=> BAU: fix flaky tests

src/test/java/uk/gov/pay/ledger/event/dao/EventDaoIT.java, src/test/java/uk/gov/pay/ledger/event/resource/EventResourceIT.java, src/test/java/uk/gov/pay/ledger/queue/QueueMessageReceiverIT.java, src/test/java/uk/gov/pay/ledger/queue/sqs/EventQueueIT.java, src/test/java/uk/gov/pay/ledger/rule/AppWithPostgresAndSqsRule.java, src/test/java/uk/gov/pay/ledger/rule/PostgresTestDocker.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java
- Enables all integration tests except `EventQueueIT` as it is flaky in CI but works fine in local dev environment
- Uses single docker container (postgres, sqs) for all tests
- Uses GenericContainer for postgres DB instead of test containers `PostgreSQLContainer`
- CI should pass
- Only one container for postgres/sqs should be started for all tests (can check with tests run locally and monitor docker containers)
=> PP-5342 - Enable Integration tests in CI

src/main/java/uk/gov/pay/ledger/event/dao/EventDao.java, src/main/java/uk/gov/pay/ledger/event/model/Event.java, src/main/java/uk/gov/pay/ledger/event/model/EventDigest.java, src/main/java/uk/gov/pay/ledger/event/model/EventType.java, src/main/java/uk/gov/pay/ledger/event/model/response/CreateEventResponse.java, src/main/java/uk/gov/pay/ledger/event/service/EventService.java, src/main/java/uk/gov/pay/ledger/queue/EventMessageHandler.java, src/test/java/uk/gov/pay/ledger/event/dao/EventDaoIT.java, src/test/java/uk/gov/pay/ledger/event/resource/EventResourceIT.java, src/test/java/uk/gov/pay/ledger/event/service/EventServiceTest.java, src/test/java/uk/gov/pay/ledger/queue/EventMessageHandlerTest.java, src/test/java/uk/gov/pay/ledger/queue/EventQueueTest.java, src/test/java/uk/gov/pay/ledger/queue/QueueMessageReceiverIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/EventFixture.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueueEventFixture.java
First step in going from receiving an event to writing a transaction. The main idea is the event digest, 
that is used to make sense of the event history for a given resource_external_id.
The EventDigest is an object that represents the summary of a list of events pertinent to the further processing of those events. Basically that amounts to the timestamp and event type of the latest event by timestamp, as well as a compressed digest of the event details attached to each event. The idea is that this EventDigest is easily convertible into a Transaction. The way event details are compressed, if two event_detail objects both contain an attribute then the later event will overwrite the earlier one.  
This PR also introduces EventType enum. As part of this I have changed the name of the …
=> Pp 5255 event digest

src/test/java/uk/gov/pay/ledger/pact/TransactionsApiContractTest.java, src/test/java/uk/gov/pay/ledger/util/DatabaseTestHelper.java
- truncate tables before pact test runs to avoid multiple transaction records
=> PP-5257 truncate tables before running pact test

pom.xml, src/main/java/uk/gov/pay/ledger/transaction/dao/mapper/TransactionMapper.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/main/resources/migrations/00004_modify_transaction_table.sql, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
In an attempt to keep transactions relatively generic, introduce a transactio_detail jsonb column and move most things "card related" into it. Update mapping and fixtures accordingly. I have kept cardholder_name as its own column in order to ensure searching on this will continue to be performant. We cn look at making this more payment type agnostic in future.
=> PP-5255 Introduce transaction_detail column

src/test/java/uk/gov/pay/ledger/pact/TransactionsApiContractTest.java
- Removes annotation `IgnoreNoPactsToVerify` from contract tests as consumer pacts (publicapi) are now published to pact-broker and pacts are available to verify
=> PP-5257 Unignore pacts to verify

src/main/java/uk/gov/pay/ledger/event/model/EventDetailsDigest.java, src/main/java/uk/gov/pay/ledger/event/model/EventDigest.java, src/main/java/uk/gov/pay/ledger/queue/EventMessageHandler.java, src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionRow.java, src/main/java/uk/gov/pay/ledger/transaction/dao/mapper/TransactionMapper.java, src/main/java/uk/gov/pay/ledger/transaction/model/Address.java, src/main/java/uk/gov/pay/ledger/transaction/model/CardDetails.java, src/main/java/uk/gov/pay/ledger/transaction/model/Transaction.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/main/resources/migrations/00005_drop_not_null_transaction_table.sql, src/test/java/uk/gov/pay/ledger/event/service/EventServiceTest.java, src/test/java/uk/gov/pay/ledger/queue/EventMessageHandlerTest.java, src/test/java/uk/gov/pay/ledger/queue/QueueMessageReceiverIT.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoSearchIT.java
Adds the connecting logic that takes an EventDigest and creates and
inserts a transaction.
At the moment this simply inserts a transaction, so will not handle multiple
events. It also hardcodes the state of the transaction, so the mapping
logic needs writing.
In order to do this I have dropped some constraints on the transaction table.
This is because we don;t know what order we are going to recieve events,
so we may have only a minimal amount of information to create the
transaction, therefore we cannot enforce non-null constraints on things like
description, reference etc.
Another mildly controversial thing I have done is equate the event
`resourceExternalId` with the transaction externalId. I think this
is correct, as ultimately we need to be able to retrieve things from
connector and …
=> PP-5255 Insert transaction on recieving event

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/CommaDelimitedSetParameter.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java
* updated `TransactionSearchParams` and `TransactionDao` to bind the params instead of manually constructing string with values
* a bit of refactor in `TransactionDao` to remove duplicate code (probably can be done more of it)
=> PP-5359: bind params in `IN` clause

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java
* #89 - refactor binding parameters in TransactionDao to separate method for the sake of readability
* #90 - replaced `new ObjectMapper` with `Jackson.newObjectMapper` to make test simulate closer of what happens in the actual Dropwizard application
=> BAU: post PR clean-up

src/main/java/uk/gov/pay/ledger/event/model/SalientEventType.java, src/main/java/uk/gov/pay/ledger/transaction/state/TransactionState.java, src/test/java/uk/gov/pay/ledger/event/model/TransactionEntityFactoryTest.java, src/test/java/uk/gov/pay/ledger/queue/QueueMessageReceiverIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueueEventFixture.java
* Changed the SalientEventType back to have `AUTHORISATION_SUCCESSFUL` event (for the purpose of test: src/test/java/uk/gov/pay/ledger/event/model/TransactionEntityFactoryTest.java) - it might be required to rename it to something else as part of PP-5388
=> PP-5357: renamed Payment details event

Jenkinsfile, pom.xml, src/test/java/uk/gov/pay/ledger/pact/ContractTestSuite.java, src/test/java/uk/gov/pay/ledger/pact/EventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueueEventFixture.java
Example of how Ledger can generate a message pact for a particular event type. I think this can be improved, but this shows the basic idea of how to generate and verify a message pact for the `PAYMENT_CREATED` event.
At the moment the verification step checks that the event has been persisted to the database. I think this might be the right point to verify. We would then rely on the pacts and test fixtures being generated from a shared source to ensure end to end compatibility.
=> PP-5355 Example message consumer pact test

Jenkinsfile
Connector side of things is not in yet, so disbling the compatibility
check until that is sorted.
=> PP-5355 Remove pact compatibility check

src/main/resources/migrations/00011_update_payment_details_event_name.sql
* added a migration script that updates the name of the `PAYMENT_DETAILS_EVENT` to `PAYMENT_DETAILS_ENTERED`
**Notes**
Tested in pay local - is working
**BLOCKED** on release of https://github.com/alphagov/pay-connector/pull/1457
=> PP-5357: database migration for rename

Jenkinsfile
When we run contract tests against ledger on master we should publish
the results. This will mean verifications of contracts with upstream
services (in this case publicapi) will be published on ledger master
builds, which is what we want.
=> BAU Publish pact results

src/test/java/uk/gov/pay/ledger/pact/GetTransactionContractTest.java
- Removes @IgnoreNoPactsToVerify as publicapi has got pacts for states in `GetTransactionContractTest`
=> BAU - Remove @IgnoreNoPactsToVerify

src/main/resources/migrations/00014_add_fields_for_refunds.sql
- Added columns `gateway_transaction_id`, `origin_transaction_id`, `transaction_type` to support refund related endpoints
- Transaction type is currently set to nullable.
Todo:
- Update code to always populate transaction_type
- Update transactoion_type to not null
Co-authored-by: @sfount
=> PP-5457 Add columns to support refunds

src/main/resources/migrations/00014_add_fields_for_refunds.sql
- Renames `origin_transaction_id` to `parent_transcation_id`
Migrations have not been run in staging/prod, so updating sql
=> PP-5457 Rename origin_transaction_id to parent_transaction_id

src/test/java/uk/gov/pay/ledger/pact/EventQueueContractTest.java
Ledger was writing pacts with dynamically generated data - both
the event timestamp and the gateway_account_id. This means the
pact broker thinks every new build of ledger is generating a new
pact, requiring a new verification, which causes blockages in
other parts of build pipeline (even for unrelated microservices).
This commit makes all data in ledger-connector pact static.
=> BAU Staticify ledger-connector pact

src/main/java/uk/gov/pay/ledger/transaction/model/PaymentFactory.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/ConvertedTransactionDetails.java, src/test/java/uk/gov/pay/ledger/event/model/TransactionEntityFactoryTest.java
* put json properties in transaction_details only if they have value (JSON annotation)
* chaged `as<type>` to `<type>Value` to retrieve value insted of making conversions (null won't be treated as "null")
* updated tests to reflect changes in the behaviour
=> BAU: clean up transaction_details

src/main/resources/migrations/00017_rename_parent_transaction_id_in_transaction_table.sql
Rename `parent_transaction_id` to `parent_external_id` as the column is referring to `external_id` and not `id` of transaction table
=> PP-5403 Rename `parent_transaction_id`

src/main/java/uk/gov/pay/ledger/event/model/EventDigest.java, src/main/java/uk/gov/pay/ledger/event/model/EventType.java, src/main/java/uk/gov/pay/ledger/event/model/TransactionEntityFactory.java, src/main/java/uk/gov/pay/ledger/transaction/state/TransactionState.java, src/test/java/uk/gov/pay/ledger/event/model/TransactionEntityFactoryTest.java
* introduce refund event types 
* map types to external states (respecting connector maps)
* make sure transaction projection wires cross correctly
=> PP-5403 Map refund to external states

pom.xml
`org.apache.httpcomponents:httpclient` is a transitive dependency of `io.dropwizard:dropwizard-client` but is also used by AWS core.
As the transitive dependency of dropwizard-client is adding `httpclient 4.5.7`, AWS core which expects latest library (>4.5.8) started logging warning messages and adding noise to logs.
`"level":"WARN","logger":"com.amazonaws.http.apache.utils.ApacheUtils","thread":"dw-22 - GET /healthcheck","message":"NoSuchMethodError was thrown when disabling normalizeUri. This indicates you are using an old version (< 4.5.8) of Apache http client. It is recommended to use http client version >= 4.5.9 to avoid the breaking change introduced in apache client 4.5.7 and the latency in exception handling. See https://github.com/aws/aws-sdk-java/issues/1919 for more …
=> BAU - Add httpclient as direct dependency

src/test/java/uk/gov/pay/ledger/pact/EventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueueEventFixture.java
I tried to add date format verification:
* at the top level, but given you specify the name (not path) to the checked property it wasn't possible (unless there is a special way I haven't found)
* by lambda Consumer function - but it didn't seem to work
Giving up for now - can be picked up later or by somebody else.
=> PP-5460: add pact test for CaptureConfirmed event

src/main/java/uk/gov/pay/ledger/transaction/search/model/ConvertedTransactionDetails.java, src/test/java/uk/gov/pay/ledger/event/model/TransactionEntityFactoryTest.java
Refund submitted event includes `refunded_by` field in the payload which is not directly mapped to Transaction table. Updated to map `refunded_by` to `transaction_details` json blob
=> PP-5403 Process additional refund event field

src/test/java/uk/gov/pay/ledger/pact/CaptureConfirmedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/pact/ContractTestSuite.java, src/test/java/uk/gov/pay/ledger/pact/PaymentCreatedEventQueueContractTest.java
Moved PaymentCreated event pact to separate file and renamed EventQueueContractTest to CaptureConfirmedEventQueueContractTest (or the other way around)
=> PP-5469: pacts in separate files

src/main/java/uk/gov/pay/ledger/event/model/EventDigest.java, src/main/java/uk/gov/pay/ledger/event/model/SalientEventType.java, src/main/java/uk/gov/pay/ledger/event/model/TransactionEntityFactory.java, src/main/java/uk/gov/pay/ledger/transaction/state/TransactionState.java, src/test/java/uk/gov/pay/ledger/event/model/EventDigestTest.java, src/test/java/uk/gov/pay/ledger/event/model/TransactionEntityFactoryTest.java, src/test/java/uk/gov/pay/ledger/event/service/EventServiceTest.java, src/test/java/uk/gov/pay/ledger/queue/QueueMessageReceiverIT.java
* use the most recent `s/salient/state-transitioning/g` event to determine event digest state
Implicitly this sets the standard that: 
* ledger shouldn't need to know about events that don't transition state (directly map to external states)
* any number of payload events can be related to a given digest, as long as at least one event maps to an external state ledger knows about
Question: should it be enforced that registered enum `EventType` has a map to an external state in `TransactionState`
=> PP-5403 Support non state transition events

src/test/java/uk/gov/pay/ledger/event/model/EventDigestTest.java, src/test/java/uk/gov/pay/ledger/event/model/TransactionEntityFactoryTest.java, src/test/java/uk/gov/pay/ledger/pact/CaptureConfirmedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/pact/ContractTestSuite.java, src/test/java/uk/gov/pay/ledger/pact/PaymentCreatedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/pact/RefundCreatedByUserEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/pact/RefundSubmittedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/pact/RefundSucceededEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/queue/EventMessageHandlerTest.java, src/test/java/uk/gov/pay/ledger/queue/QueueMessageReceiverIT.java, src/test/java/uk/gov/pay/ledger/queue/sqs/EventQueueIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueueEventFixtureUtil.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueueRefundEventFixture.java
- add refund created by user, refund submitted and refund succeeded pact tests
- add granular checks under `PactVerification` that unique to the given event_details payload
- add queue event fixture
- small code clean up in `PaymentCreatedEventQueueContractTest`
- All 3 tests insert a payment transaction into the db. Although it is not strictly necessary to run the tests, it makes them run cleaner. Without the payment transaction the code throws an
exception down the line (`insert or update on table transaction violates foreign key constraint transaction_parent_transaction_id_fkey`)
=> PP-5391 add refund events contract tests

src/main/java/uk/gov/pay/ledger/transaction/search/model/RefundSummary.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/TransactionView.java
* added getter for "transaction_id" to deprecate "charge_id" which is overly specific and doesn't apply to refunds (at least not in the same context)
* will create follow-up PR to remove it when the changes in public api are implemented
* made RefundSummary nullable when there are no values for it
=> BAU: clean up TransactionView

src/main/java/uk/gov/pay/ledger/event/dao/EventDao.java, src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/test/java/uk/gov/pay/ledger/event/dao/EventDaoIT.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
- Added method in TransactionDao to find transactions by external_id or parent_external_id (filters by gateway_accoun_id)
- Added method in EventDao to find events based on list of external ids
- Integration tests
=> PP-5454 DAO methods for transaction events

src/main/java/uk/gov/pay/ledger/transaction/model/TransactionEvent.java, src/main/java/uk/gov/pay/ledger/transaction/model/TransactionEventResponse.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java
- Adds service method `findTransactionEvents` to search for events by external_id and gateway_account_id
- Maps transactions and events to TransactionEvent
- Removes event without a state mapping
- Gets the earliest event based on external_id, event resource type, and state
- Sorts returns by event date ascending
- Unit tests
=> PP-5454 Service method for transaction events

src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java
- Added flag `include_all_events` to request for all events. By default, duplicate events (for same payment_type & state) are removed
=> PP-5454 Added flag to include all events

src/main/java/uk/gov/pay/ledger/event/dao/EventDao.java, src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/test/java/uk/gov/pay/ledger/event/dao/EventDaoIT.java, src/test/java/uk/gov/pay/ledger/queue/QueueMessageReceiverIT.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java, src/test/java/uk/gov/pay/ledger/util/DatabaseTestHelper.java
Persist data associated with refund summary.
Persist multiple events of same type and resource_external_id if
they have different timestamps.
=> PP-5463 Fix refund summary persistence

src/main/java/uk/gov/pay/ledger/transaction/search/model/TransactionView.java
It's not used anyway at the moment.
=> BAU: remove links property from TransactionView

src/main/java/uk/gov/pay/ledger/event/model/TransactionEntityFactory.java, src/main/java/uk/gov/pay/ledger/transaction/dao/mapper/TransactionMapper.java, src/main/java/uk/gov/pay/ledger/transaction/entity/TransactionEntity.java, src/main/java/uk/gov/pay/ledger/transaction/model/TransactionFactory.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/main/java/uk/gov/pay/ledger/transaction/state/TransactionState.java, src/test/java/uk/gov/pay/ledger/event/model/TransactionEntityFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/model/TransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
Previously we were doing the following:
- Make event digest
- Calculate TransactionState from latest salient event
- Store transaction state as Transaction.getStatus()
- Get transaction status from db
- Convert to first TransactionState with matching status
This could lead to the following happening:
- Latest event is CANCEL_BY_USER_FAILED
- Therefore TransactionState is FAILED_CANCELLED
- Transaction state stored in DB as cancelled
- Transaction retrieved
- TransactionState calculated as CANCELLED
i.e. we could lose information about the real TransactionState and
therefore report the wrong state.
Now we store the actual name of the transaction state in the DB,
so we do not lose any information. I have had to adapt the search
so that now if someone searches for cancelled, we actual go and …
=> PP-5491 Correct transaction state handling

src/main/java/uk/gov/pay/ledger/transaction/model/Payment.java, src/main/java/uk/gov/pay/ledger/transaction/model/Refund.java, src/main/java/uk/gov/pay/ledger/transaction/model/Transaction.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/TransactionView.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java
in order to distinguish Payments from Refunds in search results
Quick one to have transaction_type property visible.
=> PP-5390: add transaction_type to transaction view

src/main/java/uk/gov/pay/ledger/transaction/model/TransactionFactory.java, src/test/java/uk/gov/pay/ledger/transaction/model/TransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
- `expiry_date` is currently missing from transaction view / search.
- Corrected expected JSON field and updated relevant tests
=> PP-5526 Fix card expiry_date

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/dao/mapper/TransactionMapper.java, src/main/java/uk/gov/pay/ledger/transaction/entity/TransactionEntity.java, src/main/java/uk/gov/pay/ledger/transaction/model/TransactionFactory.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/ConvertedTransactionDetails.java, src/test/java/uk/gov/pay/ledger/event/model/TransactionEntityFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java, src/test/java/uk/gov/pay/ledger/transaction/model/TransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueueEventFixtureUtil.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
I wasn't quite sure whether to go with moving external_metdata to the transaction details so I prepared two versions:
* current version PR (both commits) shows implementation for keeping external_metadata at the top level
* first commit (only) shows version which moves external_metadata to transaction_details (without changes to db yet)
=> PP-5540 external metadata

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/dao/mapper/TransactionMapper.java, src/main/java/uk/gov/pay/ledger/transaction/entity/TransactionEntity.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/RefundSummary.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java, src/test/java/uk/gov/pay/ledger/transaction/model/TransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
(Waiting on pacts given services master builds failing)
* database migration for column name change
* column name matches event structure defined by https://github.com/alphagov/pay-connector/pull/1515
* follow up PR to update payment resource model
Requires initial PR to introduce the column (through migration), followed up by a cleanup removing the extra column.
=> PP-5541 Use refunded amount column in favour of refund submitted

src/main/resources/migrations/00019_remove_transaction_refund_submitted_amount.sql
(Waiting on pacts given services master builds failing)
Depends on (forked from) https://github.com/alphagov/pay-ledger/pull/208
* column replaced in favour of `submitted` -> `refunded`
* migration succeeded, remove old column that is no longer used
=> PP-5541 Remove refund submitted column

src/main/java/uk/gov/pay/ledger/transaction/dao/mapper/TransactionMapper.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java
* in order to be able to read null value from db (instead of defaulting to the value of long primitive type)
(extended to other Long values not only `fee`)
=> PP-5527: update TransactionMapper

src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/test/java/uk/gov/pay/ledger/pact/TransactionsApiContractTest.java
- Update refund pact state to also include a refund with state 'error'
- Minor update to `findTransactionsForParentExternalId` service method to always return results in order. If not, this can cause tests to flaky
=> PP-5421 Update refund pact state

src/test/java/uk/gov/pay/ledger/pact/TransactionsApiContractTest.java
* in order to introduce transaction_type when retrieving payment from public api
=> BAU: introduce transaction type for payment pact state

src/main/java/uk/gov/pay/ledger/transaction/model/Refund.java, src/main/java/uk/gov/pay/ledger/transaction/model/TransactionFactory.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/TransactionView.java, src/test/java/uk/gov/pay/ledger/pact/TransactionsApiContractTest.java, src/test/java/uk/gov/pay/ledger/transaction/model/TransactionFactoryTest.java
- Adds `parent_transaction_id` for RefundTransaction response as `parent_external_id` is required to build `Refund for payment` link (in publicapi search refunds resource)
- Adds Pact state for Refund transactions search
- Refactored `TransactionsApiContractTest`
=> PP-5499 Includes parent_transaction_id in Refund response

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/model/TransactionSearchResponse.java, src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsValidator.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/PaginationBuilder.java, src/main/java/uk/gov/pay/ledger/transaction/service/AccountIdSupplierManager.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsValidatorTest.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java
Use the already existing AccountIdSupplierManager to manage access
to transaction search without supplying a gateway account id. This
can be used by internal tools to get cross account data.
I have tried to minimise changes to make it clear what I have done, but
I have also started to move TransactionSearchParams towards a more
flexible structure. I have not over tested the account id override mechanism
as unit tests already exist for that.
=> PP-5520 Allow overriding of gateway account id on search

src/test/java/uk/gov/pay/ledger/pact/RefundCreatedByUserEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/pact/RefundSubmittedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/pact/RefundSucceededEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueueRefundEventFixture.java
Pact detects contract changes based on a hash of the contract content.
Therefore in order for semantically identical contracts not to be considered
different we need to write static data to the contract, rather than random
uuids etc.
=> BAU Make pact data static

src/test/java/uk/gov/pay/ledger/pact/GetTransactionContractTest.java, src/test/java/uk/gov/pay/ledger/pact/TransactionEventsApiContractTest.java, src/test/java/uk/gov/pay/ledger/pact/TransactionsApiContractTest.java
- pact-js is not yet generating providerStates and thus we cannot pass params to be used on the provider side.
=> PP-5537 add hard coded values to some pact tests

src/main/java/uk/gov/pay/ledger/queue/managed/QueueMessageReceiver.java
* thread pool size is currently specified with an environment variable,
currently only one thread is executed on the pool
* execute up to the total specified number of threads on @Override
start()
Relates to https://github.com/alphagov/pay-connector/pull/1641
=> PP-5520 Use full thread pool for managed message receiver

docker-startup.sh, src/main/java/uk/gov/pay/ledger/app/LedgerApp.java, src/main/java/uk/gov/pay/ledger/healthcheck/DependentResourceWaitCommand.java
Pinch code from pay-products to add a Dropwizard command 'waitOnDependencies'
which will poll the configured database connection until it connects
successfully
Call this from docker-startup.sh so that we don't fail on startup if the
database is temporarily unavailable (e.g. during end to end test runs)
=> PP-5441 Wait for the database to be available on startup

src/main/resources/migrations/00021_index_created_date_for_order_by.sql
* looking up the latest transactions in ledger is taking ages
* _leverage_ Index Scan Backward, make them instant
This could also be done for events themselves however the number of events we will be interested in should normally be limited by the scope of the resource ID.
=> PP-5389 Index `created_date` for transactions

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java
* this query is order of magnitudes faster than using a full ID for
count
* numbers to follow
`explain analyse select count(1) from transaction where  type= 'PAYMENT';`
>  QUERY PLAN
>----------------------------------------------
> Finalize Aggregate  (cost=381830.39..381830.40 rows=1 width=8) (actual time=833.308..833.308 rows=1 loops=1)
->  Gather  (cost=381830.18..381830.39 rows=2 width=8) (actual time=832.376..833.903 rows=3 loops=1)
Workers Planned: 2
Workers Launched: 2
->  Partial Aggregate  (cost=380830.18..380830.19 rows=1 width=8) (actual time=827.315..827.316 rows=1 loops=3)
->  Parallel Index Only Scan using transaction_type_idx on transaction  (cost=0.43..374593.98 rows=2494478 width=0) (actual time=0.023..588.446 rows=1995486 loops=3)
Index Cond: (type = …
=> PP-5389 Use COUNT(1) in favour of ID

src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/test/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsTest.java
* changed null check to `isNotBlank` in `TransactionSearchParams` for:
** buildQueryParamString
** getFilterTemplates
** getQueryMap
* added unit tests to cover the changes
=> PP-5559: don't include empty parameters in query parameters or db query

src/main/resources/migrations/00023_index_transaction_lower_reference.sql
- `Reference` is used by all dependent services to search transaction (publicapi, selfservice, toolbox)
=> PP-5389 Index for transaction `reference` column

src/main/resources/migrations/00024_index_transaction_lower_cardholder_name.sql, src/test/java/uk/gov/pay/ledger/rule/PostgresTestDocker.java
- Creates Gin index to be able to search cardholder_name using partial strings.
- Creates required extension for Gin indexes in postgres used for testing
=> PP-5389 Gin index for `cardholder_name`

src/main/resources/migrations/00026_index_transaction_gateway_transaction_id.sql
- `Gateway_transaction_id` is not directly used to search payments (via selfservice/publicapi) but index on it will be useful if a service sends us queries with gateway_transaction_id as reference
=> PP-5389 Index for transation `gateway_transaction_id`

src/main/java/uk/gov/pay/ledger/app/LedgerConfig.java, src/main/java/uk/gov/pay/ledger/healthcheck/SQSHealthCheck.java, src/main/java/uk/gov/pay/ledger/queue/QueueMessage.java, src/main/java/uk/gov/pay/ledger/queue/managed/QueueMessageReceiver.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/test/java/uk/gov/pay/ledger/event/dao/EventDaoIT.java, src/test/java/uk/gov/pay/ledger/pact/CaptureConfirmedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsValidatorTest.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java
Clean up `import`s, remove unused `throws` clauses and normalise long literals.
Also, fix up a log format error in `QueueMessageReceiver`
=> Minor cleanups

src/main/java/uk/gov/pay/ledger/transaction/state/TransactionState.java
* fix map for AUTHORISATION_CANCELLED from FAILED_CANCELLED to FAILED_REJECTED (same as in connector)
https://github.com/alphagov/pay-connector/blob/master/src/main/java/uk/gov/pay/connector/charge/model/domain/ChargeStatus.java#L36
=> PP-5605: fix mapping between event type and external state

src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java
- We have Gin indexes in database on lower(fieldname) for email,reference,cardholder_name. Use lower(fieldname) to search,  so postgres can use Gin indexes.
=> PP-5637 Search transactions by lower(field)

src/main/resources/migrations/00028_multicolumn_index_transaction_gateway_account_id_and_type.sql
- Creates multicolumn index on `gateway_account_id` and `type` as  postgres doesn't use index on `gateway_account_id` sometimes.
1. Query by just gateway_account_id uses index (explain analyse select count(1) from transaction where gateway_account_id = '32';
**QUERY PLAN**
```
Finalize Aggregate  (cost=346990.06..346990.07 rows=1 width=8) (actual time=250.628..250.628 rows=1 loops=1)
->  Gather  (cost=346989.85..346990.06 rows=2 width=8) (actual time=250.537..252.330 rows=3 loops=1)
Workers Planned: 2
Workers Launched: 2
->  Partial Aggregate  (cost=345989.85..345989.86 rows=1 width=8) (actual time=248.532..248.532 rows=1 loops=3)
->  Parallel Index Only Scan using transaction_gateway_account_id_idx on transaction  (cost=0.43..343500.43 rows=995768 width=0) (actual time=0.169..190.739 …
```
=> PP-5637 Multicolumn index on gateway_account_id and type

docker-startup.sh
We only needed to augment the default Java truststore for local testing with
selfsigned certificates, but this is no longer required.
Remove support for adding custom CA certificates.
=> Remove support for custom CA certificates

src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/main/java/uk/gov/pay/ledger/transaction/state/TransactionState.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java
- Adds new query param (status_version) to search endpoint to search/return transactions with  old_status (for `status_version=1`) or new_status (when no status version specified or `status_version=2`)
- To match current Connector functionality
- Connector supports different search endpoints for selfservice and publicapi and returns old/new status based on endpoint invoked
**For Selfservice**
https://connector_url:9003/v2/api/accounts/{account_id}/charges?payment_states=timedout
Returns (state with `new status`)
```
"state":
{
"finished": true,
"code": "P0020",
"message": "Payment expired",
"status": "timedout"
},
```
**For PublicAPI**
https://connector_url/v1/api/accounts/{accountId}/charges?state=failed
Returns (state with `old status`)
```
"state": {
"finished": true,
"code": "P0020", …
```
=> PP-5637 Search transaction by status version

src/main/resources/migrations/00029_drop_index_transaction_gateway_account_id.sql
Drop index on gateway_account_id in favour of using multi column index `transaction_gateway_account_id_and_type_idx` https://github.com/alphagov/pay-ledger/blob/207945b3dcc5bee08c3482a96e48b5f0c21a254f/src/main/resources/migrations/00028_multicolumn_index_transaction_gateway_account_id_and_type.sql#L5
Postgres will use multiple column index for searches from left most column (so search using `gateway_account_id` OR `gateway_account_id & type` uses multi column index)
=> PP-5637 Drop index on gateway_account_id

src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsTest.java
Context:
Currently ledger searches based on partial reference (the `like` query).
The current behaviour of Connector though is to search by exact mathc for
public api calls and partial reference for selfservice.
In order to mimic the same behaviour in ledger the exact_reference_match query
needs to be introduced (with default false value) which will allow switching between
exact and partial match for reference.
Changes:
* add exact_reference_match to TransactionSearchParams (default true, not added to
query param string
* update getFilterTemplates and getQueryMap methods to support switching between exact
and partial mathch
* cover the changes with unit and integration tests
=> PP-5647: add exact_reference_match query param to search endpoint

src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/test/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsTest.java
We have transaction search view in selfservice microservice which allows to search for refunds by card_type, reference, email, and last_digits_card_number of corresponding payment.
Selfservice service also presents `payment` related info for refunds records.
Current search endpoint (`v1/transaction?query_params`) in ledger doesn't return payment related information for `refund` transactions.
This change is part of `adding payment transaction info  to refunds transaction / searching refunds by fields available on payment transaction` when search is from selfservice.
=> PP-5657 DAO filter to search on parent transaction

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/dao/mapper/TransactionWithParentMapper.java, src/main/java/uk/gov/pay/ledger/transaction/entity/TransactionEntity.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoSearchIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
- Search for transaction and on parent transaction too so refunds can be returned in the search
- When query parameters `reference, email_address, cardholder_name, last_four_digits_card_number, card_brand` are available,
should also search on parent transaction
- For other query parameters, apply filter only on transaction
=> PP-5657 DAO method to search on parent transaction

src/main/java/uk/gov/pay/ledger/transaction/model/Refund.java, src/main/java/uk/gov/pay/ledger/transaction/model/TransactionFactory.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/TransactionView.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/test/java/uk/gov/pay/ledger/transaction/model/TransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java
- Updates service method to search for transactions with parent when `withParentTransaction` query param is `true`.
- Refund transaction also includes parent transaction information
=> PP-5657 Search on parent transaction - service method

src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsValidator.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsValidatorTest.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java
- Validation for gateway_account_id when `with_parent_transaction` is true. This prevents querying with parent transaction without gateway_account_id
- added resource test
=> PP-5657 Resource validation for search with parent transaction

src/main/java/uk/gov/pay/ledger/transaction/model/TransactionFactory.java, src/test/java/uk/gov/pay/ledger/pact/TransactionsAndEventApiContractTest.java, src/test/java/uk/gov/pay/ledger/transaction/model/TransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
Connector responds with with the card brand human readable labels found
in Connector's database. This is now passed through the payment details
entered event and stored in the `card_brand_label` attribute of
transaction details. Send this in favour of the card brand key (which
can still be searched/ filtered as normal).
=> PP-5658 Report on card brand label to match Connector

src/main/java/uk/gov/pay/ledger/transaction/dao/mapper/TransactionMapper.java, src/main/java/uk/gov/pay/ledger/transaction/dao/mapper/TransactionWithParentMapper.java
If an unknown transaction state is stored in the database `valueOf` will
throw an exception. Use `from` String exposed on `TransactionState`
which should handle no mapping.
=> PP-5565 Handle exception if transaction data is corrupt

src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java
Add `"card_type": "DEBIT"` to the `PaymentDetailsEntered` event details test fixture because connector will now be sending something like this.
No need to update the test assertions because ledger does not yet return the card type in responses.
=> PP-5662 Add "card_type": "DEBIT" to PaymentDetailsEntered test

src/main/java/uk/gov/pay/ledger/app/LedgerModule.java, src/main/java/uk/gov/pay/ledger/report/entity/PaymentCountByStateResult.java, src/main/java/uk/gov/pay/ledger/report/params/PaymentsReportParams.java, src/main/java/uk/gov/pay/ledger/report/service/ReportService.java, src/test/java/uk/gov/pay/ledger/report/service/ReportServiceTest.java
Add service that calls the report DAO to get the counts by payment
status and from them constructs a Map which can be returned in the body
of the response for the get payment counts by status endpoint.
=> PP-5671 Add report service

pom.xml, src/main/java/uk/gov/pay/ledger/app/LedgerApp.java, src/main/java/uk/gov/pay/ledger/app/LedgerModule.java, src/main/java/uk/gov/pay/ledger/exception/JerseyViolationExceptionMapper.java, src/main/java/uk/gov/pay/ledger/report/params/PaymentsReportParams.java, src/main/java/uk/gov/pay/ledger/report/resource/ReportResource.java, src/main/java/uk/gov/pay/ledger/report/service/ReportService.java, src/test/java/uk/gov/pay/ledger/report/resource/ReportResourceIT.java, src/test/java/uk/gov/pay/ledger/report/resource/ReportResourceTest.java
Add resource with /v1/report/payments_by_state endpoint which returns
the counts of payments in each state.
Validate the query parameters using hibernate validation. Add
JerseyViolationExceptionMapper to map the exceptions thrown when
validation fails into a 422 response with a body of the expected
structure.
=> PP-5671 Add report resource

pom.xml, src/test/java/uk/gov/pay/ledger/pact/ContractTest.java, src/test/java/uk/gov/pay/ledger/pact/ContractTestSuite.java, src/test/java/uk/gov/pay/ledger/pact/PublicApiContractTest.java, src/test/java/uk/gov/pay/ledger/pact/SelfServiceContractTest.java
Currently when a consumer build is kicked off, the provider contract test will
run in its entirety. For example, in a selfservice build, the ledger provider
contract tests will run as well. However, what is run is:
publicapi->ledger
selfservice->ledger
connector->ledger
We really only want to run selfservice->ledger in this case.
This commit will allow a dynamic creation of the test suite to run based on a
CONSUMER system property. This will mean shorter run times when a provider
contract test is run as part of a specific consumer build.
=> PP-5670: Specify the consumer when running contract test

src/main/java/uk/gov/pay/ledger/report/dao/ReportDao.java, src/main/java/uk/gov/pay/ledger/report/entity/PaymentsStatisticsResult.java, src/main/java/uk/gov/pay/ledger/report/resource/ReportResource.java, src/main/java/uk/gov/pay/ledger/report/service/ReportService.java, src/test/java/uk/gov/pay/ledger/report/dao/ReportDaoIT.java, src/test/java/uk/gov/pay/ledger/report/resource/ReportResourceIT.java, src/test/java/uk/gov/pay/ledger/report/resource/ReportResourceTest.java, src/test/java/uk/gov/pay/ledger/report/service/ReportServiceTest.java
Add an endpoint in the report resource to get some overview payment statistics, optionally by gateway account and filtered by created date.
The endpoint returns the count and the gross total amount of successful payments meeting the filter parameters.
=> PP-5677 Add get payment statistics endpoint

src/test/java/uk/gov/pay/ledger/pact/PaymentNotificationCreatedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java
- temporarily disable checking for expiry_date on telephone payments created event queue test. This is needed for pact tests to be passed.
=> PP-5681 temporarily disable checking expiry_date

src/test/java/uk/gov/pay/ledger/pact/PaymentNotificationCreatedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java
- re-enable card expiry date field to be checked in pact test
- rename card_expiry_date to expiry_date
=> PP-5681 re-enable fixed msg queue test for telephone payments

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/dao/mapper/TransactionMapper.java, src/main/java/uk/gov/pay/ledger/transaction/entity/TransactionEntity.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/TransactionView.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
- insert gateway_transaction_id when creating a telephone payment
- gateway transaction id is an important part of the telephone and thus we need to store it
=> PP-5681 insert gateway_transaction_id when creating a payment type

src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java
- Currently we return 200 response and empty results, if `page number` query parameter is set to too high. To maintain functionality on par with connector/publicapi, return 404 when page number is greater than the last page number possible for query params
=> PP-5602 Return 404 for invalid page number

src/main/java/uk/gov/pay/ledger/event/dao/EventDao.java, src/main/java/uk/gov/pay/ledger/event/service/EventService.java, src/main/java/uk/gov/pay/ledger/queue/EventMessageHandler.java, src/test/java/uk/gov/pay/ledger/event/dao/EventDaoIT.java, src/test/java/uk/gov/pay/ledger/event/service/EventServiceTest.java, src/test/java/uk/gov/pay/ledger/queue/EventMessageHandlerTest.java
- When we receive a new event from the queue, sometimes that event already
exists but with less information that the newer version of the event,
currently the behaviour of ledger is to not store this information, this
commit fixes that by updating the previous record with the new event
information if there is a disparity between the two.
=> PP-5170 Store New Event Details Data

src/main/java/uk/gov/pay/ledger/event/dao/EventDao.java, src/test/java/uk/gov/pay/ledger/event/dao/EventDaoIT.java
- Currently, if an event exists in ledger, `event_details` are always updated.
- We would only want to update event, if event_details changes (this is to support events with updated `event_details` due to fixes in connector)
=> PP-5710 Update event when event details mismatch

src/main/resources/migrations/00031_index_event_date.sql
* sorting events requires a full table scan
* index date to allow scripts to be run when:
* updating legacy transaction and transaction events (used to update live events and card brand label events)
* requestsing platform level events (observability + communication)
=> PP-5659 Add btree index to `event_date` column

src/main/java/uk/gov/pay/ledger/transaction/entity/TransactionEntity.java, src/test/java/uk/gov/pay/ledger/event/model/TransactionEntityFactoryTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java
* live column not being set correctly as it is explicitly ignored by
JSON object mapper
* remove ignore and verify that it is being set correctly on entity
=> PP-5659 Remove ignore from transaction entity live column

Jenkinsfile
- We now have publicapi and selfservice using ledger in CI environment and Selfservice uses ledger in all environments
- Run E2E tests on master build and optionally run them on PR builds to catch regression
=> PP-5744 Enable E2E tests

src/test/java/uk/gov/pay/ledger/pact/PaymentCreatedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java
The https://github.com/alphagov/pay-connector/pull/1829 change
adds additional data to PaymentCreated message.
Change:
* update pact test to include additional fields in the message
=> PP-5666: add additional field validation for payment created pact test

src/main/java/uk/gov/pay/ledger/event/dao/EventDao.java, src/main/java/uk/gov/pay/ledger/event/service/EventService.java, src/main/java/uk/gov/pay/ledger/queue/EventMessageHandler.java, src/test/java/uk/gov/pay/ledger/event/dao/EventDaoIT.java, src/test/java/uk/gov/pay/ledger/event/service/EventServiceTest.java, src/test/java/uk/gov/pay/ledger/queue/EventMessageHandlerTest.java
- Event updates were allowed so backfill process could send new fields in JSON. Now that backfill is complete revert event overwrites as this is not expected behaviour of ledger.
Ledger either inserts a new event if not exists or ignores an existing event
=> PP-5779 Revert "PP-5710 Update event"

src/test/java/uk/gov/pay/ledger/pact/ContractTest.java
- pact's javascript framework does not support params thus we need to hard code them
=> PP-5770 add params checking for pact tests

src/test/java/uk/gov/pay/ledger/pact/ContractTest.java
- add created date to createThreeTransactionsForSelfserviceSearch. It's going to be used for to and from date searches
=> PP-5770 add created date to selfservice search pact test

src/test/java/uk/gov/pay/ledger/pact/ContractTest.java
- add a new state that has a payment with all fields and a corresponding refund with parent transaction
=> PP-5770 add new state to contract tests to include all fields

pom.xml, src/main/java/uk/gov/pay/ledger/app/LedgerApp.java
- The new version of pay-java-commons introduces breaking changes
regarding the import path for LoggingFilter, this PR fixes them.
=> BAU Update Pay Java Commons

pom.xml
Reverts alphagov/pay-ledger#429
Ledger build has been failing - reverting this commit.
=> Revert "Bump mockito-core from 3.1.0 to 3.2.0"

src/main/java/uk/gov/pay/ledger/app/LedgerApp.java, src/main/java/uk/gov/pay/ledger/filters/LoggingMDCRequestFilter.java, src/main/java/uk/gov/pay/ledger/filters/LoggingMDCResponseFilter.java
Description:
- At the moment this doesn't compile as Pay Java Commons doesn't have the static members PARENT_EXTERNAL_ID and TRANSACTION_EXTERNAL_ID
- Adds eventId, parent_external_id and transactionExternalId to MDC
=> PP-5893-Add-MDC-Logging-Filter

src/test/java/uk/gov/pay/ledger/pact/PaymentDetailsEnteredEventQueueContractTest.java
The gateway account id is by default random
(https://github.com/alphagov/pay-ledger/blob/master/src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java#L23)
which causes the published pact to be different each time. This isn't ideal as
the pact hasn't really changed and it affects deploys of ledger because a
connector build has to be run to verify the changed pact.
=> bau: use fixed gateway account id

src/main/java/uk/gov/pay/ledger/filters/LoggingMDCResponseFilter.java
We shouldn't use MDC.clear as LoggingMDCResponseFilter happens before the
LoggingFilter
(https://github.com/alphagov/pay-java-commons/blob/master/logging/src/main/java/uk/gov/pay/logging/LoggingFilter.java)
is called. This would remove the x_request_id needed in the LoggingFilter.
=> PP-5893: Manually clear keys

src/main/java/uk/gov/pay/ledger/queue/EventMessageHandler.java, src/test/java/uk/gov/pay/ledger/queue/EventMessageHandlerTest.java
We currently have no visibility on the lag time for when an event gets emitted
and when it is processed by ledger. This makes it difficult for us to deal with
the query relating to this zendesk ticket about certain transactions not
appearing in calls to `/v1/payments?state=success&from_date={fromdate}` for
example.
This metric would also be useful as we currently have no guarantees as to the performance of events appearing in ledger, except that data between connector and ledger is eventually consistent. Getting data will enable us to do some thinking around this, as some services use `/v1/payments` to get data to be input into their financial systems.
=> ZD3867367: Include ingest lag on event log lines

src/main/java/uk/gov/pay/ledger/transaction/model/Refund.java, src/main/java/uk/gov/pay/ledger/transaction/model/TransactionFactory.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/TransactionView.java, src/test/java/uk/gov/pay/ledger/transaction/model/TransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
- Ledger now receives `user_email` for refund transactions which is stored in `transaction_details` DB column.
- This change returns user_email as `refunded_by_user_email` in refund transaction endpoint and to be used by CSV endpoint
=> PP-5967 Add user_email to refund view

pom.xml, src/main/java/uk/gov/pay/ledger/app/LedgerApp.java, src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/main/java/uk/gov/pay/ledger/util/csv/CSVMessageBodyWriter.java, src/main/java/uk/gov/pay/ledger/util/csv/FlatCsvTransaction.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java
* add jackson csv parser dependency
* jersey `MessageBodyWriter` for `text/csv`, map generic (flat!) list to CSV
* map `TransactionView` to flat record that matches our current admin tool CSV columns
* integration test for `text/csv` content type
Supersedes https://github.com/alphagov/pay-ledger/pull/439
=> PP-5970 Transaction search resource accepts CSV

pom.xml, src/main/java/uk/gov/pay/ledger/util/csv/FlatCsvTransaction.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java
- Added a new test library to parse CSV data
- Added assertions for CSV headers and data (includes standard columns). Metadata/Stripe specific columns to be added once Ledger is able to generate CSV with these headers
=> PP-5970 Assertions for CSV data

src/main/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactory.java, src/test/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactoryTest.java
Prep to use `Map` for CSV data instead of POJO.
- Added new class `CsvTransactionFactory` to process DB transactions and convert the same to Map (CSV field name, value) for CSV endpooint. Currently we create plain object with annotations.
- Also derives headers (including metadata & Stripe specific ) for CSV as Map
- Uses `LinkedHashMap` for CSV header to keep the column ordering when generating CSV response
=> PP-5970 Added `CsvTransactionFactory`

src/main/java/uk/gov/pay/ledger/event/dao/EventDao.java, src/main/java/uk/gov/pay/ledger/event/dao/mapper/EventTickerMapper.java, src/main/java/uk/gov/pay/ledger/event/model/EventTicker.java, src/main/java/uk/gov/pay/ledger/event/resource/EventResource.java, src/test/java/uk/gov/pay/ledger/event/dao/EventDaoIT.java, src/test/java/uk/gov/pay/ledger/event/resource/EventResourceIT.java
"Administrative" list all events endpoint - used to drive a payment events ticker.
This will fetch events within a specified timeframe selecting only for `live` transactions. 
Future improvements: 
* Allow selecting by individual gateway accounts 
* Limit the consumer from selecting a large number of events (or a long timespan) 
These events can then be formatted and displayed as payments are processed (rough draft):
=> PP-5991 Events ticker for dashboard

src/main/java/uk/gov/pay/ledger/report/dao/ReportDao.java, src/main/java/uk/gov/pay/ledger/report/entity/TimeseriesReportSlice.java, src/main/java/uk/gov/pay/ledger/report/mapper/ReportMapper.java, src/main/java/uk/gov/pay/ledger/report/resource/ReportResource.java, src/main/java/uk/gov/pay/ledger/report/service/ReportService.java, src/test/java/uk/gov/pay/ledger/report/dao/ReportDaoIT.java, src/test/java/uk/gov/pay/ledger/report/resource/ReportResourceIT.java
Transaction volumes grouped by hour will be used to show payment trends for a single day or comparing multiple days. Transaction volume data is grouped using the `created_date` field.
This end point requires from and to date to be specified - it should potentially limit the consumer to requesting within a one day period for performance reasons.
Future improvements: 
* optionally select data by gateway account or provide the override flag
* limit the consumer from doing huge massive queries
This will then be presented in a graph (rough draft)
=> PP-5991 Timeseries transaction volumes by hour

src/main/java/uk/gov/pay/ledger/event/dao/EventDao.java, src/main/java/uk/gov/pay/ledger/event/dao/mapper/EventTickerMapper.java, src/main/java/uk/gov/pay/ledger/event/model/EventTicker.java, src/test/java/uk/gov/pay/ledger/event/dao/EventDaoIT.java
The event ticker query returns a superset of what is actually sent through the entity, add remaining attributes.
=> PP-5991 Reflect all event ticker query attributes in entity

src/main/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactory.java, src/test/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
- For CSV data and especially for refunds, we need to get payment specific details (payment details, card details and so on) from Payment transaction. This change maps payment attributes to refund record.
- Also for refunds amount is represented in negatives
- Additional tests for refund mapping and CSV data
- Refactored resource test to get CSV fields by header name to make it more readable.
Fixes
- Fixed wallet mapped which is stored as JSON field `wallet` and is returned as titleCase in CSV
- Fixed card_type value - update to return lowercase value
- Fixed total_amount & net_amount as calculated in selfservice
=> PP-5970 CSV endpoint - Refund data mapping

src/main/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactory.java, src/main/java/uk/gov/pay/ledger/transaction/state/PaymentState.java, src/main/java/uk/gov/pay/ledger/transaction/state/RefundState.java, src/test/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java
- Currently selfservice derives user friendly name for payment & refunds states for CSV. Introduced the same for ledger CSV data
=> PP-5970 CSV data - displayName for TransactionState

src/main/java/uk/gov/pay/ledger/event/dao/EventDao.java, src/main/java/uk/gov/pay/ledger/event/resource/EventResource.java, src/test/java/uk/gov/pay/ledger/event/dao/EventDaoIT.java, src/test/java/uk/gov/pay/ledger/event/resource/EventResourceIT.java
Request for unbound data isn't reliable enough including request latency. Add upper bound `to_date` for increased precision.
=> PP-5991 Event ticker include "to_date" for precision

src/main/java/uk/gov/pay/ledger/report/dao/PerformanceReportDao.java, src/main/java/uk/gov/pay/ledger/report/dao/ReportDao.java, src/main/java/uk/gov/pay/ledger/report/entity/GatewayAccountMonthlyPerformanceReportEntity.java, src/main/java/uk/gov/pay/ledger/report/mapper/GatewayAccountMonthlyPerformanceReportEntityMapper.java, src/main/java/uk/gov/pay/ledger/report/resource/PerformanceReportResource.java, src/test/java/uk/gov/pay/ledger/report/dao/PerformanceReportDaoIT.java, src/test/java/uk/gov/pay/ledger/report/resource/PerformanceReportResourceIT.java
Description:
- Queries the Transaction database instead of Connector returns gateway_account_id,  average amount, total amount and total volume per gateway account given a start and end date
- PerformanceReportDAO is  called directly in the controller.
This is similar to [https://github.com/alphagov/pay-ledger/pull/493/files](#493 ) and could possibly be included in this endpoint but for the time being I have made it separate.
=> PP-5993 - DAO Monthly live gateway performance statistics

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/test/java/uk/gov/pay/ledger/pact/CaptureSubmittedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/pact/PaymentCreatedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
Why?
We're passing the gatewayAccountId from resource to the method, but we're actually not using
it at all.
Changes:
* update DAO method to use gatewayAccountId when retrieving transactions
* update getTransactions method in TransactionService to pass gatewayAccount id to DAO method
* new unit test
* update to relevant tests
=> [BAU] update getTransactions method to use gatewayAccountId

src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceTest.java
Why?
The @NotEmpty constraint from hibernate-validator has been deprecated.
Recommendation was to use the standard constraint.
Changes:
* replace the import (hibernate.validator -> javax.validation)
* update the test assertion
=> [BAU] update deprecated constraint

src/main/java/uk/gov/pay/ledger/event/model/ResourceType.java, src/main/java/uk/gov/pay/ledger/exception/JerseyViolationExceptionMapper.java, src/main/java/uk/gov/pay/ledger/filters/LoggingMDCRequestFilter.java, src/main/java/uk/gov/pay/ledger/filters/LoggingMDCResponseFilter.java, src/main/java/uk/gov/pay/ledger/healthcheck/SQSHealthCheck.java, src/main/java/uk/gov/pay/ledger/report/dao/PerformanceReportDao.java, src/main/java/uk/gov/pay/ledger/report/dao/ReportDao.java, src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/CommaDelimitedSetParameter.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/SettlementSummary.java, src/main/java/uk/gov/pay/ledger/util/JsonParser.java, src/main/java/uk/gov/pay/ledger/util/csv/CSVMessageBodyWriter.java, src/test/java/uk/gov/pay/ledger/event/dao/EventDaoIT.java, src/test/java/uk/gov/pay/ledger/event/model/TransactionEntityFactoryTest.java, src/test/java/uk/gov/pay/ledger/event/resource/EventResourceIT.java, src/test/java/uk/gov/pay/ledger/pact/CaptureConfirmedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/pact/CaptureSubmittedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/pact/PaymentCreatedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/pact/PaymentDetailsEnteredEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/pact/PaymentNotificationCreatedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/pact/RefundCreatedByUserEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/report/dao/PerformanceReportDaoIT.java, src/test/java/uk/gov/pay/ledger/util/DatabaseTestHelper.java, src/test/java/uk/gov/pay/ledger/util/fixture/EventFixture.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueueEventFixtureUtil.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
Changes:
* replace deprecated ResultIterable.findOnly with ResultIterable.one
* replace deprecated instantiating of JsonParser and parse method with static
JsonParser.parseString
* remove unnecessary semicolon
* updated healthcheck code in functional style
* inverse the isEmpty method (it's always being used with negation - should
improve readability)
* remove redundant 'throws' clause
* simplify stream API call chain (PerformanceReportDaoIT)
* replace lambda with method reference
* remove redundant 'toString' call
=> [BAU] Fix some style issues

src/main/java/uk/gov/pay/ledger/report/resource/PerformanceReportResource.java, src/test/java/uk/gov/pay/ledger/report/resource/PerformanceReportResourceIT.java
Description:
- This ensures that a validation error is thrown if the from_date is later than the to_date for the provided query params.
=> PP-5993-Add-date-validation-to-route

src/main/resources/migrations/00032_add_source_to_transaction_table.sql
- Adds the source column, which is an enum of all possible supported
values, to the transaction table
Co-authored-by: Alex Bishop <alexbishop1@users.noreply.github.com>
=> PP-6013 Add Source Column To Transaction Table

pom.xml, src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/dao/mapper/TransactionMapper.java, src/main/java/uk/gov/pay/ledger/transaction/entity/TransactionEntity.java, src/test/java/uk/gov/pay/ledger/event/model/TransactionEntityFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
- When a TransactionEntity is serialised to the database, the source
value is stored in the source column within the transaction column
- When a TransactionEntity is deserialised from the the TransactionDao
reading the database, the source column's value is correctly read
- Tests are updated, TransactionDaoIT and TransactionEntityFactoryTest
to ensure this behaviour is as expected
=> PP-6013 Store Source in Transaction Column

Dockerfile
WHAT YOU DID
Updated the the root CA certificate in the container build in preparation for updating the certs installed on the RDS instances.
The combined cert bundle URL does not need to be updated as the URL has not changed, but the updated bundle will be downloaded at build time.
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html
How to test
Rebuild containers and deploy to test environment
Ensure app works with NEW CA root cert but OLD RDS certs. The new ca certs must be backward compatible.
Schedule the cert update on the RDS instance.
See similar PR for connector
https://github.com/alphagov/pay-connector/pull/2026
=> PP-5920 update RDS CA Cert to 2019

src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java
- When the Source enum is modified, the test will ensure that there is
parity between the different values and those that exist for the DB
type.
=> PP-6013 Ensure Enum Modifications Exist In DB

src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java
Description:
- Moves SearchPaymentsIT.shouldNotFundAnyChargeByANonExistingReference from publicapi pay-endtoend into publicapi and ledger
- Related [PR](https://github.com/alphagov/pay-publicapi/pull/833) which covers the test in publicapi
=> PP-6008 Add TransactionResourceIT for not finding transaction by reference

src/main/resources/migrations/00033_create_table_metadata_key.sql, src/main/resources/migrations/00034_create_table_transaction_metadata.sql
- Creates new tables `metadata_key`, `transaction_metadata` to store to external metadata keys for transactions.
- metadata `key` is set to `50` characters long, which is over the limit `30` we allow services
=> PP-6059 Create metadata tables

src/main/resources/migrations/00035_table_transaction_external_metadata.sql
- Creates partial index on transaction_details for existence of external_metadata so this can be used to filter our transactions metadata and to derive metadata keys
=> PP-6059 Partial index on transaction_details (external_metadata)

src/main/resources/migrations/00036_index_metadata_key.sql
- Added index on `key` column of metadata_key as the table is queried often for existence of key when processing transactions
=> PP-6059 Add index on metadata_key

src/main/resources/migrations/00033_compound_index_transaction_id_created_date.sql
In order to use keyset pagination through transactions on asynchronous
(CSV) downloads, add compound index across both id and transaction
created_date.
This allows ordering by created_date and then id, providing a guaranteed
unique and consistent page without overlapping entities. Created date on
its own could is likely to contain duplicates and we cannot gaurantee
the order of transaction ids as events are eventually consistent.
=> PP-6058 Index id, created_date on transaction table

src/main/resources/migrations/00037_add_moto_to_payment_transactions.sql
There is currently no plan to allow a service to search for MOTO payments
however it's better to technically allow this (we can envisage a service
wanting to search its MOTO payments in the future) by adding a column rather
than leaving it in the transaction_details column where it would be stored in a json
blob and then converting it to its own column later.
=> PP-6078: Add moto to transaction table

src/main/java/uk/gov/pay/ledger/app/LedgerModule.java, src/main/java/uk/gov/pay/ledger/transactionmetadata/dao/TransactionMetadataDao.java, src/test/java/uk/gov/pay/ledger/transactionmetadata/dao/TransactionMetadataDaoIT.java
- Added new method `findMetadataKeysForTransactions` to derive metadata keys from new tables (transaction_metadata and metadata_key) for given search parameters
- Changed `TransactionMetadataDao` to a class to add concrete method
- Relevant test
=> PP-6061 Add findMetadataKeysForTransactions DAO method

src/main/resources/migrations/00038_index_transaction_metadata_foreign_keys.sql
- Added index on transaction_id and metadata_key_id columns to avoid sequential scan on entire table when joined with transaction and metadata_key tables
=> PP-6061 Add index for transaction_metadata foreign keys

src/main/java/uk/gov/pay/ledger/app/LedgerConfig.java, src/main/java/uk/gov/pay/ledger/app/config/ReportingConfig.java, src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java, src/main/resources/config/config.yaml, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceTest.java, src/test/resources/config/test-config.yaml
Accept `REPORTING_MAX_CSV_ROWS_SIZE` for streaming configuration; defaults to 100,000.
=> PP-6070 Reporting config for max csv size

src/main/java/uk/gov/pay/ledger/transaction/model/Payment.java, src/main/java/uk/gov/pay/ledger/transaction/model/TransactionFactory.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/TransactionView.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java
- When we respond with a `TransactionView`, in response to both GET
single payment requests and GET search requests, in which case a
`List<TransactionView>` is returned, we want to include the `source` and
`live` parameters.
- Add tests to ensure that this is the case for payments.
=> PP-6125 Return `source` and `live` in Response

src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceTest.java
There are two methods within `TransactionResource` named `search` and
`streamCsv`. Both use the path `/` and http method `GET` but provide
either "application/json" or "text/csv" respectively.
According to the jax-rs specification when the client does not specify
the "accept" header then it is not garanteed as to which method will be
invoked, since both methods have the same level of specificity in what
they provide.
When
`shouldReturn400IfTransactionGatewayAccountIdIsNotProvidedForSearch`
runs locally and on Jenkins the `search` method is invoked as expected,
however on Travis `streamCsv` is called and an NPE is thrown as the test
provides a mock config with null parameters.
This shouldn't be a concern in production since the client of this
service is publicApi which provides an accept …
=> PP-6085 Add accept header to test

src/main/resources/config/config.yaml
When running on CloudFoundry via `cf run-task`, no PORT env var is supplied since no http route is served in this context. The app config throws an error without a default value.
=> PP-6085: Add default application port (8080)

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/dao/mapper/TransactionWithParentMapper.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoSearchIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
Include the moto flag on a transaction in the results for transaction searches so that it can be included in CSVs
=> PP-6076 Return moto flag in transaction searches

src/main/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactory.java, src/test/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactoryTest.java
For refund line items in the CSV, use whether the parent payment is moto
or not to populate the "MOTO" column for refunds.
=> PP-6076 Use "moto" value of payment for refunds in CSV

src/main/resources/migrations/00039_drop_default_for_transaction_moto_column.sql
Drop the default value, as the ledger convention is that columns do not have a value until connector sends an event containing the data to populate it.
=> PP-6076 Drop default for moto column

src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceTest.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java
- Added new endpoint (`v1/transaction/gateway-transaction/{gatewayTransactionId}`) to find
a transaction by gateway_transaction_id (payment provider reference) and payment provider.
This is needed to handle refund notifications (which need charge details to send confirmation
email and also gateway_account info) in connector for expunged charges
- Relevant tests
=> PP-6184 Add new endpoint for get transaction by gateway_transaction_id

src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsValidator.java, src/main/java/uk/gov/pay/ledger/transaction/service/AccountIdListSupplierManager.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsTest.java, src/test/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsValidatorTest.java, src/test/java/uk/gov/pay/ledger/transaction/service/AccountIdSupplierManagerTest.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java, src/test/java/uk/gov/pay/ledger/transactionmetadata/dao/TransactionMetadataDaoIT.java
- Ledger now allows users to supply comma separated lists of account IDs
via the `account_id` parameter, this will then return payments for all
of the gateway accounts specified.
- Adds tests to test the functionality works as expected.
=> PP-6163 Search For Multiple Gateway Accounts

src/test/java/uk/gov/pay/ledger/queue/QueueMessageReceiverIT.java
Description:
- Test is flaky because there wasn't enough time for the event to be captured by the queue handlers
=> PP-6201 - Fix shouldHandleForceCaptureEvent failing test

src/main/java/uk/gov/pay/ledger/queue/EventMessageHandler.java
Currently, we catch all exceptions thrown processing events and log a
line including the exception message.
However, sometimes the message is null which makes it hard to diagnose
what has gone wrong. Send an event to Sentry to capture the stack trace
when this happens.
=> PP-6201 Capture sentry event when event processing fails

src/main/resources/migrations/00040_create_table_payouts.sql
- Create a table `payouts` to store Stripe payout events and include
rollback provisions.
=> PP-6260 Create Table Payouts

src/main/resources/migrations/00041_alter_index_on_payouts_gateway_id.sql
- The index on the payouts table needs to be a unique constraint, this
drops the previous one and adds a new index that the unique constraint
can then be placed against
=> PP-6262 Alter Index Migrations

src/main/java/uk/gov/pay/ledger/payout/dao/PayoutDao.java, src/main/java/uk/gov/pay/ledger/payout/dao/mapper/PayoutMapper.java, src/main/java/uk/gov/pay/ledger/payout/entity/PayoutEntity.java, src/test/java/uk/gov/pay/ledger/payout/dao/PayoutDaoIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/PayoutFixture.java
- Creates the PayoutEntity, PayoutDao and PayoutFixture to allow for the
representation of the `payouts` database table in Java objects.
- Adds tests to ensure the DAO methods we have chosed to start with work
as expected.
=> PP-6262 Create Payouts Dao/Entity

src/main/resources/migrations/00043_extend_payouts_gateway_payout_id_column.sql
- Extend the length of the VARCHAR `gateway_payout_id` column on the
payouts table to reflect the real length of Stripe `payout_id` column.
=> PP-6261 Extend Length of `gateway_payout_id`

src/main/resources/migrations/00044_add_payouts_foreign_key_to_transaction.sql
- The `transaction` table now has a foreign key relationship to the
`payouts` table via the `gateway_payout_id`.
=> PP-6261 Transaction Table References Payouts

src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsTest.java
- This PR adds the ability for ledger to receive a new query pameter
(`live`) on transaction searches, this will return transactions on live
accounts if it is set to `true` and on test accounts if it is set to
`false`.
- Adds a test to ensure that the functionality works as expected on all
levels of Ledger.
=> BAU Add Live Parameter To Search Resource

Jenkinsfile, pom.xml, src/test/java/uk/gov/pay/ledger/pact/ConsumerContractTestSuite.java, src/test/java/uk/gov/pay/ledger/pact/ProviderContractTestSuite.java
Ledger is the only Pay microservice that is both a consumer (of connector) and a provider (to publicapi and selfservice). This led to a weird bug in the Ledger pact tests. In order to run a pact test you need to specify the `CONSUMER_TAG`. When you run a consumer pact test, this is used to tag the pact that the test produces. When you run a provider test, it specifies the tag to use when retrieving pacts from a consumer to be validated. The pact tests were run against Ledger with the command
```
mvn clean package pact:publish -DrunContractTests=true -DPACT_CONSUMER_TAG=${branchName} …
```
This command ran both the set of tests where Ledger is a provider and those where Ledger is a consumer. For the provider tests it fetched the pacts from the consumer tagged with the value of …
=> PP-6310 Fix pact bug

src/main/resources/migrations/00046_add_event_count_payout_details_to_payout.sql
- Added event_count so we upsert payouts only when there are new payout events
- Also added payout_details to store entire payout payload in json blob and table level fields only need to hold searchable/aggregate fields
=> PP-6421 Add event_count and payout_details to payout

src/main/java/uk/gov/pay/ledger/payout/dao/PayoutDao.java, src/main/resources/migrations/00047_rename_payouts_table.sql, src/test/java/uk/gov/pay/ledger/util/fixture/PayoutFixture.java
- Renames `payouts` to `payout` (singular) to be consistent with naming convention (transaction, event) in ledger
=> PP-6421 Rename payouts table

src/main/java/uk/gov/pay/ledger/payout/entity/PayoutEntity.java, src/main/java/uk/gov/pay/ledger/payout/model/PayoutEntityFactory.java, src/main/java/uk/gov/pay/ledger/payout/service/PayoutService.java, src/test/java/uk/gov/pay/ledger/payout/model/PayoutEntityFactoryTest.java
* add `PayoutEntityFactory` to parse payouts from event digests
* simple service method to combine the factory and writing to the DB
Note the object mapper used to convert the event digest payload has to register the java time module (`this.objectMapper.registerModule(new JavaTimeModule())`) otherwise it isn't able to serialise `ZonedDateTime`.
---
What this PR does not do:
* setting state based on PayoutState and known salient events (1 PR)
* setting the event count on the payout to ensure latest event is applied (depends on https://github.com/alphagov/pay-ledger/pull/715)
* setting the payout details to contain anything not at the column level (depends on https://github.com/alphagov/pay-ledger/pull/715)
* handling events at the top level based on resource type (1 PR)
=> PP-6421 Payout entity factory

src/main/java/uk/gov/pay/ledger/payout/dao/PayoutDao.java, src/main/java/uk/gov/pay/ledger/payout/entity/PayoutEntity.java, src/main/java/uk/gov/pay/ledger/payout/model/PayoutEntityFactory.java, src/test/java/uk/gov/pay/ledger/payout/dao/PayoutDaoIT.java, src/test/java/uk/gov/pay/ledger/payout/model/PayoutEntityFactoryTest.java
- Sets event_count and payout_details when processing event digest for payouts
- Also updated DAO so we only update payouts when there a new event for payout
with @sandorarpa
=> PP-6421 Set event_count & payout_details on PayoutEntity

src/main/java/uk/gov/pay/ledger/payout/dao/PayoutDao.java, src/test/java/uk/gov/pay/ledger/payout/dao/PayoutDaoIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/PayoutFixture.java
- Sets payout `created_date` derived from event digest instead of defaulting to DB date `now`.
- Cleaned up some static imports, brittle test, PayoutDao
=> PP-6469 Set Payout created_date from event digest

src/test/java/uk/gov/pay/ledger/pact/ConsumerContractTestSuite.java, src/test/java/uk/gov/pay/ledger/pact/PayoutCreatedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueueEventFixtureUtil.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePayoutEventFixture.java
- Added consumer pact test for PayoutCreated event received from connector (provider)
- Fixes ZonedDateTime format when generating pact as json body, as toString() can give varying output based on input. That is, for date time `2020-05-13T18:45:00.000000Z`, toString() returns `2020-05-13T18:45` instead of full date time as string which breaks https://github.com/alphagov/pay-ledger/blob/f76e13cdf4f369e298f71a80f148355d5d4d6bf5/src/main/java/uk/gov/pay/ledger/event/model/serializer/MicrosecondPrecisionDateTimeSerializer.java#L35
=> PP-6469 Pact test for PayoutCreated event

src/main/resources/migrations/00052_drop_payout_foriegn_key_from_transaction.sql
- Drop foreign key to payout from transaction, as events can arrive in Ledger in any order, and transaction related events shouldn't break due to payout record not being available yet.
=> PP-6469 Drop foreign key to payout

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/dao/mapper/TransactionMapper.java, src/main/java/uk/gov/pay/ledger/transaction/dao/mapper/TransactionWithParentMapper.java, src/main/java/uk/gov/pay/ledger/transaction/entity/TransactionEntity.java, src/main/java/uk/gov/pay/ledger/transaction/model/Payment.java, src/main/java/uk/gov/pay/ledger/transaction/model/Refund.java, src/main/java/uk/gov/pay/ledger/transaction/model/Transaction.java, src/main/java/uk/gov/pay/ledger/transaction/model/TransactionFactory.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/TransactionView.java, src/test/java/uk/gov/pay/ledger/event/model/TransactionEntityFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
Add gateway_payout_id column to TransactionEntity and persist it as a
top-level field.
Return gateway_payout_id as field on transactions returned by the get
transactions API endpoints.
=> PP-6472 Persist and return gateway_payout_id on transaction

src/main/java/uk/gov/pay/ledger/common/search/SearchParams.java, src/main/java/uk/gov/pay/ledger/payout/model/PayoutSearchResponse.java, src/main/java/uk/gov/pay/ledger/payout/model/PayoutView.java, src/main/java/uk/gov/pay/ledger/payout/search/PayoutSearchParams.java, src/main/java/uk/gov/pay/ledger/payout/service/PayoutService.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/main/java/uk/gov/pay/ledger/util/pagination/PaginationBuilder.java, src/main/java/uk/gov/pay/ledger/util/pagination/PaginationLink.java, src/test/java/uk/gov/pay/ledger/payout/dao/PayoutDaoSearchIT.java, src/test/java/uk/gov/pay/ledger/payout/service/PayoutServiceTest.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/PayoutFixture.java, src/test/java/uk/gov/pay/ledger/util/pagination/PaginationBuilderTest.java
- add search by PayoutSearchParams to PayoutService
- add an abstract SearchParams class to be used for pagination
- refactor PaginationBuilder to use SearchParams
- move PaginationBuilder to util.pagination
- refactor TransactionSearchParams and PayoutSearchParams to extend
SearchParams
- add PayoutSearchResponse and PayoutView classes
- add/update/refactor relevant tests
=> PP-6502 add search to payout service

src/test/java/uk/gov/pay/ledger/pact/ConsumerContractTestSuite.java, src/test/java/uk/gov/pay/ledger/pact/PaymentIncludedInPayoutEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/pact/RefundIncludedInPayoutEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueueRefundEventFixture.java
Add consumer pact tests for PAYMENT_INCLUDED_IN_PAYOUT and REFUND_INCLUDED_IN_PAYOUT events from connector
=> PP-6472 Add pact tests for transaction included in payout messages

src/main/resources/migrations/00053_payout_drop_not_null_constraint_on_amount.sql
- Drops not null constraint on `payout.amount` column so ledger can process out of order payout events.
`amount` is only available for PAYOUT_CREATED event.
=> PP-6486 Drop not null constraint on payout.amount

src/test/java/uk/gov/pay/ledger/pact/PayoutFailedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/pact/PayoutPaidEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/pact/PayoutUpdatedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePayoutEventFixture.java
- Added pact tests for rest of the payout events (failed, updated, paid) from connector
=> PP-6486 Pact tests for payout events

src/main/java/uk/gov/pay/ledger/payout/resource/PayoutResource.java, src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java, src/main/java/uk/gov/pay/ledger/transaction/service/AccountIdListSupplierManager.java, src/test/java/uk/gov/pay/ledger/transaction/service/AccountIdSupplierManagerTest.java
- refactor AccountIdListSupplierManager to take a field name when validating gateway account id. This is needed as a workaround for the naming discrepancy between transaction (account_id) and payout (gateway account id)
=> PP-6502 refactor AccountIdListSupplierManager

src/main/java/uk/gov/pay/ledger/transaction/dao/mapper/TransactionWithParentMapper.java
- At the moment, parent transaction entity is being mapped on to refund parent transaction even parent_external_id is null. As a result, checks for  `TransactionEntity.getParentTransactionEntity() !=null` will always be true and this causes
NullPointerException when parts of code does additional operations on parentTransaction attributes.
=> PP-6586 Build parent transaction only when parent is available

src/main/java/uk/gov/pay/ledger/event/model/EventDigest.java, src/test/java/uk/gov/pay/ledger/event/model/EventDigestTest.java
- Derived parent_external_id if any one event in the given list has parent_external_id set
This allows to send events without parent_external_id as in the case of refunds where payout
notifications are received from Stripe and connector can send refund related events without looking further into refunds table.
- This also protects against processing new events in future without parent_external_id
=> PP-6585 Calculate parent_external_id from events

src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsValidator.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceCsvIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceTest.java, src/test/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsValidatorTest.java
- Added validation on TransactionResource for CSV endpoint inline with transactions search endpoint.
At present, CSV endpoint could cause NPE or date format exceptions if query params are invalid or not available.
- gateway_account_ids are mandatory for CSV download as there is no use case to search transactions for csv without associated accounts. As a result `override_account_id_restriction` query param has been removed which is unused and not needed.
- Added relevant tests
- Also added ITest to get transactions as CSV for payouts
=> PP-6503 Improve validation for transaction CSV endpoint

src/test/resources/testcontainers.properties
ryuk container used by testcontainers library is responsible for starting and cleaning up postgres/sqs containers used during the tests.
By default images is pulled from quay.io.
Added configuration to use dockerhub instead as for all other images. Image is still an official test containers ryuk image https://hub.docker.com/r/testcontainersofficial/ryuk
Custom images can be configured in multiple ways as per https://www.testcontainers.org/features/configuration/
=> BAU - Use dockerhub for ryuk image

src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java
Everything is correctly in place to filter on `gateway_transaction_id`
but as there is no `QueryParam` annotation on the attribute this will
never be set by the resource. 
Add this so it can be parsed and set appropriately.
=> BAU Fix gateway transaction id transaction search filter

src/test/java/uk/gov/pay/ledger/pact/PublicApiContractTest.java, src/test/java/uk/gov/pay/ledger/pact/SelfServiceContractTest.java
We are using a different pact broker for ci running on concourse so
make the pact broker url configurable from an env var `PACT_BROKER_URL`.
Default value is the existing broker used for Jenkins CI.
See https://github.com/alphagov/pay-connector/pull/2376 for similar implementation for Connector
=> PP-6445 Use env var for Pact broker url

src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java
In the case where the client does not specify Accepts header,
we want ledger to respond with `application/json`. At the moment
the response type will be indeterminate if no Accepts header is
set and is determined by version of JDK.
Use qs factor to explicitly indicate that `application/json`
should be the preferred content type.
See http://www.apacheweek.com/features/negotiation
=> PP-6504 Explicitly set priority of content type

manifest.yml, src/main/resources/env-map.yml
According to the README these aren't needed unless you're running locally using a fake SQS queue. Apps won't start without "endpoint" if "non-standard" SQS is enabled which isn't a thing in "real" SQS.
=> PP-6234: Remove dev SQS config options from PaaS environment variables

src/test/java/uk/gov/pay/ledger/pact/RefundSucceededEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueueRefundEventFixture.java
- Added new field `gateway_transaction_id` expected for RefundSucceeded pact
- Removed `reference` from expected pact payload as connector is going to send only `gateway_transaction_id`
=> PP-6575 Update RefundSucceeded pact for new field

src/main/java/uk/gov/pay/ledger/event/model/TransactionEntityFactory.java, src/main/java/uk/gov/pay/ledger/event/service/EventService.java, src/main/java/uk/gov/pay/ledger/queue/EventDigestHandler.java, src/main/java/uk/gov/pay/ledger/queue/EventMessageHandler.java, src/main/java/uk/gov/pay/ledger/queue/eventprocessor/EventProcessor.java, src/main/java/uk/gov/pay/ledger/queue/eventprocessor/PaymentEventProcessor.java, src/main/java/uk/gov/pay/ledger/queue/eventprocessor/PayoutEventProcessor.java, src/main/java/uk/gov/pay/ledger/queue/eventprocessor/RefundEventProcessor.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/test/java/uk/gov/pay/ledger/event/service/EventServiceTest.java, src/test/java/uk/gov/pay/ledger/queue/EventDigestHandlerTest.java, src/test/java/uk/gov/pay/ledger/queue/QueueMessageReceiverIT.java
* Move event digest collection up to the processor level
* Model anything that can be projected as an event processor, this
should collect an event digest and project a domain object
with @kbottla
with @heathd
=> PP-6657 Split out event digest processors for domain object projection

src/main/java/uk/gov/pay/ledger/event/model/EventDigest.java, src/main/java/uk/gov/pay/ledger/exception/EmptyEventsException.java, src/main/java/uk/gov/pay/ledger/queue/eventprocessor/RefundEventProcessor.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/test/java/uk/gov/pay/ledger/queue/EventDigestHandlerTest.java, src/test/java/uk/gov/pay/ledger/queue/QueueMessageReceiverIT.java
Depends on https://github.com/alphagov/pay-ledger/pull/839
Update the RefundEventProcessor to pull shared payment attributes from
the payment event digest. These key: values are then added to the refund
event digest which allows all downstream projection (upserting a
transaction) to include this data.
Verify that attributes are set correctly.
With @kbottla
=> PP-6657 Refund event digest processor shared payment data

src/main/java/uk/gov/pay/ledger/transaction/model/Payment.java, src/main/java/uk/gov/pay/ledger/transaction/model/TransactionFactory.java
The Builder pattern is used by `Refund` and `TransctionView`, it allows
us to avoid giant constructors and will allow populating an imcomplete
payment for the shared refund/ payment details.
=> PP-6657 Refactor Payment model to use builder pattern

src/main/java/uk/gov/pay/ledger/queue/eventprocessor/RefundEventProcessor.java, src/main/java/uk/gov/pay/ledger/transaction/entity/TransactionEntity.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/test/java/uk/gov/pay/ledger/queue/EventDigestHandlerTest.java, src/test/java/uk/gov/pay/ledger/queue/QueueMessageReceiverIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java
- Project payment specific information as a nested object `payment_details` on `transaction_details` json blob
- Sets top level column directly instead of using objectMapper to set fields on refund transaction entity
=> PP-6657 Project payment details to nested blob

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactory.java, src/test/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceCsvIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
- Refunds stored within transaction table are now projected with payment details required (to search / for CSV data). These appear at top level (fields like reference, email, description and so on) on a table row and a few payment fields in `payment_details` (card_brand_label, wallet_type and so on) json nested within ``transaction_details` json blob.
- We can now search for refunds by payment values (like reference, email ...) directly and map payment specific fields onto refunds with payment fields available on refunds.
**Changes**
- Removes self join on transaction table for CSV query and directly map results to entities using `TransactionMapper`.
- Project refunds records in CSV with payment details available on refund records.
- Provider ID is set from payment/refund transactions as …
=> PP-6758 CSV consumer uses flat refunds

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/test/java/uk/gov/pay/ledger/pact/ContractTest.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoSearchIT.java
- Adds payments details expected by consumer (selfservice) for new `payment_details` json on refund transaction
- Also fixed csv search query to use filter template on transaction as parent transaction filter template is no longer applicable. 
- Updated DAO test to apply filters on fields
=> PP-6758 Pact states: Add payment details to refunds payload

src/main/java/uk/gov/pay/ledger/transaction/model/Refund.java, src/main/java/uk/gov/pay/ledger/transaction/model/TransactionFactory.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsValidator.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/TransactionView.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/test/java/uk/gov/pay/ledger/transaction/model/TransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsValidatorTest.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
- Removes `with_parent_transaction` flag from search transaction endpoint as it is no longer needed.
- Updated service, models and related tests to remove parent transaction object
=> PP-6766 Remove parent transaction

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParamsTest.java
- Added DAO method to use to count results up to configured limit instead of counting all rows for search
- Ensures the limit applied isn't below display_size, so total in the results won't be less than the actual number of search results.
=> PP-6768 Add DAO method to count total with limit

src/main/java/uk/gov/pay/ledger/common/search/SearchParams.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/main/java/uk/gov/pay/ledger/util/pagination/PaginationBuilder.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionServiceTest.java, src/test/java/uk/gov/pay/ledger/util/pagination/PaginationBuilderTest.java
- Added new query param `limit_total`. When param is set, counting total for search results is limited to `limit_tota_size` value or defaults.   When `total` is less than `limit_tota_size`, then `total` is accurate, otherwise it should be interpreted as ' > x rows' (where x is `limit_tota_size` set of default)
- Different set of pagination links are generated when `limit_total` is set. last_page is not available as accurate `total` is unknown.
=> PP-6768 Add new query param `limit_total`

src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/main/java/uk/gov/pay/ledger/util/pagination/PaginationBuilder.java, src/test/java/uk/gov/pay/ledger/util/pagination/PaginationBuilderTest.java
- When searching with `limit_total` flag enabled, next_link generated is an increment of current page. Use `count` to make sure `next_page` is generated only when there is possibility of more results i.e., when count is same as page_size.
=> PP-6768 Optimise next_link generation

src/main/java/uk/gov/pay/ledger/queue/eventprocessor/RefundEventProcessor.java, src/test/java/uk/gov/pay/ledger/queue/EventDigestHandlerTest.java, src/test/java/uk/gov/pay/ledger/queue/eventprocessor/RefundEventProcessorTest.java
Make public method in RefundEventProcessor for reprojecting a refund with payment information. This will be called by the
PaymentEventProcessor when a payment that is updated has existing refunds that need to be reprojected with the new payment details.
=> PP-6850 Make public method for refund reprojection

src/main/java/uk/gov/pay/ledger/event/model/EventDigest.java, src/main/java/uk/gov/pay/ledger/event/service/EventService.java, src/main/java/uk/gov/pay/ledger/queue/EventDigestHandler.java, src/main/java/uk/gov/pay/ledger/queue/eventprocessor/PaymentEventProcessor.java, src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/main/java/uk/gov/pay/ledger/util/JsonParser.java, src/test/java/uk/gov/pay/ledger/queue/EventDigestHandlerTest.java, src/test/java/uk/gov/pay/ledger/queue/eventprocessor/PaymentEventProcessorTest.java, src/test/java/uk/gov/pay/ledger/queue/eventprocessor/RefundEventProcessorTest.java
When a payment event is received, if it has associated refund, re-calculate the TransactionEntity for the refunds and persist.
This is to ensure that any payment details that we store on the refund are kept in sync with the payment.
Avoid database lookups to get refunds when we know we won't have to do any updates to refunds for the following cases:
- The payment has no previous salient events which map to the "SUCCESS" state, as in this case there cannot be refunds for the payment.
- The event we are processing has no "event_data" associated with it, as there will be no payment details that need to be updated on the refund.
- The event has type "REFUND_AVAILABILITY_UPDATED" as these events contain "event_data" but we know that we don't need to update anything on the refund in this case.
=> PP-6850 Re-project refunds when payment updated

.secrets.baseline, src/main/java/uk/gov/pay/ledger/app/config/ReportingConfig.java, src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java, src/main/resources/config/config.yaml, src/test/resources/config/test-config.yaml
- Removed limit on CSV transactions so we can enable and limit total count to 5K for selfservice searches.
For services with lots of transactions, users will need to apply filters (in selfservice) before downloading transactions.
- Also added .secrets.baseline file which is needed for gds-pre-commit (https://github.com/alphagov/gds-pre-commit) tool
=> PP-7018 Remove limit for CSV transactions

src/main/resources/env-map.yml
Correctly maps database username from secret service to a local environment variable.
=> PP-7020: Fix env-map db user parameter

src/main/java/uk/gov/pay/ledger/transaction/model/Payment.java, src/main/java/uk/gov/pay/ledger/transaction/model/Refund.java, src/main/java/uk/gov/pay/ledger/transaction/model/TransactionFactory.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/PaymentSettlementSummary.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/SettlementSummary.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/TransactionView.java, src/test/java/uk/gov/pay/ledger/transaction/model/TransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java
- add settlement summary to refund transaction type
- refactor SettlementSummary to have one common field between the different types of transactions
- add PaymentSettlementSummary that extends SettlementSummary
=> PP-6669 add settlement summary to refund

manifest.yml
We're now using vpc peered RDS instances and no longer need to bind to a
brokered RDS instance. Remove the `ledger_db` service binding from the
manifest so ledger will start.
We missed one, this will fix ledger which isn't currently above to deploy https://cd.gds-reliability.engineering/teams/pay-deploy/pipelines/deploy/jobs/deploy-ledger-staging/builds/90#L5f5a0fc1:18
=> PP-6913 Remove binding to ledger_db in ledger manifest

src/test/java/uk/gov/pay/ledger/pact/ContractTest.java
- refund in pact 'state three payments with payout dates exists' is missing parent_external_id
=> PP-7211 fix pact state missing parent id

src/test/java/uk/gov/pay/ledger/pact/ContractTest.java
- refund needs a real parent id not to break foreign key constraint
=> PP-7211 refund needs a real parent id

src/test/java/uk/gov/pay/ledger/pact/ContractTest.java
- the annotation 'IgnoreNoPactsToVerify' was temporary while we were adding some new pact tests. Remove it.
=> PP-7211 remove temporary annotation

manifest.yml
The `ENVIRONMENT` variable is used to distinguish our various
environments in Sentry (and is added to our structured logging under the
environment key).
This change will only impact apps deployed on PaaS and should allow us
to separate issues more obviously in Sentry.
Strictly speaking existing infra and paas apps have different `environment` tags in Sentry because paas environments do not have the `n` suffix, but this makes it much clearer.
=> PP-7241 Add `paas` environment prefix

pom.xml
This reverts commit 6788e23ab4fe165b667b6d4affbeb0d49823c466.
This version bump meant that running the consumer contract tests no longer
resulted in the pacts being created in `target/pacts` or AFAIK anywhere.
This meant they could not be pushed to the pact broker and deploying to
environments failed since CI was unable to tag a version of Ledger which
the pact broker had no knowledge of.
Tested this out locally, see pacts https://pact-broker-test.cloudapps.digital/hal-browser/browser.html#/pacticipants/ledger/versions/d8b1c7d62c7a6e45ba6b761bbf80fb1701cca3f4
I haven't looked at why this Junit Jupiter version bump was stopping the pacts being created.
Now that we know ledger should have a pact we might want to remove the `do not fail if there are no pacts` flag when running ledger …
=> BAU Revert Junit Jupiter bump to 5.7

src/test/java/uk/gov/pay/ledger/pact/ConnectorContractTest.java
This will mean master builds will continue to pass even though there
is currently no verification for connector -> ledger pacts
=> PP-7253 Add ignore no pacts to verify annotation

src/test/java/uk/gov/pay/ledger/pact/ConnectorContractTest.java
We now have pacts published for connector as a consumer with ledger as a provider, so this annotation can be removed.
=> PP-7253 Remove IgnoreNoPactsToVerify notification

src/test/java/uk/gov/pay/ledger/pact/PaymentDetailsEnteredEventQueueContractTest.java
- Removed `email` from payment details entered test as a separate event (USER_EMAIL_COLLECTED)
is generated by connector when email is updated
=> PP-7276 Remove email from PaymentDetailsEntered contract test

src/test/java/uk/gov/pay/ledger/pact/CancelledByUserEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/pact/ConsumerContractTestSuite.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java
- the structure of the CANCELLED_BY_USER event has changed and now it contains event data (gateway transaction id). This change adds a consumer pact test for the refactored event.
=> PP-7277 add pact test for cancelled by user event

src/main/java/uk/gov/pay/ledger/transaction/state/TransactionState.java, src/test/java/uk/gov/pay/ledger/report/resource/PerformanceReportResourceIT.java
- Maps salient event `CANCEL_BY_EXTERNAL_SERVICE_FAILED` to transaction state `CANCELLED`
=> PP-6989 Map `cancel by external service failed` salient event to transaction state

src/test/java/uk/gov/pay/ledger/pact/Gateway3dsExemptionResultObtainedEventQueueContractTest.java
Description:
- This PR renames the externalId in Gateway3dsExemptionResultObtainedEventQueueContractTest to exemptionResult_externalId so that it is 26 characters. The previous version was 44 characters which caused a PSQLException when the Pact test was run
=> PP-7609 - Rename externalId so that it is 26 characters

src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java
Temporarily disable `TransactionDaoIT.sourceTypeInDatabase_shouldMatchValuesInEnum`, which checks that the values of the `source` enum in the database match those of the `Source` enum in the Java code.
We’re adding a new `CARD_AGENT_INITIATED_MOTO` value and since our database migrations are decoupled from our code changes, we can’t update both ledger’s database and the imported enum atomically.
So we’re going to have to disable the test, migrate the database, update the Java enum, then re-enable the test.
=> PP-7696 Temporarily disable database source enum test

src/main/resources/migrations/00054_add_CARD_AGENT_INITIATED_MOTO_source.sql
Add `CARD_AGENT_INITIATED_MOTO` to the `source` enum in the database, inserting it before `CARD_EXTERNAL_TELEPHONE`.
=> PP-7696 Add CARD_AGENT_INITIATED_MOTO to source database enum

pom.xml, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java
Update to latest Pay Java commons so that we get the updated `Source` enum with the `CARD_AGENT_INITIATED_MOTO` value. The database was migrated to be aware of this in commit 13233115e27dd789596a107443f3d57beb6d45a9.
Re-enable the test that checks the `Source` enum in the code matches the `source` enum in the database because they’re in sync again now.
=> PP-7696 Add Source.CARD_AGENT_INITIATED_MOTO and unignore test

src/main/resources/migrations/00057_make_transaction_id_and_metadata_key_id_unique_combo.sql
- to be able to create an upsert sql command on transaction_metadata table we need to use `ON CONFLICT`. `ON CONFLICT` will be only triggered if transaction_id and metadata_key_id are a unique combination.
=> PP-7832 add unique constraint on transaction_metadata table

src/main/java/uk/gov/pay/ledger/metadatakey/dao/MetadataKeyDao.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/main/java/uk/gov/pay/ledger/transactionmetadata/dao/TransactionMetadataDao.java, src/test/java/uk/gov/pay/ledger/metadatakey/dao/MetadataKeyDaoIT.java, src/test/java/uk/gov/pay/ledger/transactionmetadata/dao/TransactionMetadataDaoIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionMetadataFixture.java
- Changes to find metadata keys for transactions searched by metadata value.
- Currently all metadata keys are returned for matching transactions (based on search criteria). transaction table is joined with transaction_metadata to find all keys.
- When transactions are searched by metadata value, all metadata keys are returned for transactions for which atleast one metadata value matches. For this, first find transactions for metadata value and then find all keys for these transactions.
- Rename `TransactionMetadataKeyDaoIT` to `MetadataKeyDaoIT` as this dao is for operations on metadata_key table only.
=> PP-7833 Metadata keys for search transactions by metadata value

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/main/java/uk/gov/pay/ledger/transactionmetadata/dao/TransactionMetadataDao.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceCsvIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceSearchIT.java, src/test/java/uk/gov/pay/ledger/transactionmetadata/dao/TransactionMetadataDaoIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/MetadataKeyFixture.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
- Added functionality to search transacions by metadata_value
- transaction_metadata is joined with transaction (when searching by metadata_value). This can return multiple rows for a transaction as metadata `value` is not unique. To avoid duplicates `distinct` clause is added to the queries when searching by metadata_value.
- Based on query plan for two options, joining transaction_metadata and getting distinct result is performant as indexes `transaction_metadata_lower_value_idx & transaction_pkey` are used first and the results are filtered by other search criteria
- Where as using IN clause could first use indexes on transaction table and could slow the query
```
explain analyse select
distinct t.*,
po.paid_out_date as paid_out_date
from
transaction t
inner join transaction_metadata …
```
=> PP-7833 Search transactions by metadata_value

src/main/java/uk/gov/pay/ledger/queue/eventprocessor/PaymentEventProcessor.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionMetadataService.java, src/test/java/uk/gov/pay/ledger/queue/EventDigestHandlerTest.java, src/test/java/uk/gov/pay/ledger/queue/eventprocessor/PaymentEventProcessorTest.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionMetadataServiceTest.java
- refactor TransactionMetadataService to use EventDigest instead of Event for upserting transaction_metadata
- add/refactor relevant tests
=> PP-7832 refactor TransactionMetadataService to use EventDigest for upsert

src/main/java/uk/gov/pay/ledger/transaction/service/TransactionMetadataService.java, src/main/java/uk/gov/pay/ledger/transactionmetadata/dao/TransactionMetadataDao.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionMetadataServiceTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java
Use JsonNode::asText rather than JsonNode::textValue to get string value to insert into the `transaction_metadata` table. Previously, boolean and number values were not being inserted.
=> PP-7832 Fix getting metadata values

src/test/java/uk/gov/pay/ledger/pact/ContractTest.java
- For pact state `a transaction with metadata exists`, insert transaction_metadata & metadata rows as well so this state can be used by pact (search by metadata)
=> PP-7859 Insert transaction_metadata for metadata pact state

src/main/java/uk/gov/pay/ledger/event/dao/mapper/EventMapper.java, src/main/java/uk/gov/pay/ledger/event/model/Event.java, src/main/java/uk/gov/pay/ledger/event/model/response/CreateEventResponse.java, src/main/java/uk/gov/pay/ledger/queue/EventMessage.java, src/main/java/uk/gov/pay/ledger/queue/EventMessageDto.java, src/main/java/uk/gov/pay/ledger/queue/EventMessageHandler.java, src/test/java/uk/gov/pay/ledger/queue/EventMessageHandlerTest.java, src/test/java/uk/gov/pay/ledger/queue/EventQueueTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/EventFixture.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePayoutEventFixture.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueueRefundEventFixture.java
Handle events having a boolean `reproject_domain_object` field on event messages.
When this field is present, skip persisting the event to the database.
Will handle performing the re-projection of transaction_metadata in the next commit.
=> PP-7906 Accept reproject_domain_object field on events

src/main/java/uk/gov/pay/ledger/queue/EventMessageHandler.java, src/main/java/uk/gov/pay/ledger/queue/eventprocessor/PaymentEventProcessor.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionMetadataService.java, src/test/java/uk/gov/pay/ledger/queue/EventDigestHandlerTest.java, src/test/java/uk/gov/pay/ledger/transaction/service/TransactionMetadataServiceTest.java
Reproject `transaction_metadata` rows from the EventDigest when an event is processed with the field `reproject_domain_object` set to true.
This will not take into account any of the event details on the event being processed, only previous events for the transaction from the database.
When an event is processed without this field, or set to false, continue to only upsert to the `transaction_metadata` when the event being processed has `external_metatada` in its event details.
=> PP-7906 Reproject transaction_metadata

src/main/java/uk/gov/pay/ledger/queue/EventMessageHandler.java, src/test/java/uk/gov/pay/ledger/queue/EventDigestHandlerTest.java, src/test/java/uk/gov/pay/ledger/queue/EventMessageHandlerTest.java
If event has `reproject_domain_object` flag set to true, log the
event_type so that there is an audit record for when reprojection is
performed.
Also only log the `reproject_domain_object_event` field on the log line
when it is true to avoid unnecessary information on other log lines.
=> PP-7906 Log event_type for reprojection events

src/main/java/uk/gov/pay/ledger/queue/EventMessage.java, src/main/java/uk/gov/pay/ledger/queue/EventMessageHandler.java, src/test/java/uk/gov/pay/ledger/queue/sqs/EventQueueIT.java
We were logging the resource external id as the `id` when we processed events. However we were already logging this on the same message as `resource_external_id`. Log the queue message id as this is useful to link up with emitted events.
=> PP-7906 Log queue message id for events

src/main/java/uk/gov/pay/ledger/transactionsummary/dao/TransactionSummaryDao.java, src/test/java/uk/gov/pay/ledger/transactionsummary/dao/TransactionSummaryDaoIT.java
- Split out updating fee from transaction_summary insert/update as fee won't be available on the first successful event (which is used to update total_amount_in_pence).
- as fee is available only on capture_confirmed event, updateFee method will be used when processing CAPTURE_CONFIRMED event or when all info to project fee is available.
=> PP-8025 Update/Add DAO methods for transaction_summary

src/main/java/uk/gov/pay/ledger/queue/EventDigestHandler.java, src/main/java/uk/gov/pay/ledger/queue/EventMessageHandler.java, src/main/java/uk/gov/pay/ledger/queue/eventprocessor/PaymentEventProcessor.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/main/java/uk/gov/pay/ledger/transactionsummary/service/TransactionSummaryService.java, src/test/java/uk/gov/pay/ledger/queue/EventDigestHandlerTest.java, src/test/java/uk/gov/pay/ledger/queue/QueueMessageReceiverIT.java, src/test/java/uk/gov/pay/ledger/queue/eventprocessor/PaymentEventProcessorTest.java, src/test/java/uk/gov/pay/ledger/transactionsummary/service/TransactionSummaryServiceTest.java, src/test/resources/config/test-config.yaml
- Projects transaction summary from event stream when transaction state is finished
- To be able to project transaction summary, PAYMENT_CREATED event should exists for the transaction as this event carries required information (gateway_account_id, moto, live, amount) along with a terminal event. So projects transaction summary if event is PAYMENT_CREATED event and transaction state is finished or for an event that maps to transaction finished state.
- In case of multiple events (ex: USER_APPROVED_FOR_CAPTURE, CAPTURE_SUBMITTED, CAPTURED_CONFIRMED) leading to same terminal state, transaction_summary is updated only once to avoid updating summary multiple times for a payment.
- Projects fee for CAPTURE_CONFIRMED event as fee is expected only on this event. Multiple CAPTURE_CONFIRMED events …
=> PP-8025 Project transaction summary from event stream

src/main/java/uk/gov/pay/ledger/report/dao/PerformanceReportDao.java, src/main/java/uk/gov/pay/ledger/report/entity/GatewayAccountMonthlyPerformanceReportEntity.java, src/main/java/uk/gov/pay/ledger/report/mapper/GatewayAccountMonthlyPerformanceReportEntityMapper.java, src/main/java/uk/gov/pay/ledger/report/resource/PerformanceReportResource.java, src/main/java/uk/gov/pay/ledger/transactionsummary/dao/TransactionSummaryDao.java, src/test/java/uk/gov/pay/ledger/report/dao/PerformanceReportDaoIT.java, src/test/java/uk/gov/pay/ledger/report/resource/PerformanceReportResourceIT.java, src/test/java/uk/gov/pay/ledger/transactionsummary/dao/TransactionSummaryDaoIT.java
Description:
- Refactors /gateway-performance-report to use the transaction_summary table via TransactionSummaryDao
- Since the transaction_summary table doesn't contain a minimum and maximum amount nor can it be calculated from the table it is omitted in the JSON response
- The transaction_summary table no longer has timezone so where appropriate ZonedDateTime has been replaced with LocalDateTime
- The corresponding Toolbox PR for sending dates instead of timezones will need to be merged as LocalDate.parse(...) will throw an exception if timezones are contained. Currently Toolbox sends
timezone data
- Unnecessary .log() from previous testing has been removed
=> PP-8026 - Refactor monthly gateway performance report with transaction summary

src/main/java/uk/gov/pay/ledger/transactionsummary/dao/TransactionSummaryDao.java, src/main/java/uk/gov/pay/ledger/transactionsummary/service/TransactionSummaryService.java, src/test/java/uk/gov/pay/ledger/queue/QueueMessageReceiverIT.java, src/test/java/uk/gov/pay/ledger/report/resource/PerformanceReportResourceIT.java, src/test/java/uk/gov/pay/ledger/transactionsummary/dao/TransactionSummaryDaoIT.java, src/test/java/uk/gov/pay/ledger/transactionsummary/service/TransactionSummaryServiceTest.java, src/test/java/uk/gov/pay/ledger/util/DatabaseTestHelper.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionSummaryFixture.java
- Use LocalDate explicitly for operations on transaction summary instead of using ZonedDateTime as granualarity of data (in transaction_summary) is at day level
=> PP-8050 Use LocalDate for transaction summary

src/main/resources/migrations/00062_create_table_to_test_concourse_db_migration.sql
We want to test the [ledger database migration job](https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/deploy-to-test/jobs/ledger-db-migration/).
This table will be deleted.
=> PP-7918: Create table to test the concourse db migration

src/main/resources/migrations/00063_drop_test_concourse_db_migration.sql
The database migration ran
[successfully](https://cd.gds-reliability.engineering/teams/pay-dev/pipelines/deploy-to-test/jobs/ledger-db-migration/builds/24)
so reverting the test table.
=> PP-7918: Drop the table that tested the concourse db migration

src/main/java/uk/gov/pay/ledger/queue/EventDigestHandler.java, src/main/java/uk/gov/pay/ledger/queue/EventMessageHandler.java, src/main/java/uk/gov/pay/ledger/queue/eventprocessor/EventProcessor.java, src/main/java/uk/gov/pay/ledger/queue/eventprocessor/PaymentEventProcessor.java, src/main/java/uk/gov/pay/ledger/queue/eventprocessor/PayoutEventProcessor.java, src/main/java/uk/gov/pay/ledger/queue/eventprocessor/RefundEventProcessor.java, src/main/java/uk/gov/pay/ledger/transactionsummary/service/TransactionSummaryService.java, src/test/java/uk/gov/pay/ledger/queue/EventDigestHandlerTest.java, src/test/java/uk/gov/pay/ledger/queue/EventMessageHandlerTest.java, src/test/java/uk/gov/pay/ledger/queue/eventprocessor/PaymentEventProcessorTest.java, src/test/java/uk/gov/pay/ledger/transactionsummary/service/TransactionSummaryServiceTest.java
- Ledger can receive event multiple times for various reasons (parity checker reemitting events, emitting events for a charge for manual fixes, backfilling charges for any reason). In case ledger receives event more than once we don't want to project transaction summary so only project if ledger sees event for the first time.
- Currently summary is projected only when PAYMENT_CREATED event exists but for telephone payment reported the equivalent is "PAYMENT_NOTIFICATION_CREATED" event.
- Excludes CAPTURE_SUBMITTED & CAPTURE_CONFIRMED events as the prior events USER_APPROVED_FOR_CAPTURE and SERVICE_APPROVED_FOR_CAPTURE lead to same transaction state.
- Project transaction summary based on the current working list of events as getting events from database could result in new events …
=> PP-8050 Project transaction_summary for new events only

src/main/java/uk/gov/pay/ledger/transactionsummary/service/TransactionSummaryService.java, src/test/java/uk/gov/pay/ledger/queue/QueueMessageReceiverIT.java, src/test/java/uk/gov/pay/ledger/transactionsummary/service/TransactionSummaryServiceTest.java
- Current transaction summary (for success state) is projected for USER_APPROVED_FOR_CAPTURE OR SERVICE_APPROVED_FOR_CAPTURE events. But for telephone payments these events are not available.
- Use CAPTURE_SUBMITTED event instead as it is available for all use cases (user approved, service approved, telephone payments)
=> PP-8050 Use CAPTURE_SUBMITTED event to project transaction summary

.github/dependabot.yml
Add dependabot configuration to raise pull requests to update GitHub actions when there are new versions. as per https://docs.github.com/en/code-security/supply-chain-security/keeping-your-actions-up-to-date-with-dependabot
with @SandorArpa
=> PP-8047 Add dependabot configuration for Github actions

src/main/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactory.java, src/test/java/uk/gov/pay/ledger/report/resource/ReportResourceIT.java, src/test/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceCsvIT.java
- Added new column "Payment Provider" to the CSV stream. Field will be added as last field but before metadata fields
- Only available for payment transactions, as payment provider is not available for refund transactions
=> PP-8286 Add "Payment Provider" column to CSV stream

src/test/java/uk/gov/pay/ledger/pact/PaymentCreatedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/pact/PaymentNotificationCreatedEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java
- Added new field `credential_external_id` expected for PAYMENT_CREATED and PAYMENT_NOTIFICATION_CREATED event pacts
=> PP-8270 Add `credential_external_id` to pact tests

README.MD
Update `README.MD` to reference the Cabinet Office CDIO Cyber Security vulnerability disclosure policy and security.txt file rather than the GOV.UK Pay security vulnerability email address.
=> PP-8095 Update vulnerability disclosure in README.MD

src/main/resources/migrations/00064_add_service_id_and_live_coumn_to_event_table.sql, src/main/resources/migrations/00065_add_service_id_column_to_transaction_table.sql, src/main/resources/migrations/00066_add_service_id_and_live_column_to_payout_table.sql
We are re-orienting all payment data around services rather than gateway accounts. To enable this, events coming in to ledger will have a top level attribute of `service_id` and `live`.
This adds necessary columns to store these values in event table. I have been consistent with column naming by using
`live` to indicate whether an event is live or test.
Also adds service_id column to transaction table, and adds index on `service_id`. Added concurrently to avoid long lived table lock.
Also adds service_id and live column to payouts, with same index as transaction table,  plus partial index on live payoputs for our old friend toolbox.
=> PP-8440 Add service_id and live to event, transaction, payout tables

src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceSearchIT.java
Description:
- The previous PR (https://github.com/alphagov/pay-ledger/pull/1404) means that AuthorisationSummary is returned in TransactionView
which is used by TransactionSearchResponse. Hence searching for transactions returns the AuthorisationSummary JSON blob.
- Adds a test for this
=> PP-8543 - Add search transaction authorisation summary test

src/test/java/uk/gov/pay/ledger/pact/ContractTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
- add new field to payload of 'a payment transaction exists' pact
- add new pact state 'a transaction with 3ds version exists'
=> PP-8535 add authorisation summary to get payment contract test

Jenkinsfile
This should un-break the Jenkins Pact Tests now that microservices_v1 are gone.
=> [PP-8695] Remove ECS Deploy Step from Jenkinsfile

src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java
The pact broker does some clever stuff to compare pact files, so every single version of the consumer doesn't need to be verified against every single version of the provider if the pact hasn't changed.
When there is randomness in the pact this is prevented, meaning apps have to be deployed in a particular order, and only certain versions can be deployed depending on which commit the consumer was verified against.
=> BAU Remove randomness from pact tests

src/test/java/uk/gov/pay/ledger/pact/ConnectorContractTest.java, src/test/java/uk/gov/pay/ledger/pact/PublicApiContractTest.java, src/test/java/uk/gov/pay/ledger/pact/SelfServiceContractTest.java
The purpose of running the provider contract test is to ensure the app can be
deployed to the test environment without breaking its contractual obligations
with other apps. Pacts are tagged with 'test-fargate' in the concourse deploy
pipeline for app deployments so this tag needs to be updated.
=> bau: Use 'test-fargate' when running provider contract test

src/main/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactory.java, src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java, src/main/java/uk/gov/pay/ledger/transaction/service/CsvService.java, src/test/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceCsvIT.java
- Adds fee breakdown fields to CSV download if the query param `fee_breakdown_headers` is set.
- Fields appear as below in CSV
=> PP-9038 Add fee breakdown to CSV

.github/dependabot.yml
Fixed a duplication error in the configuration that was causing a parsing issue and added missing labels to GHA
=> pp-7475 fix errors in config, add labels to GH actions

README.MD, src/main/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactory.java, src/test/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceCsvIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
When downloading transaction details in CSV format, Ledger now returns a `0.00` net value for a failed payment that has no `net_amount`. Refund behaviour is unchanged.
README tables reformatted with correct width.
=> PP-8951 update the CSV transaction factory to zero `net` when appropriate

src/main/resources/migrations/00067_index_transaction_gateway_account_id_created_date.sql
- Adds a multicolumn index on ‘gateway_account and created_date’ columns of transaction table which could address slow query issues (which also fixed scheduled performance job for search https://build.ci.pymnt.uk/view/HUD/job/run-scheduled-performance-test-for-search/208/ that has been failing for a long time) when services load all services transactions page.
- This may not address the slow queries issue fully because of the different combination of search params allowed on the transaction table. Need to look into different indexes and remove any not required separately.
=> PP-9252 Add index on gateway_account_id and created_date columns

src/main/resources/migrations/00068_add_gateway_account_metadata_table.sql
- Add new table `gateway_account_metadata` which stores gateway accounts and the metadata keys accounts used for payments overtime. This is to be used to get CSV metadata headers.
=> PP-9311 Create gateway_account_metadata table

src/main/java/uk/gov/pay/ledger/gatewayaccountmetadata/service/GatewayAccountMetadataService.java, src/main/java/uk/gov/pay/ledger/transaction/service/CsvService.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionMetadataService.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceCsvIT.java, src/test/java/uk/gov/pay/ledger/util/DatabaseTestHelper.java
Use the gateway_account_metadata table to get all metadata keys for
gateway accounts included in a CSV download, rather than just the keys
for transactions that are included.
We've changed this behaviour as querying with joins on the transaction
table to get the keys was very expensive and was causing CSV downloads
to take a long time or time out.
Co-authored-by: Stephen Daly <stephen.daly@digital.cabinet-office.gov.uk>
=> PP-9311 Update CSV service to use gateway account metadata table

src/test/java/uk/gov/pay/ledger/rule/SqsTestDocker.java, src/test/resources/testcontainers.properties
Updated the following images used by `testcontainers`:
-   `testcontainersofficial/ryuk` -> `testcontainers/ryuk:0.3.3`
-  `oribio16/alpine-sqs` -> `mvisonneau/alpine-sqs:1.2.0`
=> BAU Update images used by testscontainers for M1 compatibility

.github/workflows/_run-pact-provider-tests.yml
Add ledger-as-provider reusable github workflow.
This is basically a copy and paste of the connector one we already merged but with the word connector swapped with ledger :)
You can see a test PR in frontend running this (Look for the "[Test ledger as provider pact / ledger-provider-contract-tests / Run Ledger as Provider](https://github.com/alphagov/pay-frontend/runs/5534792533?check_suite_focus=true)" action):
https://github.com/alphagov/pay-frontend/pull/2744
=> PP-9379: Add ledger as provider pact test reusable workflow

.github/workflows/post-merge.yml
Looking at the Jenkinsfile, we want to run maven with `-DrunConsumerContractTests` when running a ledger-as-consumer build.
Example [successful run](https://github.com/alphagov/pay-ledger/runs/5585002629?check_suite_focus=true).
=> Pp 9236 run consumer contract tests profile

src/main/java/uk/gov/pay/ledger/app/config/SnsConfig.java, src/main/java/uk/gov/pay/ledger/eventpublisher/TopicName.java, src/main/java/uk/gov/pay/ledger/eventpublisher/TopicNameArnMapper.java, src/main/java/uk/gov/pay/ledger/queue/EventMessageHandler.java, src/main/resources/config/config.yaml, src/test/java/uk/gov/pay/ledger/eventpublisher/EventPublisherTest.java, src/test/java/uk/gov/pay/ledger/queue/EventMessageHandlerTest.java
Publish dispute events to the SNS topic card_payment_dispute_events.
Add feature flags to separately enable sending events to the
card_payment_events topic and the card_payment_dispute_events topic.
=> PP-9278 Publish dispute events to SNS

src/main/java/uk/gov/pay/ledger/queue/EventMessage.java, src/main/java/uk/gov/pay/ledger/queue/EventMessageHandler.java, src/test/java/uk/gov/pay/ledger/queue/EventMessageHandlerTest.java
When serialising the event to send to SNS, use the EventMessageDto,
rather then the internal Event model. This ensures that the field names
are unchanged from the event received from connector. In particular,
the "event_details" fields is renamed to "event_data" in the internal
ledger Event model.
This field isn't deserialised by webhooks, so we won't break anything
by changing it.
=> PP-9278 Fix serialisation of SNS message

src/main/java/uk/gov/pay/ledger/queue/EventMessage.java, src/main/java/uk/gov/pay/ledger/queue/EventMessageDto.java
Rename `event_date` to `timestamp` match the original event spec (from producer
Connector). The event store shouldn't be doing any renaming on event
fields before publishing.
Downstream services receiving events parse event metadata. Now that this
is the publishing DTO, make sure a standard format is used for time.
=> BAU Serialise event date using standard pay format

src/main/java/uk/gov/pay/ledger/event/model/EventDigest.java, src/test/java/uk/gov/pay/ledger/event/model/EventDigestTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/EventFixture.java
- Derived service_id if any one event in the given list has service_id.
- This is because some events from connector doesn't have service_id set and service_id on the transaction could be null if taken from latest event.
=> PP-9281 Derive service_id from events

openapi/ledger_spec.yaml, pom.xml, src/main/java/uk/gov/pay/ledger/event/model/Event.java, src/main/java/uk/gov/pay/ledger/event/model/EventTicker.java, src/main/java/uk/gov/pay/ledger/event/resource/EventResource.java, src/main/java/uk/gov/pay/ledger/payout/model/PayoutSearchResponse.java, src/main/java/uk/gov/pay/ledger/payout/model/PayoutView.java, src/main/java/uk/gov/pay/ledger/payout/resource/PayoutResource.java, src/main/java/uk/gov/pay/ledger/payout/search/PayoutSearchParams.java, src/main/java/uk/gov/pay/ledger/util/pagination/PaginationLink.java, src/main/resources/openapi-config.yaml
- Added swagger library to generate openAPI specs for ledger endpoints
- Initial config to generate openAPI specs
- Annotated event & payout resources and generated openAPI specs for these endpoints
- Preview (using https://editor.swagger.io/)
=> PP-9456 OpenAPI specs for events and payouts resources

openapi/ledger_spec.yaml, pom.xml, src/main/java/uk/gov/pay/ledger/transaction/model/Payment.java, src/main/java/uk/gov/pay/ledger/transaction/model/TransactionFactory.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/TransactionView.java, src/test/java/uk/gov/pay/ledger/transaction/model/TransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java
Return authorisation_mode field in all payment responses. Read this from the transaction details for the payment if it exists, else default to "web" for historic transactions.
Modify the queue message contract test for the PAYMENT_CREATED event to expect this field in the event from connector.
=> PP-9142 Return authorisation_mode in payment responses

src/main/resources/migrations/00070_add_agreements_payment_instrument_tables.sql, src/main/resources/migrations/00071_add_payment_instrument_resource_type.sql
Add database tables for recurring card payments, including the data
required to project these entities from event streams.
Agreements - agreements between services and paying users, stable
identifier for associating payment instruments with.
Payment instruments - currently targeted at card payment instruments,
future projections should factor in additional "methods" (when they
exist!).
Adds `payment_instrument` as a resource type known to Leger (for
processing event streams).
Note that `agreement` was included in the original resource types from
the get go. See https://github.com/alphagov/pay-ledger/pull/15
=> PP-9531 Agreements payment instrument projection tables

src/main/java/uk/gov/pay/ledger/agreement/dao/AgreementDao.java, src/main/java/uk/gov/pay/ledger/agreement/dao/AgreementMapper.java, src/main/java/uk/gov/pay/ledger/agreement/dao/PaymentInstrumentDao.java, src/main/java/uk/gov/pay/ledger/agreement/entity/AgreementEntity.java, src/main/java/uk/gov/pay/ledger/agreement/entity/PaymentInstrumentEntity.java, src/test/java/uk/gov/pay/ledger/agreement/AgreementDaoIT.java, src/test/java/uk/gov/pay/ledger/agreement/PaymentInstrumentDaoIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/AgreementFixture.java, src/test/java/uk/gov/pay/ledger/util/fixture/PaymentInstrumentFixture.java
Entities to be mapped to agreement and payment instrument table rows.
DAO and JDBI row mappers for agreements and payment instruments.
Fetch agreements with their latest payment instrument using Postgres
`SELECT DISTINCT ON`.
Test coverage to assert that row mappers are correctly mapping and
casting fields.
Test coverage to assert that the latest payment instrument (by created
date) is associated with an agreement when pulled out of the database
and mapped to an agreement entity.
=> PP-9531 Agreements and payment instrument DAO

src/main/resources/migrations/00072_remove_event_sqs_message_id_null_constraint.sql
The SQS message ID is never used outside of interacting with an
in-flight recieved SQS message. The identifier is then stored in the
database only for developer auditing.
Allow this column to be null to allow events to be produced by other
non-SQS message sources (HTTP endpoint).
=> PP-9526 Remove sqs message id null constraint

src/main/java/uk/gov/pay/ledger/app/LedgerModule.java, src/main/java/uk/gov/pay/ledger/event/resource/EventResource.java, src/main/java/uk/gov/pay/ledger/queue/EventMessage.java, src/main/java/uk/gov/pay/ledger/queue/EventMessageHandler.java, src/main/java/uk/gov/pay/ledger/queue/EventQueue.java, src/test/java/uk/gov/pay/ledger/event/resource/EventResourceIT.java, src/test/java/uk/gov/pay/ledger/event/resource/EventResourceTest.java, src/test/java/uk/gov/pay/ledger/queue/EventMessageHandlerTest.java
Depends on https://github.com/alphagov/pay-ledger/pull/1857
---
Sync write event endpoint. Accepts an array of standard Pay event JSON.
This interface directly matches events that are consumed from SQS.
Add coverage to assert events passed into this list (POST body) are
written to the database.
Ensure that any interactions with `jdbi` are rolled back if
any
individual event fails to process, this includes:
* writing events
* domain object projection
Add coverage with an incomplete event (missing resource external ID) --
this will fail a nullable column constraint and cause the batch to rollback.
=> PP-9526 Sync event write endpoint

src/main/java/uk/gov/pay/ledger/agreement/dao/AgreementDao.java, src/main/java/uk/gov/pay/ledger/agreement/model/Agreement.java, src/main/java/uk/gov/pay/ledger/agreement/model/AgreementSearchResponse.java, src/main/java/uk/gov/pay/ledger/agreement/model/PaymentInstrument.java, src/main/java/uk/gov/pay/ledger/agreement/resource/AgreementResource.java, src/main/java/uk/gov/pay/ledger/agreement/resource/AgreementSearchParams.java, src/main/java/uk/gov/pay/ledger/agreement/service/AgreementService.java, src/main/java/uk/gov/pay/ledger/app/LedgerApp.java, src/main/java/uk/gov/pay/ledger/app/LedgerModule.java, src/test/java/uk/gov/pay/ledger/agreement/AgreementDaoIT.java, src/test/java/uk/gov/pay/ledger/agreement/resource/AgreementResourceIT.java, src/test/java/uk/gov/pay/ledger/agreement/resource/AgreementResourceTest.java, src/test/java/uk/gov/pay/ledger/util/DatabaseTestHelper.java, src/test/java/uk/gov/pay/ledger/util/fixture/AgreementFixture.java, src/test/java/uk/gov/pay/ledger/util/fixture/PaymentInstrumentFixture.java
Add endpoints to
* get one agreement
* search for agreements
Agreement search supports standard Pay result response
* pagination
* filtering on `status` and `reference`
Lifts core pagination and search string templating methodology directly from transaction search.
Either `gateway_account_id` or `service_id` is required to access the
search endpoint. This should guard against consumers accidentally
requesting data across services.
Adds agreement service to manage search functionality.
HTTP endpoints generally follow a pattern of serialising an external
facing model rather than using the database entities. Add agreement and
payment instrument shaped models.
=> PP-9533 Agreement resource

src/main/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactory.java, src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java, src/main/java/uk/gov/pay/ledger/transaction/service/CsvService.java, src/test/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceCsvIT.java
- Stripe contract fee V2 is applicable to all services which use Stripe thus we no longer need `includeFeeBreakdownHeaders`. All Stripe csv downloads will contain the fee break down. Remove all traces of separate fee  break down.
- Update tests accordingly.
=> PP-8608 remove deprecated stripe contract fee handling

src/test/java/uk/gov/pay/ledger/pact/ConsumerContractTestSuite.java, src/test/java/uk/gov/pay/ledger/pact/DisputeLostEventQueueContractTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueueDisputeEventFixture.java
- implement `a dispute lost event` pact test
Note: there is a bug in pact's matchInteger code that does not recognise a negative number as such. Add `net_amount` to this test once a fix from pact has been released.
=> PP-9577 add dispute lost event pact test

src/main/java/uk/gov/pay/ledger/queue/EventDigestHandler.java, src/main/java/uk/gov/pay/ledger/queue/eventprocessor/AgreementEventProcessor.java, src/main/java/uk/gov/pay/ledger/queue/eventprocessor/PaymentEventProcessor.java, src/main/java/uk/gov/pay/ledger/queue/eventprocessor/PaymentInstrumentEventProcessor.java, src/main/java/uk/gov/pay/ledger/queue/eventprocessor/PayoutEventProcessor.java, src/test/java/uk/gov/pay/ledger/queue/EventDigestHandlerTest.java, src/test/java/uk/gov/pay/ledger/queue/eventprocessor/AgreementEventProcessorTest.java, src/test/java/uk/gov/pay/ledger/queue/eventprocessor/ChildTransactionEventProcessorTest.java, src/test/java/uk/gov/pay/ledger/queue/eventprocessor/PaymentEventProcessorTest.java, src/test/java/uk/gov/pay/ledger/queue/eventprocessor/PaymentInstrumentEventProcessorTest.java, src/test/java/uk/gov/pay/ledger/queue/eventprocessor/PayoutEventProcessorTest.java
This test was kind of a hybrid integration/unit test, which was performing some unit testing of the EventProcessor implementations.
Move all unit testing of the EventProcessors to dedicated unit tests.
Make EventDigestHandlerTest a pure unit test, so that it is only testing that the correct EventProcessor is selected.
=> PP-9626 Refactor EventDigestHandlerTest

src/main/java/uk/gov/pay/ledger/transaction/model/TransactionFactory.java, src/main/java/uk/gov/pay/ledger/util/JsonParser.java, src/test/java/uk/gov/pay/ledger/transaction/model/TransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceSearchIT.java, src/test/java/uk/gov/pay/ledger/util/JsonParserTest.java
- Reads evidence_due_date as a date from the database instead of an epoch. Connector to send evidence_due_date in ISO 8601 format as part of DISPUTE_CREATED event.
=> PP-9788 Read evidence_date as date instead of epoch

src/main/resources/migrations/00074_add_agreement_id_column_to_transactions.sql
Transaction projections need to be searchable by their agreement id,
move this from the transaction details `jsonb` blob to a table that can
be indexed for lookup.
Run the add index concurrently in order to not lock existing
transactions.
=> PP-9530 Add agreement id column to transactions

src/main/java/uk/gov/pay/ledger/util/DisputeReasonMapper.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceSearchIT.java, src/test/java/uk/gov/pay/ledger/util/DisputeReasonMapperTest.java
- `DisputeReasonMapper` should return null when reason is missing or an empty string. That's to avoid returning an empty field through the API.
=> PP-9627 change dispute mapper

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/dao/mapper/TransactionMapper.java, src/main/java/uk/gov/pay/ledger/transaction/entity/TransactionEntity.java, src/main/java/uk/gov/pay/ledger/transaction/model/Payment.java, src/main/java/uk/gov/pay/ledger/transaction/model/TransactionFactory.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/TransactionView.java, src/test/java/uk/gov/pay/ledger/event/model/TransactionEntityFactoryTest.java, src/test/java/uk/gov/pay/ledger/queue/QueueMessageReceiverForTransactionIT.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
Depends on https://github.com/alphagov/pay-ledger/pull/2026
Agreement ID on payment transactions should now be persisted in a column
rather than transaction details.
Update the myriad entities/ mappers/ fixtures/ builders to make this
happen and cover the persisting/ retrieving with tests.
=> PP-9530 Payment transaction entity agreement ID

openapi/ledger_spec.yaml, src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoSearchIT.java
Depends on https://github.com/alphagov/pay-ledger/pull/2027 and https://github.com/alphagov/pay-ledger/pull/2026
Add `agreement_id` query param to transactions search.
Allow consumers (public api/ admin tool) to provice the `agreement_id`
query param and filter transactions by agreement id.
This will be used by the admin tool to show payments that have been
taken for a given agreement.
=> PP-9530 Transaction search params supports agreement ID

src/main/java/uk/gov/pay/ledger/transaction/model/Payment.java, src/main/java/uk/gov/pay/ledger/transaction/model/TransactionFactory.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/TransactionView.java, src/test/java/uk/gov/pay/ledger/transaction/model/TransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
For payment transactions, return a "disputed" field on the transaction in the response to the request GET a single transaction or search transactions.
The value of this field comes from the value of the "disputed" field on the "transaction_details" from the database if this field exists, otherwise it defaults to false.
=> PP-9671 Return disputed field on transactions

src/test/java/uk/gov/pay/ledger/pact/ContractTest.java
- `evidence_due_date` is no longer stored as a unix epoch but as a string representation of datetime. Change the pact test to use the latter one.
=> PP-9675 fix pact test

src/main/resources/migrations/00075_add_payment_instrument_types.sql
Adds
* payment instrument `type`
* `card_type`
* `first_digits_card_number`
Most of this data is already provided by Connector when taking a
payment, it should be mapped and stored by the event store.
=> PP-9545 Add missing payment instrument columns

src/main/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactory.java
- Set `Net` in the CSV download only if `net_amount` is available for disputes.
=> PP-9673 CSV download - fix net_amount for dispute transaction

src/main/java/uk/gov/pay/ledger/agreement/dao/AgreementDao.java, src/main/java/uk/gov/pay/ledger/agreement/dao/AgreementMapper.java, src/main/java/uk/gov/pay/ledger/agreement/dao/PaymentInstrumentDao.java, src/main/java/uk/gov/pay/ledger/agreement/entity/AgreementEntity.java, src/main/java/uk/gov/pay/ledger/agreement/entity/PaymentInstrumentEntity.java, src/main/java/uk/gov/pay/ledger/agreement/model/Agreement.java, src/main/java/uk/gov/pay/ledger/agreement/model/PaymentInstrument.java, src/main/resources/migrations/00075_add_payment_instrument_types.sql, src/test/java/uk/gov/pay/ledger/agreement/entity/AgreementsFactoryTest.java, src/test/java/uk/gov/pay/ledger/agreement/resource/AgreementResourceIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/AgreementFixture.java, src/test/java/uk/gov/pay/ledger/util/fixture/PaymentInstrumentFixture.java
Depends on https://github.com/alphagov/pay-ledger/pull/2048
Adds `type`, `card_type` and `first_digits_card_number` properties to payment instrument entities and mappers.
---
Include the commons enum `PaymentInstrumentType` across the various
entities and mappers required to set and read from the payment
instrument table.
---
Now that the agreement status is represented with a pay java commons
enum, use this when storing projections from the event stream and
reading from the projection database.
=> PP-9545 Add missing payment instrument properties

.gitignore, .pre-commit-config.yaml, .secrets.baseline, openapi/ledger_spec.yaml, src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java, src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/test/java/uk/gov/pay/ledger/pact/ContractTest.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java
Accept a transaction_type query parameter for the `/v1/transaction/{parentTransactionExternalId}/transaction` endpoint.
This will filter the child transactions for the specified parent transaction to only return results with the requested transaction type.
This will be used by connector to query for refunds for a transaction without also returning disputes.
Add a pact state that will add a transaction that has both refund and dispute child transactions so we can add a pact test using the `transaction_type` query parameter.
Regenerate the `.secrets.baseline` using v1.2.0 of detect-secrets, which we are now using in pay-connector. Update `.pre-commit-config.yaml` to use this version of detect-secrets.
=> PP-9671 Accept transaction_type query parameter

src/main/java/uk/gov/pay/ledger/agreement/resource/AgreementResource.java, src/main/java/uk/gov/pay/ledger/agreement/resource/AgreementSearchParams.java, src/test/java/uk/gov/pay/ledger/agreement/resource/AgreementResourceIT.java, src/test/java/uk/gov/pay/ledger/agreement/resource/AgreementResourceTest.java
Use the commons `AgreementStatus` enum to accept agreement search
params. Internally (in the database, in events) this is represented as
the default string version of an enum which default to caps. Public API
will be passing in parsed strings from users which will be lowercase.
Using a case insensitive match on the search param will allow Ledger to
return the expected data but will throw a reasonable error if values
that aren't present in the enum (and therefore can't have been written
to the database) are passed in.
=> PP-9545 Agreement search status accepts case insensitive

src/main/java/uk/gov/pay/ledger/agreement/resource/AgreementSearchParams.java
Transactions expects an `account_id` for search, this is generally
provided by public api. Agreements originally specified this as
`gateway_account_id` as it's more descriptive but change it back to
`account_id` to bring it in line with the other endpoints public api
interacts with.
=> PP-9545 Make search param consistent with transactions

src/main/java/uk/gov/pay/ledger/queue/EventMessage.java, src/main/java/uk/gov/pay/ledger/queue/EventMessageHandler.java, src/test/java/uk/gov/pay/ledger/queue/EventMessageHandlerTest.java
Previously, we were deserialising the event message coming from
SQS queue and then re-serialising it to send it on to SNS.
We weren't re-serialising the event in an identical way, and were
serialising the `event_details` as an escaped string rather than a
nested JSON object.
To avoid these deserialisation mistakes, get the raw string contained in
the original SQS message to send to SNS. The intention is that ledger
does not change the message, and this will ensure this.
=> PP-9292 Send raw event message to SNS

src/main/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactory.java, src/test/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceCsvIT.java
This column has been causing confusion for some services, so we are changing how it is calculated:
* It remains the same as before for successful payments (amount, plus surcharge if present).
* It is now zero for all non-successful completed payments.
* It is now left blank for any payments still in progress.
These changes will also affect the TotalAmount column in the Payments To Your Bank Account download.
=> PP-9593: Change TotalAmount in report CSV

src/main/java/uk/gov/pay/ledger/transaction/service/TransactionService.java, src/test/java/uk/gov/pay/ledger/event/dao/EventDaoIT.java
We've used 16 previously and the email we send to services state we use 16 too.
=> PP-10182: Change redacted reference string to 16 chars

.github/workflows/_run-pact-provider-tests.yml, .github/workflows/run-tests.yml, src/test/java/uk/gov/pay/ledger/rule/PostgresTestDocker.java, src/test/java/uk/gov/pay/ledger/rule/SqsTestDocker.java, src/test/resources/config/test-config.yaml
- removed use of `govuk/postgres:11`, baselining on architecture agnostic `postgres:11.16`
- updated local sqs image to be consistent with other Pay applications, updated sqs waiting strategy to be compatible with new image
- replaced generic test container with postgres module
- the module exposes the relevant port and can automatically determine when the database is healthy, removing the need to sleep the thread
- updated GHA to use new images
- limit number of open database connections during integration testing, resolves intermittent PSQLException
=> PP-10004 M1 support for integration tests

.github/workflows/run-tests.yml, .secrets.baseline, README.MD, openapi/ledger_spec.yaml
Add a check in the GitHub actions workflow that runs on PR builds to check whether there are uncommitted changes after running `mvn compile`. If there are, this suggests that there have been changes to the API specification and the OpenApi file has not been regenerated. Fail the build when uncommitted changes are detected.
Add section for the API specification in the README with a link to view in Swagger Editor.
=> PP-10255 Check if there are uncommitted changes to OpenApi file

src/main/resources/migrations/00076_add_user_identifier_column_to_agreements_table.sql
The user identifier is currently included in the event stream when agreements are created, this data needs to be represented on the Ledger agreement resource and will then be used by the API and the admin tool.
Add a column to the agreements projection table to allow the object mapper to appropriately set the `user_identifier` attribute.
Index the user identifier using a standard btree index, this will allow us filter agreements by this value if required in the future. It's likely that most agreements won't come with user identifiers initially so this shouldn't use up much space.
=> PP-10437 Add user identifier column to agreements table

src/main/java/uk/gov/pay/ledger/agreement/dao/AgreementDao.java, src/main/java/uk/gov/pay/ledger/agreement/dao/AgreementMapper.java, src/main/java/uk/gov/pay/ledger/agreement/entity/AgreementEntity.java, src/main/java/uk/gov/pay/ledger/agreement/model/Agreement.java, src/test/java/uk/gov/pay/ledger/agreement/AgreementDaoIT.java, src/test/java/uk/gov/pay/ledger/agreement/entity/AgreementsFactoryTest.java, src/test/java/uk/gov/pay/ledger/agreement/resource/AgreementResourceIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/AgreementFixture.java
Depends on https://github.com/alphagov/pay-ledger/pull/2340
Add `userIdentifier` to the agreement entity which maps to the new
`user_identifier` column introduced in
https://github.com/alphagov/pay-ledger/pull/2340.
Set mappings between the agreement entity and agreement model, assert
that this is appropriately then shown from the agreement resource.
=> PP-10437 Serialisation for user identifier on agreements 

.secrets.baseline, src/test/java/uk/gov/pay/ledger/agreement/AgreementDaoIT.java, src/test/java/uk/gov/pay/ledger/agreement/resource/AgreementResourceIT.java, src/test/java/uk/gov/pay/ledger/pact/ContractTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/AgreementFixture.java
- Add a pact state to set up a number of agreements for use by a public API pact to to test the page/display size query parameters and the links returned in the response.
- Convert AgreementFixture to use the builder pattern.
=> PP-10485 Add pact state for search agreements

src/main/java/uk/gov/pay/ledger/agreement/resource/AgreementResource.java, src/main/java/uk/gov/pay/ledger/agreement/service/AgreementService.java, src/test/java/uk/gov/pay/ledger/agreement/resource/AgreementResourceTest.java, src/test/java/uk/gov/pay/ledger/agreement/service/AgreementServiceTest.java
Move the bulk of the logic for endpoint `/v1/agreement/{agreementExternalId}` into `AgreementService`, to facilitate testing.  We're about to make this more complex by adding some filters, so taking the existing logic out of the resource class is worthwhile.
=> PP-10445: Factor out some resource logic into a service

src/test/java/uk/gov/pay/ledger/pact/event/DisputeCreatedEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/DisputeEvidenceSubmittedEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/DisputeLostEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/DisputeWonEventQueueConsumerIT.java
- For the dispute consumer pact tests, dispute events are sent to the SQS queue with `parent_resource_external_id`. No transaction exists for the `parent_resource_external_id`, so the dispute event projection fails and the message stays in the SQS queue.
- SQS queue message can then be processed later by another test which results in multiple dispute events in the database. One from the previous test and another for the current one. This causes tests to fail as the event returned by the database could be a different one.
- Dispute Itests also don't assert the transaction. At the time of writing the tests, we were not projecting dispute events.
- Updated test to insert parent transaction at the time of setup
- Asserting transaction data too as we have projection enabled for dispute events
=> PP-10263 Fix flakey dispute ITests

src/main/java/uk/gov/pay/ledger/agreement/resource/AgreementResource.java, src/main/java/uk/gov/pay/ledger/agreement/resource/AgreementSearchParams.java, src/main/java/uk/gov/pay/ledger/agreement/service/AgreementService.java, src/test/java/uk/gov/pay/ledger/agreement/resource/AgreementResourceIT.java, src/test/java/uk/gov/pay/ledger/agreement/resource/AgreementResourceTest.java, src/test/java/uk/gov/pay/ledger/agreement/service/AgreementServiceTest.java, src/test/java/uk/gov/pay/ledger/queue/QueueMessageReceiverIT.java
* New filters are `account_id` and `service_id`
* Either or both of these must be provided, unless the `override_account_or_service_id_restriction` query param is submitted and set to true
* I've reordered some of the existing integration tests
=> PP-10445: Add filters to `/v1/agreement/{agreementExternalId}` endpoint

.secrets.baseline, src/test/java/uk/gov/pay/ledger/pact/ContractTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
Add pact state that inserts a recurring payment for an agreement with with the specified ID so we can have a pact test for searching for payments by agreement_id.
=> PP-10485 Add pact state for search payments by agreement_id

src/main/java/uk/gov/pay/ledger/filters/LoggingMDCRequestFilter.java, src/main/java/uk/gov/pay/ledger/filters/LoggingMDCResponseFilter.java
- If the request has the `agreementExternalId` path paremeter, add it to the MDC to be included as a field for log lines.
=> PP-10488 Add agreement_external_id to MDC

.github/workflows/_run-pact-provider-tests.yml
Located and replaced all usages of set-output commands in our workflows.
=> PP-10675: replaced usage of set-output in github actions workflow

pom.xml
Reverts alphagov/pay-ledger#2482
=> Revert "Bump dropwizard-dependencies from 2.1.4 to 2.1.5"

.github/dependabot.yml
Dependabot is keen to update to `eclipse-temurin:20-jre` - we're happy with `11-jre` for the moment.
=> BAU: Pin Java base image to v11

src/main/java/uk/gov/pay/ledger/app/LedgerModule.java, src/main/java/uk/gov/pay/ledger/app/config/SnsConfig.java, src/main/resources/config/config.yaml, src/test/resources/config/test-config.yaml
Allow the SNS client to be built with an overridden endpoint to allow local testing.
Note that I have matched the naming used in the very similar SQS config, and have also matched the indentation style to that even though it feels very strange to me (but then I'm not a java person 😄)
One big difference is SNS is using (and is already using) aws-sdk v2, and SQS is using aws-sdk v1, so the actual client construction and configuration is quite different.
=> PP-10762: Allow ledger to use an overriden SNS endpoint for local testing

pom.xml, src/main/java/uk/gov/pay/ledger/queue/EventMessageHandler.java, src/test/java/uk/gov/pay/ledger/queue/EventMessageHandlerTest.java
Add logging so that we can determine whether ledger is successfully publishing messages to SNS.
Use shared logging keys "resource_external_id", "sqs_message_id" and "ledger_event_type". This means that logs lines that previously had key "event_type" will now have key "ledger_event_type".
=> PP-10538 Log when ledger publishes to SNS

src/main/java/uk/gov/pay/ledger/transaction/model/Payment.java, src/main/java/uk/gov/pay/ledger/transaction/model/TransactionFactory.java, src/test/java/uk/gov/pay/ledger/event/model/TransactionEntityFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/model/TransactionFactoryTest.java
- add canRetry field to `Payment` model (it will be used to build `ExternalTransactionState`)
=> PP-10982 add canRetry field to Payment model

.secrets.baseline, openapi/ledger_spec.yaml, src/main/java/uk/gov/pay/ledger/transaction/model/TransactionFactory.java, src/main/java/uk/gov/pay/ledger/transaction/search/model/TransactionView.java, src/main/java/uk/gov/pay/ledger/transaction/state/ExternalTransactionState.java, src/test/java/uk/gov/pay/ledger/transaction/model/TransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
- add canRetry to `ExternalTransactionState`
- implement including canRetry when getting/searching transactions (if applicable)
- add tests
=> PP-10982 add can_retry to external transaction state

src/main/java/uk/gov/pay/ledger/queue/EventMessageHandler.java, src/test/java/uk/gov/pay/ledger/queue/EventMessageHandlerTest.java
- Currently, Ledger is attempting to publish events other than disputes to `card_payment_events` SNS topic. We can restrict this to PAYMENT/REFUNDS events as consumers (webhooks/adminusers) of SNS do not handle events other than PAYMENT/REFUND/DISPUTE.
- Also Ledger currently fails to publish agreement events to SNS and logs `Failed to publish event for message` due to `NullPointerException` when getting `rawMessageBody` (as it is only available for events from SQS but not agreements which are sent synchronously)
=> PP-10509 Don't publish agreement events to SNS

src/main/java/uk/gov/pay/ledger/agreement/service/AgreementService.java, src/main/java/uk/gov/pay/ledger/event/service/EventService.java, src/main/java/uk/gov/pay/ledger/queue/EventMessageHandler.java, src/test/java/uk/gov/pay/ledger/agreement/resource/AgreementResourceIT.java, src/test/java/uk/gov/pay/ledger/agreement/service/AgreementServiceTest.java, src/test/java/uk/gov/pay/ledger/event/service/EventServiceTest.java, src/test/java/uk/gov/pay/ledger/queue/EventMessageHandlerTest.java
- Currently, when projecting agreement (during GET), events for the resource_external_id are processed and mapped to the agreement.
- If events for the resource_external_id are not of type AGREEMENT, Ledger still considers them and attempts to project events which cause an exception (`java.lang.RuntimeException: No salient event found for event digest for agreement with external ID`). This is because agreement status cannot be derived from these events
- So filtering events by resource type AGREEMENT as well. If no events exist, it will result in 404 which is expected
- Refactored `EventMessageHandler.processSingleMessage` method to extract publishing to SNS functionality as the method is getting complex.
=> PP-10509 Get EventDigest by resource ID and type

pom.xml
- added `junit-vintage-engine` test scoped dependency to resolve breaking changes in `dropwizard` 2.1.5
=> BAU bump dropwizard -> 2.1.6

src/test/java/uk/gov/pay/ledger/pact/event/PaymentDetailsTakenFromPaymentInstrumentEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java
For recurring card payments, Connector emits a new payment event `PAYMENT_DETAILS_TAKEN_FROM_PAYMENT_INSTRUMENT` to Ledger when authorising payment.
- Add a pact test in Ledger for this new event and ensure Ledger handles it correctly.
with @james-peacock-gds
=> PP-10600 add a PAYMENT_DETAILS_TAKEN_FROM_PAYMENT_INSTRUMENT event pact test

.secrets.baseline, src/test/java/uk/gov/pay/ledger/pact/ContractTest.java
Update Pact state that sets up recurring payments to set up a transaction with a particular external ID, extracted from the params specified by the Pact test.
This is so that we can add a Pact test to connector to get a single recurring payment transaction.
=> PP-11152 Update pact state

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/main/java/uk/gov/pay/ledger/util/JsonParser.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java
- Added a new DAO method to redact PII (personally identifiable information) from transactions
- Uses JSONB_SET with `false` as the last arg (`create_missing` - default is true) to replace PII from the transaction_details JSON blob.
- can't replace multiple fields at once so using nested JSONB_SET for multiple columns.
- Removed fields `reference, cardholder_name, email` from transaction_details JSON as these are not used anywhere and are also top-level DB columns. So having them in transaction_details as `<REDACTED>` doesn't add any value
- Note: `<REDACTED>` string is not finalised and may be updated later. So some other fields first/last digits card number
=> PP-11232 Add method to redact PII from transaction

src/main/java/uk/gov/pay/ledger/event/entity/EventEntity.java, src/main/resources/migrations/00078_add_transaction_redaction_info_table.sql
- Added a new table to record the created_date of the last transaction redacted for PII. The date recorded in this table will be used to select transactions to redact between a date range (on created_date which is indexed). 
- Without this, we may have to create another index based on reference (to filter out REDACTED records) and created_date (to select the next batch to redact) which is expensive.
=> PP-11232 Add TransactionRedactionInfo table

src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java
- Added method to find the created_date of first transaction. This will be used by the expunge/redact job (on the first run)  to find transactions between first transaction date and 7 years for redaction. On subsequent runs, job uses created date of last processed transaction.
=> PP-11232 Add TransactionDAO method

src/main/java/uk/gov/pay/ledger/expungeorredact/service/ExpungeOrRedactService.java, src/test/java/uk/gov/pay/ledger/expungeorredact/service/ExpungeOrRedactServiceTest.java
- Redacts PII from transactions and deletes related events
- redact PII.. method processes transactions for a date range
- start date: created_date of last processed transaction. If not gets the first transaction created date. When there are no transactions, uses the derived date up to which transactions can be redacted based on config. 
- end date: Date up to which transactions can be redacted. This is based on config (default is now() - 7 years)
- Uses the system clock provided so fixed dates can be used for testing
=> PP-11232 Update service to redact PII from transactions

src/main/java/uk/gov/pay/ledger/expungeorredact/service/ExpungeOrRedactService.java, src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/test/java/uk/gov/pay/ledger/expungeorredact/resource/ExpungeOrRedactResourceIT.java, src/test/java/uk/gov/pay/ledger/expungeorredact/service/ExpungeOrRedactServiceTest.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java
- Redacts `description` from transaction too as sometimes services use `name + dob` in this field
- Updated string to use to `<DELETED>` when redacting PII as finalised in the story
- Fixes calculation for the total no of transactions redacted and added `metrics`
- Removes {} as the `kv()`s are being added to the logline as well as additional key-value pairs and duplicating info.
=> PP-11232 Redact transaction description and some improvements

src/main/java/uk/gov/pay/ledger/expungeorredact/service/ExpungeOrRedactService.java, src/main/java/uk/gov/pay/ledger/transaction/dao/TransactionDao.java, src/test/java/uk/gov/pay/ledger/expungeorredact/service/ExpungeOrRedactServiceTest.java, src/test/java/uk/gov/pay/ledger/transaction/dao/TransactionDaoIT.java
- Updated search conditions to find transactions for redaction. Removed `=` when matching with `dateOfLastProcessedTransaction` so transaction processed in the last run is excluded in the new run
- Updates `transaction_redaction_info` after every batch of transactions processed. This is so that if the task is stopped midway (possible with perf env) it can resume after the last batch of txs processed.
=> PP-11232 Update search to find transactions to redact

src/main/java/uk/gov/pay/ledger/expungeorredact/resource/ExpungeOrRedactResource.java
- Added `x_request_id` to MDC so that the request-id is attached to all log activity for the expunge task and we can correlate the same in logs.
=> PP-11541 Add x_request_id to expunge resource

src/main/java/uk/gov/pay/ledger/expungeorredact/service/ExpungeOrRedactService.java, src/test/java/uk/gov/pay/ledger/expungeorredact/service/ExpungeOrRedactServiceTest.java
- Change metric type to Guage to record the exact number of transactions/events processed
=> PP-11569 Change metric type to Guage

.secrets.baseline, src/test/java/uk/gov/pay/ledger/pact/ContractTest.java
- For the disputes pact state, having the same created_date doesn't guarantee the order of the records returned via API (which breaks consumer pact tests). So create dispute records with different created dates.
=> BAU - Create disputes with different created_date

src/main/java/uk/gov/pay/ledger/util/CommaDelimitedSetParameter.java, src/test/java/uk/gov/pay/ledger/payout/dao/PayoutDaoSearchIT.java, src/test/java/uk/gov/pay/ledger/transaction/resource/TransactionResourceSearchIT.java
Despite the class name, the fact that account ids might not be unique is bugging me 😂 Why didn't I make [getParameters return a Set](https://github.com/alphagov/pay-ledger/blob/master/src/main/java/uk/gov/pay/ledger/util/CommaDelimitedSetParameter.java#L27)? I tried, and it's [not worth the effort](https://github.com/alphagov/pay-ledger/pull/3119).
=> bau: Ensure gateway account id query params are unique

.github/dependabot.yml, pom.xml, src/main/java/uk/gov/pay/ledger/app/LedgerApp.java, src/main/java/uk/gov/pay/ledger/app/LedgerConfig.java, src/main/java/uk/gov/pay/ledger/app/LedgerModule.java, src/main/java/uk/gov/pay/ledger/app/config/ExpungeOrRedactHistoricalDataConfig.java, src/main/java/uk/gov/pay/ledger/app/config/QueueMessageReceiverConfig.java, src/main/java/uk/gov/pay/ledger/app/config/ReportingConfig.java, src/main/java/uk/gov/pay/ledger/app/config/SnsConfig.java, src/main/java/uk/gov/pay/ledger/app/config/SqsConfig.java, src/main/java/uk/gov/pay/ledger/healthcheck/DependentResourceWaitCommand.java, src/main/java/uk/gov/pay/ledger/healthcheck/HealthCheckResource.java, src/main/java/uk/gov/pay/ledger/queue/managed/QueueMessageReceiver.java, src/main/resources/config/config.yaml
- Upgrade Dropwizard to v3 latest.
- Use dropwizard-dependencies BOM, which removes the need to pull in some dependencies ourselves
=> PP-12174 upgrade Dropwizard to version 3

pom.xml
we do not explicitly need to set mockito-junit-jupiter, Dropwizard bom takes care of the versioning.
=> BAU fix pom configuration

src/main/java/uk/gov/pay/ledger/transaction/resource/TransactionResource.java
The latest IT Healthcheck identified a number of logging statements which could potentially result in unsanitised PII being logged. In several of these cases, these logging statements were found to be unnecessary as the relevant information is already logged in the API call, so they are being removed rather than spending time investigating the risk around logging PII.
- remove unnecessary logging statements
=> PP-12767 Remove unnecessary logging

.secrets.baseline, openapi/ledger_spec.yaml, pom.xml, src/main/java/uk/gov/pay/ledger/event/dao/EventDao.java, src/main/java/uk/gov/pay/ledger/event/dao/mapper/EventTickerMapper.java, src/main/java/uk/gov/pay/ledger/event/model/EventTicker.java, src/main/java/uk/gov/pay/ledger/event/resource/EventResource.java, src/test/java/uk/gov/pay/ledger/event/dao/EventDaoIT.java, src/test/java/uk/gov/pay/ledger/event/resource/EventResourceIT.java
add the following fields to the EventTicker class for consumption via the live payments dashboard:
- service_external_id
- wallet_type
- source
- is_moto
- is_recurring
add new query parameter to `/ticker` resource for filtering events by salient event type
=> PP-12841 add new fields to EventTicker class

pom.xml, src/test/resources/logback.xml
When we upgraded to Dropwizard 3, a few scattered code was left behind that refers to com.spotify.
=> PP-12830 remove spotify

pom.xml, src/test/java/uk/gov/pay/ledger/pact/event/CancelledByUserEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/CaptureConfirmedEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/CaptureSubmittedEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/DisputeCreatedEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/DisputeEvidenceSubmittedEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/DisputeLostEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/DisputeWonEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/FeeIncurredEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/Gateway3dsExemptionResultObtainedEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/Gateway3dsInfoObtainedEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/GatewayRequires3dsAuthorisationEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/PaymentCreatedEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/PaymentDetailsEnteredEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/PaymentDetailsSubmittedByAPIEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/PaymentDetailsTakenFromPaymentInstrumentEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/PaymentIncludedInPayoutEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/PaymentNotificationCreatedEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/PayoutCreatedEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/PayoutFailedEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/PayoutPaidEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/PayoutUpdatedEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/RefundCreatedByUserEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/RefundIncludedInPayoutEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/RefundSubmittedEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/RefundSucceededEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/StatusCorrectedToCapturedToMatchGatewayStatusEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/UserEmailCollectedEventQueueConsumerIT.java
`pay-java-commons` was upgraded to Java 21. Some of the imports needed update as they are transative dependencies.
=> PP-12789 upgrade to pay-java-commons

src/test/java/uk/gov/pay/ledger/pact/event/Requested3dsExemptionQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java
Add a queue pact test for consuming `a gateway requested 3DS exemption message`
=> PP-13031 add a new pact test

src/main/resources/migrations/00079_create_procedure_check_and_execute.sql
Add stored procedure check_and_execute which allows specifying SQL, the table, and expected number of rows affected. This should allow ad-hoc modifications to be done more safely since it will automatically error if the number of rows affected wasn't exactly what you had intended
This is based on the prior art in https://github.com/alphagov/pay-connector/pull/5451/ and the RFC https://github.com/alphagov/pay-architecture/discussions/147
The formatting of the liquibase migrations meant I had to slightly edit the sql and replace the $$ quoted multi line string with single `'` quotes (and change all single quotes inside it to 2 x single quotes `''` (not double quotes)
- Locally run up pay local with this branch of ledger `pay local up --cluster card --local ledger`
- Once it's running run …
=> PP-13026: Add stored procedure to allow safer manual sql execution

src/main/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactory.java, src/test/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactoryTest.java, src/test/java/uk/gov/pay/ledger/util/fixture/TransactionFixture.java
When a payment in ledger has its requires_3ds property false the value of the ‘3-D Secure Required’ column is an empty string
=> PP-13344 return empty string

.secrets.baseline, src/test/java/uk/gov/pay/ledger/pact/ContractTest.java, src/test/java/uk/gov/pay/ledger/pact/SelfServiceContractTest.java
Add a pact state for a payment with honoured corporate exemption
=> PP-13334 add pact state

src/test/java/uk/gov/pay/ledger/pact/event/Requested3dsExemptionQueueConsumerIT.java
Temporarily ignore queue message pact test.
We are changing the property name in Connector. Ignore the test while Connector changes go through.
=> PP-13430 ignore pact test

src/test/java/uk/gov/pay/ledger/event/model/TransactionEntityFactoryTest.java, src/test/java/uk/gov/pay/ledger/pact/event/CancelledByUserEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/DisputeCreatedEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/Gateway3dsExemptionResultObtainedEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/GatewayRequires3dsAuthorisationEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/PaymentCreatedEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/PaymentDetailsEnteredEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/PaymentDetailsSubmittedByAPIEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/PaymentIncludedInPayoutEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/PaymentNotificationCreatedEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/PayoutPaidEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/RefundCreatedByUserEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/pact/event/RefundIncludedInPayoutEventQueueConsumerIT.java, src/test/java/uk/gov/pay/ledger/queue/QueueMessageReceiverIT.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueueDisputeEventFixture.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueueEventFixtureUtil.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePaymentEventFixture.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueuePayoutEventFixture.java, src/test/java/uk/gov/pay/ledger/util/fixture/QueueRefundEventFixture.java
Current setup checks if the type of the JsonElement of the Json payload coming from the provider (connector) is matching the type of the JsonElement of the Json payload of what the consumer (ledger) expects. This will match `honoured` to `HONOURED` or `EXEMPTION_HONOURED` to `HONOURED`.
Refactor `QueueEventFixtureUtil.getNestedPact()` to use strict, value based matching of strings. Also refactor existing tests to match values generated by `connector`
=> PP-13515 refactor queue msg pact tests

src/main/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactory.java, src/test/java/uk/gov/pay/ledger/transaction/model/CsvTransactionFactoryTest.java
With this change, we are fixing a bug for which disputed amounts are shown as negative numbers in the CSV files.
The logic will now consider also the state of the dispute and present the value as positive when the dispute has been won by the service.
Further information in Jira.
https://payments-platform.atlassian.net/browse/PP-13622
=> PP-13622 Fix incorrect negation for won disputes in CSV files

.github/dependabot.yml
Missed dependabot config ignoring Dropwizard 4, Guice, and Eclipse Link.
=> BAU fix dependabot config

pom.xml, src/main/resources/config/config.yaml
We can migrate to 4.x now we use Dropwizard 4, which would allow us to remove some custom code.
=> PP-13991 refactor config to use dropwizard-sentry 4
